package com.likes.common.enums;

/**
 * 系统参数的枚举，替代cpt的SystemInfoEnum
 * cpt使用例子：  systemInfoRest.queryByName(SystemInfoEnum.LOTTERY_VERSION_ZIP_URL.name());
 * 现在使用例子： systemInfoRest.queryByName(SysParameterEnum.REGISTER_MEMBER_ODDS.getCode());
 */
public enum AnchorSysParameterEnum {
    ANCHOR_PLATFORM_NAME("ANCHOR_PLATFORM_NAME", "平台标识"),
    ANCHOR_SESSION_TIME("ANCHOR_SESSION_TIME", "App的token有效期"),
    ANCHOR_SMS_SENDWAIT("ANCHOR_SMS_SENDWAIT", "短信验证码发送等待时间"),
    ANCHOR_SMS_VALIDATE("ANCHOR_SMS_VALIDATE", "短信验证码有效期"),
    ANCHOR_H5_URL("ANCHOR_H5_URL", "分享H5注册页面地址"),
    ANCHOR_DOWNLOAD_URL("ANCHOR_DOWNLOAD_URL", "APP下载页"),
    ANCHOR_OFFLINE_TIME("ANCHOR_OFFLINE_TIME", "直播强制下线时间"),
    ANCHOR_NOTALK_TIME("ANCHOR_NOTALK_TIME", "禁言时间"),
    ANCHOR_SHORTMSG_LIMIT("ANCHOR_SHORTMSG_LIMIT", "同IP同手机号短信发送限制条数"),
    ANCHOR_SRS_KEY("ANCHOR_SRS_KEY", "直播服务加密key"),
    ANCHOR_ONLINE_MERGER("ANCHOR_ONLINE_MERGER", "直播间断上线记录合并时间"),
    ANCHOR_VIDEO_GOLDNUM("ANCHOR_VIDEO_GOLDNUM", "发表短视讯"),
    ANCHOR_ARTICLE_GOLDNUM("ANCHOR_ARTICLE_GOLDNUM", "发表贴文"),
    ANCHOR_RECOMMEND_USER("ANCHOR_RECOMMEND_USER", "推荐用户"),
    ANCHOR_H5_APPDOWNLOAD("ANCHOR_H5_APPDOWNLOAD", "H5下载页"),
    ANCHOR_APPDOWNLOAD_SENTENCE("ANCHOR_APPDOWNLOAD_SENTENCE", "分享的文本"),
    ANCHOR_SMS_ONOFF("ANCHOR_SMS_ONOFF", "短信开关"),
    ANCHOR_SMS_REAL_SEND("ANCHOR_SMS_REAL_SEND", "短信是否真实调用发送"),
    ANCHOR_REQ_FREQUENCY("ANCHOR_REQ_FREQUENCY", "直播在线数据刷新频率"),
    ANCHOR_SESSION_TIME_BACK("ANCHOR_SESSION_TIME_BACK", "后台token有效期"),
    ANCHOR_PLATFORM_SCALE("ANCHOR_PLATFORM_SCALE", "平台提成比例"),
    ANCHOR_RECHARGEMEAL_NUM("ANCHOR_RECHARGEMEAL_NUM", "充值套餐个数"),
    ANCHOR_FAMILY_INCARNATE_DAY("ANCHOR_FAMILY_INCARNATE_DAY", "家族提现日期"),
    ANCHOR_ANCHOR_INCAR_WEEKDAY("ANCHOR_ANCHOR_INCAR_WEEKDAY", "主播每周几提现"),
    ANCHOR_ANCHOR_INCAR_TIME("ANCHOR_ANCHOR_INCAR_TIME", "主播提现时间段"),
    ANCHOR_OFF_RECHARGE_KEFU("ANCHOR_OFF_RECHARGE_KEFU", "线下充值订单客服"),
    ANCHOR_H5_SHORT_URL("ANCHOR_H5_SHORT_URL", "分享H5注册页面地址"),
    ANCHOR_GUANFANG_RECOMCODE("ANCHOR_GUANFANG_RECOMCODE", "官方邀请码"),
    ANCHOR_LIVE_HOME_KEFU("ANCHOR_LIVE_HOME_KEFU", "直播列表得客服微信"),
    ANCHOR_TIXIAN_KEFU("ANCHOR_TIXIAN_KEFU", "提现客服微信"),
    ANCHOR_H5_APPDOWNLOAD_WEB("ANCHOR_H5_APPDOWNLOAD_WEB", "给web端用扫描下载APP"),
    ANCHOR_WEBSITE_DOWNCODE("ANCHOR_WEBSITE_DOWNCODE", "官网二维码下载APP"),

    ANCHOR_KYQP_API_URL("ANCHOR_KYQP_API_URL", "开元棋牌API接口"),
    ANCHOR_KYQP_API_RECORD_URL("ANCHOR_KYQP_API_RECORD_URL", "开元棋牌独立拉单接口"),
    ANCHOR_KYQP_AGENT("ANCHOR_KYQP_AGENT", "开元棋牌Agent"),
    ANCHOR_KYQP_DESKEY("ANCHOR_KYQP_DESKEY", "开元棋牌Deskey"),
    ANCHOR_KYQP_MD5KEY("ANCHOR_KYQP_MD5KEY", "开元棋牌Md5key"),
    ANCHOR_KYQP_LINECODE("ANCHOR_KYQP_LINECODE", "开元棋牌lineCode"),
    ANCHOR_KYQP_BACKURL("ANCHOR_KYQP_BACKURL", "开元棋牌回调接口"),

    ANCHOR_MANAGE_ISIP("ANCHOR_MANAGE_ISIP", "BB直播后台是否启用白名单"),
    ANCHOR_PAY_RETURNURL("ANCHOR_PAY_RETURNURL", "支付成功后跳转页面"),
    ANCHOR_PAY_URL("ANCHOR_PAY_URL", "请求支付中心路径"),
    ANCHOR_BET_RATIO("ANCHOR_BET_RATIO", "直播间主播彩票分成比例"),
    ANCHOR_GP_LUCKRATE("ANCHOR_GP_LUCKRATE", "大牛牛人计划基础胜率"),

    ANCHOR_TENLIVE_SECRETID("ANCHOR_TENLIVE_SECRETID", "腾讯云直播SecretId"),
    ANCHOR_TENLIVE_SECRETKEY("ANCHOR_TENLIVE_SECRETKEY", "腾讯云直播SecretKey"),
    ANCHOR_TENLIVE_CALLBACKKEY("ANCHOR_TENLIVE_CALLBACKKEY", "腾讯云推流回调key"),

    ANCHOR_ASTRICT_IP_LOGIN_STATUS("ANCHOR_ASTRICT_IP_LOGIN_STATUS", "限制ip登录状态"),
    ANCHOR_ASTRICT_IP_GROUP("ANCHOR_ASTRICT_IP_GROUP", "限制的ip"),

    ANCHOR_HINT_REFRESH_TIME("ANCHOR_HINT_REFRESH_TIME", "提示刷新时间"),
    ANCHOR_HINT_VOICE_STATUS("ANCHOR_HINT_VOICE_STATUS", "提示声音开关"),

    ANCHOR_FREEZE_ACCOUNT_STATUS("ANCHOR_FREEZE_ACCOUNT_STATUS", "冻结账号"),
    ANCHOR_SHENG_XIAO("ANCHOR_SHENG_XIAO", "当前年生肖"),
    ANCHOR_ODDS_SET("ANCHOR_ODDS_SET", "赔率设置"),

    ANCHOR_REGISTER_MEMBER_ODDS("ANCHOR_REGISTER_MEMBER_ODDS", "注册用户赔率"),
    ANCHOR_REGISTER_MEMBER_BACKWATER("ANCHOR_REGISTER_MEMBER_BACKWATER", "注册用户返水"),

    ANCHOR_DEMO_ACCOUNT_REGISTER_TIMES("ANCHOR_DEMO_ACCOUNT_REGISTER_TIMES", "试玩账号注册次数"),
    ANCHOR_REVOKE_SECOND("ANCHOR_REVOKE_SECOND", "开放撤单多少秒后生效"),

    ANCHOR_BIND_BANK_CARD("ANCHOR_BIND_BANK_CARD", "充值必须绑卡"),
    ANCHOR_BIND_PHONE("ANCHOR_BIND_PHONE", "开启手机绑定"),
    ANCHOR_BIND_ALIPAY("ANCHOR_BIND_ALIPAY", "支付宝绑定显示"),
    ANCHOR_BIND_BANK_CARD_AMOUNT("ANCHOR_BIND_BANK_CARD_AMOUNT", "每人可绑银行卡张数"),

    ANCHOR_WITHDRAWAL_AMOUNT("ANCHOR_WITHDRAWAL_AMOUNT", "提现额度设置"),
    ANCHOR_MAX_WITHDRAW_DEPOSIT_TIMES("ANCHOR_MAX_WITHDRAW_DEPOSIT_TIMES", "每天最大提现次数"),

    ANCHOR_GENERAL_WITHDRAW_DEPOSIT_MAX("ANCHOR_GENERAL_WITHDRAW_DEPOSIT_MAX", "普通会员单次提现最大额度"),
    ANCHOR_GENERAL_WITHDRAW_DEPOSIT_MIN("ANCHOR_GENERAL_WITHDRAW_DEPOSIT_MIN", "普通会员单次提现最小额度"),

    ANCHOR_TOPUP_WITHDRAW_DEPOSIT_MAX("ANCHOR_TOPUP_WITHDRAW_DEPOSIT_MAX", "充值会员单次提现最大额度"),
    ANCHOR_TOPUP_WITHDRAW_DEPOSIT_MIN("ANCHOR_TOPUP_WITHDRAW_DEPOSIT_MIN", "充值会员单次提现最小额度"),

    ANCHOR_NO_TOP_UP_START_TIME("ANCHOR_NO_TOP_UP_START_TIME", "不可提现开始时间"),
    ANCHOR_NO_TOP_UP_END_TIME("ANCHOR_NO_TOP_UP_END_TIME", "不可提现结束时间"),

    ANCHOR_WITHDRAW_DEPOSIT_EXPLAIN("ANCHOR_WITHDRAW_DEPOSIT_EXPLAIN", "提现说明"),
    ANCHOR_IOS_FIRST_REGISTER_GIVE_MONEY("ANCHOR_IOS_FIRST_REGISTER_GIVE_MONEY", "每台IOS手机第一次注册赠送金额"),

    ANCHOR_ANDROID_FIRST_REGISTER_GIVE_MONEY("ANCHOR_ANDROID_FIRST_REGISTER_GIVE_MONEY", "每台ANDROID手机第一次注册赠送金额"),

    ANCHOR_BACKWATER_VIP_SCALE("ANCHOR_BACKWATER_VIP_SCALE", "VIP返水比例"),
    ANCHOR_BACKWATER_PLATFORM_SCALE("ANCHOR_BACKWATER_PLATFORM_SCALE", "后台返水比例"),
    ANCHOR_BACKWATER_PATTERN("ANCHOR_BACKWATER_PATTERN", "返水模式"),
    ANCHOR_BACKWATER_WITHDRAW("ANCHOR_BACKWATER_WITHDRAW", "返水可提"),

    ANCHOR_BE_SHARER_BET_MIN_MONEY("ANCHOR_BE_SHARER_BET_MIN_MONEY", "被分享者最低投注金额"),

    ANCHOR_SHARER_GIVE_MONEY("ANCHOR_SHARER_GIVE_MONEY", "分享者获得赠送金额"),
    ANCHOR_SHARER_GIVE_MONEY_WAY("ANCHOR_SHARER_GIVE_MONEY_WAY", "分享者获得赠送金额方式"),

    ANCHOR_BE_SHARER_IOS_REGISTER_MONEY("ANCHOR_BE_SHARER_IOS_REGISTER_MONEY", "被分享者IOS成功注册获得金额"),
    ANCHOR_BE_SHARER_ANDROID_REGISTER_MONEY("ANCHOR_BE_SHARER_ANDROID_REGISTER_MONEY", "被分享者ANDROID成功注册获得金额"),
    ANCHOR_BE_SHARER_GIVE_MONEY_WAY("ANCHOR_BE_SHARER_GIVE_MONEY_WAY", "被分享者获得赠送金额方式"),

    ANCHOR_SHARE_BACKWATER_QUOTA("ANCHOR_SHARE_BACKWATER_QUOTA", "分享返水限额类型"),
    ANCHOR_SHARE_BACKWATER_SCALE("ANCHOR_SHARE_BACKWATER_SCALE", "分享返水比例(‰)"),

    ANCHOR_WEEK_FIRST_TOP_UP_STATUS("ANCHOR_WEEK_FIRST_TOP_UP_STATUS", "周周首充活动状态"),
    ANCHOR_WEEK_FIRST_TOP_UP_SCALE("ANCHOR_WEEK_FIRST_TOP_UP_SCALE", "周周首充活动赠送比例(%)"),
    ANCHOR_WEEK_FIRST_TOP_UP_MAX_MONEY("ANCHOR_WEEK_FIRST_TOP_UP_MAX_MONEY", "周周首充活动礼金上限"),

    ANCHOR_ACTIVITY_FIRST_TOP_UP_STATUS("ANCHOR_ACTIVITY_FIRST_TOP_UP_STATUS", "活动首充活动状态"),
    ANCHOR_ACTIVITY_FIRST_TOP_UP_SCALE("ANCHOR_ACTIVITY_FIRST_TOP_UP_SCALE", "活动首充活动赠送比例(%)"),
    ANCHOR_ACTIVITY_FIRST_TOP_UP_MAX_MONEY("ANCHOR_ACTIVITY_FIRST_TOP_UP_MAX_MONEY", "活动首充活动礼金上限"),
    ANCHOR_ACTIVITY_FIRST_TOP_UP_START_TIME("ANCHOR_ACTIVITY_FIRST_TOP_UP_START_TIME", "活动首充活动开启时间"),
    ANCHOR_ACTIVITY_FIRST_TOP_UP_END_TIME("ANCHOR_ACTIVITY_FIRST_TOP_UP_END_TIME", "活动首充活动结束时间"),
    ANCHOR_ACTIVITY_FIRST_TOP_UP_BACK_SCALE("ANCHOR_ACTIVITY_FIRST_TOP_UP_BACK_SCALE", "活动首充活动返还比例"),

    ANCHOR_SHARE_BACKWATER_SCALE_ONE("ANCHOR_SHARE_BACKWATER_SCALE_ONE", "1层分享返水比例(‰)"),
    ANCHOR_SHARE_BACKWATER_SCALE_TWO("ANCHOR_SHARE_BACKWATER_SCALE_TWO", "2层分享返水比例(‰)"),

    ANCHOR_LOTTERY_VERSION_ZIP_URL("ANCHOR_LOTTERY_VERSION_ZIP_URL", "150"),
    ANCHOR_SYS_FILE_UPLOAD_URL("ANCHOR_SYS_FILE_UPLOAD_URL", "后台文件上传路径"),
    ANCHOR_SYSTEM_RECHARGE_TIME("ANCHOR_SYSTEM_RECHARGE_TIME", "充值预计时间"),
    ANCHOR_SYSTEM_WITH_DRAW_TIME("ANCHOR_SYSTEM_WITH_DRAW_TIME", "提现预计时间"),
    ANCHOR_SYS_FILE_DOWNLOAD_URL("ANCHOR_SYS_FILE_DOWNLOAD_URL", "1"),

    ANCHOR_LHTK_MANUAL_MANAGEMENT_NAMES("ANCHOR_LHTK_MANUAL_MANAGEMENT_NAMES", "六合图库手动管理图片名"),
    ANCHOR_IP_ENROLL("ANCHOR_IP_ENROLL", "同IP注册限制"),

    ANCHOR_USER_CAPTCHA_ONE_DAY_COUNT("ANCHOR_USER_CAPTCHA_ONE_DAY_COUNT", "用户每天能获取的验证码次数"),
    ANCHOR_USER_CAPTCHA_FREEZE_HOURS("ANCHOR_USER_CAPTCHA_FREEZE_HOURS", "用户验证码禁用时长。单位：小时"),

    ANCHOR_CHAT_ROOM_CONTENT("ANCHOR_CHAT_ROOM_CONTENT", "聊天室全员禁言"),
    ANCHOR_CHAT_ROOM("ANCHOR_CHAT_ROOM", "聊天室启停"),
    ANCHOR_CHAT_ROOM_PACK("ANCHOR_CHAT_ROOM_PACK", "聊天室红包启停"),
    ANCHOR_CHAT_PACK_NUMBER("ANCHOR_CHAT_PACK_NUMBER", "聊天室个数"),
    ANCHOR_CHAT_PACK_AMOUT("ANCHOR_CHAT_PACK_AMOUT", "聊天室红包金额"),

    ANCHOR_REGISTER_ACCOUNT_CAN_RECOMMEND("ANCHOR_REGISTER_ACCOUNT_CAN_RECOMMEND", "注册型用户是否可评论,1:可评论;0:不能评论"),
    ANCHOR_REWARD_SET_STATUS("ANCHOR_REWARD_SET_STATUS", "打赏开关"),
    ANCHOR_AUDIT_SET_STATUS("ANCHOR_AUDIT_SET_STATUS", "审核开关"),
    ANCHOR_CRATE_AGENT_DATA_SWITCH("ANCHOR_CRATE_AGENT_DATA_SWITCH", "项目启动时是否要迁移代理数据"),
    ANCHOR_KILL_PLATFORM("ANCHOR_KILL_PLATFORM", "设置杀号的所有平台信息"),
    ANCHOR_VEST_BAG_SWITCH("ANCHOR_VEST_BAG_SWITCH", "0:马甲包开启,1:马甲包关闭"),
    ANCHOR_PRE_AEARD("ANCHOR_PRE_AEARD", "设置预开奖信息"),
    ANCHOR_GOD_PLAN_LOW_LOTTERY("ANCHOR_GOD_PLAN_LOW_LOTTERY", "大神计划低频彩"),
    ANCHOR_PROXY_WORK_STATUS("ANCHOR_PROXY_WORK_STATUS", "1"),
    ANCHOR_WEB_FIRST_REGISTER_GIVE_MONEY("ANCHOR_WEB_FIRST_REGISTER_GIVE_MONEY", "每台WEB第一次注册赠送金额"),
    ANCHOR_H5_FIRST_REGISTER_GIVE_MONEY("ANCHOR_H5_FIRST_REGISTER_GIVE_MONEY", "每台H5第一次注册赠送金额"),

    ANCHOR_LIVE_USER_ACCOUNT_SENSITIVE_CASE("ANCHOR_LIVE_USER_ACCOUNT_SENSITIVE_CASE", "LIVE_USER_ACCOUNT_SENSITIVE_CASE"),
    ANCHOR_LIVE_REGISTER_ACCOUNT_CAN_RECOMMEND("ANCHOR_LIVE_REGISTER_ACCOUNT_CAN_RECOMMEND", "LIVE_REGISTER_ACCOUNT_CAN_RECOMMEND"),

    ANCHOR_LIVE_INVITE_CODE("ANCHOR_LIVE_INVITE_CODE", "直播间邀请码"),
    ANCHOR_OFFICE_INVITE_CODE("ANCHOR_OFFICE_INVITE_CODE", "官方邀请码"),
    ANCHOR_SWIPE_VERIFICATION_SWIFT("ANCHOR_SWIPE_VERIFICATION_SWIFT", "第三方网易验证码"),
    ANCHOR_KEFU_QQ_LINK_NUMBER("ANCHOR_KEFU_QQ_LINK_NUMBER", "客服"),

    ANCHOR_LIVE_VIDEO_ENCODE("ANCHOR_LIVE_VIDEO_ENCODE", "直播视频编码"),
    ANCHOR_LIVE_VIDEO_PUSH_ENABLE_H265("ANCHOR_LIVE_VIDEO_PUSH_ENABLE_H265", "直播推流视频编码是否启用h265方式"),
    ANCHOR_TRANSFORM_TPL_360("ANCHOR_TRANSFORM_TPL_360", "360P转码模板"),
    ANCHOR_TRANSFORM_TPL_480("ANCHOR_TRANSFORM_TPL_480", "480P转码模板"),
    ANCHOR_TRANSFORM_TPL_720("ANCHOR_TRANSFORM_TPL_720", "720P转码模板"),
    ANCHOR_ROOMTALK_LEVEL("ANCHOR_ROOMTALK_LEVEL", "直播间发言等级"),
    ANCHOR_LIVE_WS_URL("ANCHOR_LIVE_WS_URL", "直播ws服务地址"),
    ANCHOR_UNIQUE_CODE_GEN_SIZE("ANCHOR_UNIQUE_CODE_GEN_SIZE", "生成随机码的个数"),
    ANCHOR_UNIQUE_CODE_LOAD_SIZE("ANCHOR_UNIQUE_CODE_LOAD_SIZE", "每次加载随机码的个数"),
    ANCHOR_UNIQUE_CODE_BATCH_SIZE("ANCHOR_UNIQUE_CODE_BATCH_SIZE", "每次批量操作随机码的个数");

    /**
     * 系统参数的代码
     */
    private String code;

    /**
     * 方便coder理解code的意思，无其它意义
     */
    private String remark;

    AnchorSysParameterEnum(String code, String remark) {
        this.code = code;
        this.remark = remark;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}