package com.likes.common.mybatis.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class BasVideo implements Serializable {
    /**
     * 字段: bas_video.videoid<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 视频id
     *
     * @mbggenerated
     */
    private Long videoid;

    /**
     * 字段: bas_video.accno<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 会员标识号
     *
     * @mbggenerated
     */
    private String accno;

    /**
     * 字段: bas_video.videoname<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 500<br/>
     * 说明: 视频名称
     *
     * @mbggenerated
     */
    private String videoname;

    /**
     * 字段: bas_video.videoinfo<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 300<br/>
     * 说明: 视频简介
     *
     * @mbggenerated
     */
    private String videoinfo;

    /**
     * 字段: bas_video.videoimg<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 64<br/>
     * 说明: 视频封面
     *
     * @mbggenerated
     */
    private String videoimg;

    /**
     * 字段: bas_video.videourl<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 64<br/>
     * 说明: 视频url
     *
     * @mbggenerated
     */
    private String videourl;

    /**
     * 字段: bas_video.videosize<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 6<br/>
     * 说明: 视频大小 单位M
     *
     * @mbggenerated
     */
    private BigDecimal videosize;

    /**
     * 字段: bas_video.viewnum<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 收藏量
     *
     * @mbggenerated
     */
    private Long viewnum;

    /**
     * 字段: bas_video.praisenum<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 点赞量
     *
     * @mbggenerated
     */
    private Long praisenum;

    /**
     * 字段: bas_video.sharenum<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 分享量
     *
     * @mbggenerated
     */
    private Long sharenum;

    /**
     * 字段: bas_video.seenum<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 浏览数量
     *
     * @mbggenerated
     */
    private Long seenum;

    /**
     * 字段: bas_video.sortby<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 排序权重
     *
     * @mbggenerated
     */
    private Integer sortby;

    /**
     * 字段: bas_video.checkstatus<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1<br/>
     * 说明: 审核状态 1未审核  8审核通过 9审核未通过
     *
     * @mbggenerated
     */
    private Integer checkstatus;

    /**
     * 字段: bas_video.checknote<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 400<br/>
     * 说明: 审核说明
     *
     * @mbggenerated
     */
    private String checknote;

    /**
     * 字段: bas_video.is_delete<br/>
     * 必填: true<br/>
     * 缺省: b'0'<br/>
     * 长度: 1<br/>
     * 说明: 是否删除
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * 字段: bas_video.create_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 创建人
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * 字段: bas_video.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 字段: bas_video.update_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 最后修改人
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * 字段: bas_video.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bas_video
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return bas_video.videoid: 视频id
     *
     * @mbggenerated
     */
    public Long getVideoid() {
        return videoid;
    }

    /**
     * 字段: bas_video.videoid<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 视频id
     *
     * @mbggenerated
     */
    public void setVideoid(Long videoid) {
        this.videoid = videoid;
    }

    /**
     * @return bas_video.accno: 会员标识号
     *
     * @mbggenerated
     */
    public String getAccno() {
        return accno;
    }

    /**
     * 字段: bas_video.accno<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 会员标识号
     *
     * @mbggenerated
     */
    public void setAccno(String accno) {
        this.accno = accno;
    }

    /**
     * @return bas_video.videoname: 视频名称
     *
     * @mbggenerated
     */
    public String getVideoname() {
        return videoname;
    }

    /**
     * 字段: bas_video.videoname<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 500<br/>
     * 说明: 视频名称
     *
     * @mbggenerated
     */
    public void setVideoname(String videoname) {
        this.videoname = videoname;
    }

    /**
     * @return bas_video.videoinfo: 视频简介
     *
     * @mbggenerated
     */
    public String getVideoinfo() {
        return videoinfo;
    }

    /**
     * 字段: bas_video.videoinfo<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 300<br/>
     * 说明: 视频简介
     *
     * @mbggenerated
     */
    public void setVideoinfo(String videoinfo) {
        this.videoinfo = videoinfo;
    }

    /**
     * @return bas_video.videoimg: 视频封面
     *
     * @mbggenerated
     */
    public String getVideoimg() {
        return videoimg;
    }

    /**
     * 字段: bas_video.videoimg<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 64<br/>
     * 说明: 视频封面
     *
     * @mbggenerated
     */
    public void setVideoimg(String videoimg) {
        this.videoimg = videoimg;
    }

    /**
     * @return bas_video.videourl: 视频url
     *
     * @mbggenerated
     */
    public String getVideourl() {
        return videourl;
    }

    /**
     * 字段: bas_video.videourl<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 64<br/>
     * 说明: 视频url
     *
     * @mbggenerated
     */
    public void setVideourl(String videourl) {
        this.videourl = videourl;
    }

    /**
     * @return bas_video.videosize: 视频大小 单位M
     *
     * @mbggenerated
     */
    public BigDecimal getVideosize() {
        return videosize;
    }

    /**
     * 字段: bas_video.videosize<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 6<br/>
     * 说明: 视频大小 单位M
     *
     * @mbggenerated
     */
    public void setVideosize(BigDecimal videosize) {
        this.videosize = videosize;
    }

    /**
     * @return bas_video.viewnum: 收藏量
     *
     * @mbggenerated
     */
    public Long getViewnum() {
        return viewnum;
    }

    /**
     * 字段: bas_video.viewnum<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 收藏量
     *
     * @mbggenerated
     */
    public void setViewnum(Long viewnum) {
        this.viewnum = viewnum;
    }

    /**
     * @return bas_video.praisenum: 点赞量
     *
     * @mbggenerated
     */
    public Long getPraisenum() {
        return praisenum;
    }

    /**
     * 字段: bas_video.praisenum<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 点赞量
     *
     * @mbggenerated
     */
    public void setPraisenum(Long praisenum) {
        this.praisenum = praisenum;
    }

    /**
     * @return bas_video.sharenum: 分享量
     *
     * @mbggenerated
     */
    public Long getSharenum() {
        return sharenum;
    }

    /**
     * 字段: bas_video.sharenum<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 分享量
     *
     * @mbggenerated
     */
    public void setSharenum(Long sharenum) {
        this.sharenum = sharenum;
    }

    /**
     * @return bas_video.seenum: 浏览数量
     *
     * @mbggenerated
     */
    public Long getSeenum() {
        return seenum;
    }

    /**
     * 字段: bas_video.seenum<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 浏览数量
     *
     * @mbggenerated
     */
    public void setSeenum(Long seenum) {
        this.seenum = seenum;
    }

    /**
     * @return bas_video.sortby: 排序权重
     *
     * @mbggenerated
     */
    public Integer getSortby() {
        return sortby;
    }

    /**
     * 字段: bas_video.sortby<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 排序权重
     *
     * @mbggenerated
     */
    public void setSortby(Integer sortby) {
        this.sortby = sortby;
    }

    /**
     * @return bas_video.checkstatus: 审核状态 1未审核  8审核通过 9审核未通过
     *
     * @mbggenerated
     */
    public Integer getCheckstatus() {
        return checkstatus;
    }

    /**
     * 字段: bas_video.checkstatus<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1<br/>
     * 说明: 审核状态 1未审核  8审核通过 9审核未通过
     *
     * @mbggenerated
     */
    public void setCheckstatus(Integer checkstatus) {
        this.checkstatus = checkstatus;
    }

    /**
     * @return bas_video.checknote: 审核说明
     *
     * @mbggenerated
     */
    public String getChecknote() {
        return checknote;
    }

    /**
     * 字段: bas_video.checknote<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 400<br/>
     * 说明: 审核说明
     *
     * @mbggenerated
     */
    public void setChecknote(String checknote) {
        this.checknote = checknote;
    }

    /**
     * @return bas_video.is_delete: 是否删除
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * 字段: bas_video.is_delete<br/>
     * 必填: true<br/>
     * 缺省: b'0'<br/>
     * 长度: 1<br/>
     * 说明: 是否删除
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * @return bas_video.create_user: 创建人
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * 字段: bas_video.create_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 创建人
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * @return bas_video.create_time: 创建时间
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 字段: bas_video.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return bas_video.update_user: 最后修改人
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * 字段: bas_video.update_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 最后修改人
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * @return bas_video.update_time: 更新时间
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 字段: bas_video.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_video
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BasVideo other = (BasVideo) that;
        return (this.getVideoid() == null ? other.getVideoid() == null : this.getVideoid().equals(other.getVideoid()))
            && (this.getAccno() == null ? other.getAccno() == null : this.getAccno().equals(other.getAccno()))
            && (this.getVideoname() == null ? other.getVideoname() == null : this.getVideoname().equals(other.getVideoname()))
            && (this.getVideoinfo() == null ? other.getVideoinfo() == null : this.getVideoinfo().equals(other.getVideoinfo()))
            && (this.getVideoimg() == null ? other.getVideoimg() == null : this.getVideoimg().equals(other.getVideoimg()))
            && (this.getVideourl() == null ? other.getVideourl() == null : this.getVideourl().equals(other.getVideourl()))
            && (this.getVideosize() == null ? other.getVideosize() == null : this.getVideosize().equals(other.getVideosize()))
            && (this.getViewnum() == null ? other.getViewnum() == null : this.getViewnum().equals(other.getViewnum()))
            && (this.getPraisenum() == null ? other.getPraisenum() == null : this.getPraisenum().equals(other.getPraisenum()))
            && (this.getSharenum() == null ? other.getSharenum() == null : this.getSharenum().equals(other.getSharenum()))
            && (this.getSeenum() == null ? other.getSeenum() == null : this.getSeenum().equals(other.getSeenum()))
            && (this.getSortby() == null ? other.getSortby() == null : this.getSortby().equals(other.getSortby()))
            && (this.getCheckstatus() == null ? other.getCheckstatus() == null : this.getCheckstatus().equals(other.getCheckstatus()))
            && (this.getChecknote() == null ? other.getChecknote() == null : this.getChecknote().equals(other.getChecknote()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_video
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getVideoid() == null) ? 0 : getVideoid().hashCode());
        result = prime * result + ((getAccno() == null) ? 0 : getAccno().hashCode());
        result = prime * result + ((getVideoname() == null) ? 0 : getVideoname().hashCode());
        result = prime * result + ((getVideoinfo() == null) ? 0 : getVideoinfo().hashCode());
        result = prime * result + ((getVideoimg() == null) ? 0 : getVideoimg().hashCode());
        result = prime * result + ((getVideourl() == null) ? 0 : getVideourl().hashCode());
        result = prime * result + ((getVideosize() == null) ? 0 : getVideosize().hashCode());
        result = prime * result + ((getViewnum() == null) ? 0 : getViewnum().hashCode());
        result = prime * result + ((getPraisenum() == null) ? 0 : getPraisenum().hashCode());
        result = prime * result + ((getSharenum() == null) ? 0 : getSharenum().hashCode());
        result = prime * result + ((getSeenum() == null) ? 0 : getSeenum().hashCode());
        result = prime * result + ((getSortby() == null) ? 0 : getSortby().hashCode());
        result = prime * result + ((getCheckstatus() == null) ? 0 : getCheckstatus().hashCode());
        result = prime * result + ((getChecknote() == null) ? 0 : getChecknote().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_video
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", videoid=").append(videoid);
        sb.append(", accno=").append(accno);
        sb.append(", videoname=").append(videoname);
        sb.append(", videoinfo=").append(videoinfo);
        sb.append(", videoimg=").append(videoimg);
        sb.append(", videourl=").append(videourl);
        sb.append(", videosize=").append(videosize);
        sb.append(", viewnum=").append(viewnum);
        sb.append(", praisenum=").append(praisenum);
        sb.append(", sharenum=").append(sharenum);
        sb.append(", seenum=").append(seenum);
        sb.append(", sortby=").append(sortby);
        sb.append(", checkstatus=").append(checkstatus);
        sb.append(", checknote=").append(checknote);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}