package com.likes.common.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class CirclePost implements Serializable {
    /**
     * 字段: circle_post.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 字段: circle_post.user_id<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * 字段: circle_post.account<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 50<br/>
     * 说明: 发帖人
     *
     * @mbggenerated
     */
    private String account;

    /**
     * 字段: circle_post.content<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1000<br/>
     * 说明: 内容
     *
     * @mbggenerated
     */
    private String content;

    /**
     * 字段: circle_post.image<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 800<br/>
     * 说明: 图片
     *
     * @mbggenerated
     */
    private String image;

    /**
     * 字段: circle_post.is_delete<br/>
     * 必填: true<br/>
     * 缺省: b'0'<br/>
     * 长度: 1<br/>
     * 说明: 是否删除
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * 字段: circle_post.circle_postcol<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 3<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private Byte circlePostcol;

    /**
     * 字段: circle_post.me_has_praise<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 3<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private Byte meHasPraise;

    /**
     * 字段: circle_post.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 字段: circle_post.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 字段: circle_post.channel<br/>
     * 必填: false<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 马甲包频道(0为原有圈子的数据,其它数字为马甲包的数据)
     *
     * @mbggenerated
     */
    private Integer channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table circle_post
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return circle_post.id:
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 字段: circle_post.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明:
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return circle_post.user_id:
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 字段: circle_post.user_id<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明:
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * @return circle_post.account: 发帖人
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * 字段: circle_post.account<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 50<br/>
     * 说明: 发帖人
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * @return circle_post.content: 内容
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * 字段: circle_post.content<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1000<br/>
     * 说明: 内容
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * @return circle_post.image: 图片
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * 字段: circle_post.image<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 800<br/>
     * 说明: 图片
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * @return circle_post.is_delete: 是否删除
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * 字段: circle_post.is_delete<br/>
     * 必填: true<br/>
     * 缺省: b'0'<br/>
     * 长度: 1<br/>
     * 说明: 是否删除
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * @return circle_post.circle_postcol:
     *
     * @mbggenerated
     */
    public Byte getCirclePostcol() {
        return circlePostcol;
    }

    /**
     * 字段: circle_post.circle_postcol<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 3<br/>
     * 说明:
     *
     * @mbggenerated
     */
    public void setCirclePostcol(Byte circlePostcol) {
        this.circlePostcol = circlePostcol;
    }

    /**
     * @return circle_post.me_has_praise:
     *
     * @mbggenerated
     */
    public Byte getMeHasPraise() {
        return meHasPraise;
    }

    /**
     * 字段: circle_post.me_has_praise<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 3<br/>
     * 说明:
     *
     * @mbggenerated
     */
    public void setMeHasPraise(Byte meHasPraise) {
        this.meHasPraise = meHasPraise;
    }

    /**
     * @return circle_post.create_time: 创建时间
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 字段: circle_post.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return circle_post.update_time: 修改时间
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 字段: circle_post.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 修改时间
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * @return circle_post.channel: 马甲包频道(0为原有圈子的数据,其它数字为马甲包的数据)
     *
     * @mbggenerated
     */
    public Integer getChannel() {
        return channel;
    }

    /**
     * 字段: circle_post.channel<br/>
     * 必填: false<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 马甲包频道(0为原有圈子的数据,其它数字为马甲包的数据)
     *
     * @mbggenerated
     */
    public void setChannel(Integer channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_post
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CirclePost other = (CirclePost) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
                && (this.getAccount() == null ? other.getAccount() == null : this.getAccount().equals(other.getAccount()))
                && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
                && (this.getImage() == null ? other.getImage() == null : this.getImage().equals(other.getImage()))
                && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
                && (this.getCirclePostcol() == null ? other.getCirclePostcol() == null : this.getCirclePostcol().equals(other.getCirclePostcol()))
                && (this.getMeHasPraise() == null ? other.getMeHasPraise() == null : this.getMeHasPraise().equals(other.getMeHasPraise()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
                && (this.getChannel() == null ? other.getChannel() == null : this.getChannel().equals(other.getChannel()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_post
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getAccount() == null) ? 0 : getAccount().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getImage() == null) ? 0 : getImage().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getCirclePostcol() == null) ? 0 : getCirclePostcol().hashCode());
        result = prime * result + ((getMeHasPraise() == null) ? 0 : getMeHasPraise().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getChannel() == null) ? 0 : getChannel().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_post
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", account=").append(account);
        sb.append(", content=").append(content);
        sb.append(", image=").append(image);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", circlePostcol=").append(circlePostcol);
        sb.append(", meHasPraise=").append(meHasPraise);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", channel=").append(channel);
        sb.append("]");
        return sb.toString();
    }
}