package com.likes.common.mybatis.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class EsBetOrder implements Serializable {
    /**
     * 字段: es_bet_order.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 字段: es_bet_order.es_order_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 电竞注单ID
     *
     * @mbggenerated
     */
    private String esOrderId;

    /**
     * 字段: es_bet_order.es_user_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 电竞账号ID
     *
     * @mbggenerated
     */
    private Integer esUserId;

    /**
     * 字段: es_bet_order.username<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 50<br/>
     * 说明: 用户名
     *
     * @mbggenerated
     */
    private String username;

    /**
     * 字段: es_bet_order.total_amount<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 12<br/>
     * 说明: 总金额
     *
     * @mbggenerated
     */
    private BigDecimal totalAmount;

    /**
     * 字段: es_bet_order.odds_value<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 12<br/>
     * 说明: 赔率
     *
     * @mbggenerated
     */
    private BigDecimal oddsValue;

    /**
     * 字段: es_bet_order.can_win_amount<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 12<br/>
     * 说明: 可赢金额
     *
     * @mbggenerated
     */
    private BigDecimal canWinAmount;

    /**
     * 字段: es_bet_order.confirm_status<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 结算状态
     *
     * @mbggenerated
     */
    private Integer confirmStatus;

    /**
     * 字段: es_bet_order.win_lose_state<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 输赢状态
     *
     * @mbggenerated
     */
    private Integer winLoseState;

    /**
     * 字段: es_bet_order.settlement_status<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 结算状态
     *
     * @mbggenerated
     */
    private Integer settlementStatus;

    /**
     * 字段: es_bet_order.settlement_amount<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 结算金额
     *
     * @mbggenerated
     */
    private String settlementAmount;

    /**
     * 字段: es_bet_order.settlement_ratio<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 结算比例
     *
     * @mbggenerated
     */
    private String settlementRatio;

    /**
     * 字段: es_bet_order.settlement_time<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 结算时间
     *
     * @mbggenerated
     */
    private Date settlementTime;

    /**
     * 字段: es_bet_order.is_change<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1<br/>
     * 说明: 赛果是否变更
     *
     * @mbggenerated
     */
    private Boolean isChange;

    /**
     * 字段: es_bet_order.is_handle<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 打码量：0未处理，1已处理
     *
     * @mbggenerated
     */
    private Integer isHandle;

    /**
     * 字段: es_bet_order.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 字段: es_bet_order.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 字段: es_bet_order.user_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 用户ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return es_bet_order.id: 
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 字段: es_bet_order.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return es_bet_order.es_order_id: 电竞注单ID
     *
     * @mbggenerated
     */
    public String getEsOrderId() {
        return esOrderId;
    }

    /**
     * 字段: es_bet_order.es_order_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 电竞注单ID
     *
     * @mbggenerated
     */
    public void setEsOrderId(String esOrderId) {
        this.esOrderId = esOrderId;
    }

    /**
     * @return es_bet_order.es_user_id: 电竞账号ID
     *
     * @mbggenerated
     */
    public Integer getEsUserId() {
        return esUserId;
    }

    /**
     * 字段: es_bet_order.es_user_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 电竞账号ID
     *
     * @mbggenerated
     */
    public void setEsUserId(Integer esUserId) {
        this.esUserId = esUserId;
    }

    /**
     * @return es_bet_order.username: 用户名
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * 字段: es_bet_order.username<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 50<br/>
     * 说明: 用户名
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * @return es_bet_order.total_amount: 总金额
     *
     * @mbggenerated
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * 字段: es_bet_order.total_amount<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 12<br/>
     * 说明: 总金额
     *
     * @mbggenerated
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * @return es_bet_order.odds_value: 赔率
     *
     * @mbggenerated
     */
    public BigDecimal getOddsValue() {
        return oddsValue;
    }

    /**
     * 字段: es_bet_order.odds_value<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 12<br/>
     * 说明: 赔率
     *
     * @mbggenerated
     */
    public void setOddsValue(BigDecimal oddsValue) {
        this.oddsValue = oddsValue;
    }

    /**
     * @return es_bet_order.can_win_amount: 可赢金额
     *
     * @mbggenerated
     */
    public BigDecimal getCanWinAmount() {
        return canWinAmount;
    }

    /**
     * 字段: es_bet_order.can_win_amount<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 12<br/>
     * 说明: 可赢金额
     *
     * @mbggenerated
     */
    public void setCanWinAmount(BigDecimal canWinAmount) {
        this.canWinAmount = canWinAmount;
    }

    /**
     * @return es_bet_order.confirm_status: 结算状态
     *
     * @mbggenerated
     */
    public Integer getConfirmStatus() {
        return confirmStatus;
    }

    /**
     * 字段: es_bet_order.confirm_status<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 结算状态
     *
     * @mbggenerated
     */
    public void setConfirmStatus(Integer confirmStatus) {
        this.confirmStatus = confirmStatus;
    }

    /**
     * @return es_bet_order.win_lose_state: 输赢状态
     *
     * @mbggenerated
     */
    public Integer getWinLoseState() {
        return winLoseState;
    }

    /**
     * 字段: es_bet_order.win_lose_state<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 输赢状态
     *
     * @mbggenerated
     */
    public void setWinLoseState(Integer winLoseState) {
        this.winLoseState = winLoseState;
    }

    /**
     * @return es_bet_order.settlement_status: 结算状态
     *
     * @mbggenerated
     */
    public Integer getSettlementStatus() {
        return settlementStatus;
    }

    /**
     * 字段: es_bet_order.settlement_status<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 结算状态
     *
     * @mbggenerated
     */
    public void setSettlementStatus(Integer settlementStatus) {
        this.settlementStatus = settlementStatus;
    }

    /**
     * @return es_bet_order.settlement_amount: 结算金额
     *
     * @mbggenerated
     */
    public String getSettlementAmount() {
        return settlementAmount;
    }

    /**
     * 字段: es_bet_order.settlement_amount<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 结算金额
     *
     * @mbggenerated
     */
    public void setSettlementAmount(String settlementAmount) {
        this.settlementAmount = settlementAmount;
    }

    /**
     * @return es_bet_order.settlement_ratio: 结算比例
     *
     * @mbggenerated
     */
    public String getSettlementRatio() {
        return settlementRatio;
    }

    /**
     * 字段: es_bet_order.settlement_ratio<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 结算比例
     *
     * @mbggenerated
     */
    public void setSettlementRatio(String settlementRatio) {
        this.settlementRatio = settlementRatio;
    }

    /**
     * @return es_bet_order.settlement_time: 结算时间
     *
     * @mbggenerated
     */
    public Date getSettlementTime() {
        return settlementTime;
    }

    /**
     * 字段: es_bet_order.settlement_time<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 结算时间
     *
     * @mbggenerated
     */
    public void setSettlementTime(Date settlementTime) {
        this.settlementTime = settlementTime;
    }

    /**
     * @return es_bet_order.is_change: 赛果是否变更
     *
     * @mbggenerated
     */
    public Boolean getIsChange() {
        return isChange;
    }

    /**
     * 字段: es_bet_order.is_change<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1<br/>
     * 说明: 赛果是否变更
     *
     * @mbggenerated
     */
    public void setIsChange(Boolean isChange) {
        this.isChange = isChange;
    }

    /**
     * @return es_bet_order.is_handle: 打码量：0未处理，1已处理
     *
     * @mbggenerated
     */
    public Integer getIsHandle() {
        return isHandle;
    }

    /**
     * 字段: es_bet_order.is_handle<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 打码量：0未处理，1已处理
     *
     * @mbggenerated
     */
    public void setIsHandle(Integer isHandle) {
        this.isHandle = isHandle;
    }

    /**
     * @return es_bet_order.create_time: 创建时间
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 字段: es_bet_order.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return es_bet_order.update_time: 修改时间
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 字段: es_bet_order.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 修改时间
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * @return es_bet_order.user_id: 用户ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 字段: es_bet_order.user_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 用户ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EsBetOrder other = (EsBetOrder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEsOrderId() == null ? other.getEsOrderId() == null : this.getEsOrderId().equals(other.getEsOrderId()))
            && (this.getEsUserId() == null ? other.getEsUserId() == null : this.getEsUserId().equals(other.getEsUserId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getTotalAmount() == null ? other.getTotalAmount() == null : this.getTotalAmount().equals(other.getTotalAmount()))
            && (this.getOddsValue() == null ? other.getOddsValue() == null : this.getOddsValue().equals(other.getOddsValue()))
            && (this.getCanWinAmount() == null ? other.getCanWinAmount() == null : this.getCanWinAmount().equals(other.getCanWinAmount()))
            && (this.getConfirmStatus() == null ? other.getConfirmStatus() == null : this.getConfirmStatus().equals(other.getConfirmStatus()))
            && (this.getWinLoseState() == null ? other.getWinLoseState() == null : this.getWinLoseState().equals(other.getWinLoseState()))
            && (this.getSettlementStatus() == null ? other.getSettlementStatus() == null : this.getSettlementStatus().equals(other.getSettlementStatus()))
            && (this.getSettlementAmount() == null ? other.getSettlementAmount() == null : this.getSettlementAmount().equals(other.getSettlementAmount()))
            && (this.getSettlementRatio() == null ? other.getSettlementRatio() == null : this.getSettlementRatio().equals(other.getSettlementRatio()))
            && (this.getSettlementTime() == null ? other.getSettlementTime() == null : this.getSettlementTime().equals(other.getSettlementTime()))
            && (this.getIsChange() == null ? other.getIsChange() == null : this.getIsChange().equals(other.getIsChange()))
            && (this.getIsHandle() == null ? other.getIsHandle() == null : this.getIsHandle().equals(other.getIsHandle()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEsOrderId() == null) ? 0 : getEsOrderId().hashCode());
        result = prime * result + ((getEsUserId() == null) ? 0 : getEsUserId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getTotalAmount() == null) ? 0 : getTotalAmount().hashCode());
        result = prime * result + ((getOddsValue() == null) ? 0 : getOddsValue().hashCode());
        result = prime * result + ((getCanWinAmount() == null) ? 0 : getCanWinAmount().hashCode());
        result = prime * result + ((getConfirmStatus() == null) ? 0 : getConfirmStatus().hashCode());
        result = prime * result + ((getWinLoseState() == null) ? 0 : getWinLoseState().hashCode());
        result = prime * result + ((getSettlementStatus() == null) ? 0 : getSettlementStatus().hashCode());
        result = prime * result + ((getSettlementAmount() == null) ? 0 : getSettlementAmount().hashCode());
        result = prime * result + ((getSettlementRatio() == null) ? 0 : getSettlementRatio().hashCode());
        result = prime * result + ((getSettlementTime() == null) ? 0 : getSettlementTime().hashCode());
        result = prime * result + ((getIsChange() == null) ? 0 : getIsChange().hashCode());
        result = prime * result + ((getIsHandle() == null) ? 0 : getIsHandle().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", esOrderId=").append(esOrderId);
        sb.append(", esUserId=").append(esUserId);
        sb.append(", username=").append(username);
        sb.append(", totalAmount=").append(totalAmount);
        sb.append(", oddsValue=").append(oddsValue);
        sb.append(", canWinAmount=").append(canWinAmount);
        sb.append(", confirmStatus=").append(confirmStatus);
        sb.append(", winLoseState=").append(winLoseState);
        sb.append(", settlementStatus=").append(settlementStatus);
        sb.append(", settlementAmount=").append(settlementAmount);
        sb.append(", settlementRatio=").append(settlementRatio);
        sb.append(", settlementTime=").append(settlementTime);
        sb.append(", isChange=").append(isChange);
        sb.append(", isHandle=").append(isHandle);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", userId=").append(userId);
        sb.append("]");
        return sb.toString();
    }
}