package com.likes.common.mybatis.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class GodPlan implements Serializable {
    /**
     * 字段: god_plan.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 字段: god_plan.god_id<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 大神Id
     *
     * @mbggenerated
     */
    private Integer godId;

    /**
     * 字段: god_plan.head<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 头像
     *
     * @mbggenerated
     */
    private String head;

    /**
     * 字段: god_plan.god_nick_name<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 大神昵称
     *
     * @mbggenerated
     */
    private String godNickName;

    /**
     * 字段: god_plan.lottery_id<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 彩种Id
     *
     * @mbggenerated
     */
    private Integer lotteryId;

    /**
     * 字段: god_plan.play_tag_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 玩法id
     *
     * @mbggenerated
     */
    private Integer playTagId;

    /**
     * 字段: god_plan.plan_type<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 计划类型(1,2,3)
     *
     * @mbggenerated
     */
    private Integer planType;

    /**
     * 字段: god_plan.status<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 255<br/>
     * 说明: 状态(0关闭，1开启)
     *
     * @mbggenerated
     */
    private String status;

    /**
     * 字段: god_plan.reward_amount<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 20<br/>
     * 说明: 大神打赏总金额
     *
     * @mbggenerated
     */
    private BigDecimal rewardAmount;

    /**
     * 字段: god_plan.win_count<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 中奖数
     *
     * @mbggenerated
     */
    private Integer winCount;

    /**
     * 字段: god_plan.probability<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 255<br/>
     * 说明: 总中奖率
     *
     * @mbggenerated
     */
    private String probability;

    /**
     * 字段: god_plan.total_issue_count<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 总推单期数
     *
     * @mbggenerated
     */
    private Integer totalIssueCount;

    /**
     * 字段: god_plan.order_num<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 排序
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * 字段: god_plan.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 字段: god_plan.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 字段: god_plan.play_show_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 显示名称
     *
     * @mbggenerated
     */
    private String playShowName;

    /**
     * 字段: god_plan.play_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 玩法名称
     *
     * @mbggenerated
     */
    private String playName;

    /**
     * 字段: god_plan.plan_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 计划Id
     *
     * @mbggenerated
     */
    private Long planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table god_plan
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return god_plan.id: id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 字段: god_plan.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return god_plan.god_id: 大神Id
     *
     * @mbggenerated
     */
    public Integer getGodId() {
        return godId;
    }

    /**
     * 字段: god_plan.god_id<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 大神Id
     *
     * @mbggenerated
     */
    public void setGodId(Integer godId) {
        this.godId = godId;
    }

    /**
     * @return god_plan.head: 头像
     *
     * @mbggenerated
     */
    public String getHead() {
        return head;
    }

    /**
     * 字段: god_plan.head<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 头像
     *
     * @mbggenerated
     */
    public void setHead(String head) {
        this.head = head;
    }

    /**
     * @return god_plan.god_nick_name: 大神昵称
     *
     * @mbggenerated
     */
    public String getGodNickName() {
        return godNickName;
    }

    /**
     * 字段: god_plan.god_nick_name<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 大神昵称
     *
     * @mbggenerated
     */
    public void setGodNickName(String godNickName) {
        this.godNickName = godNickName;
    }

    /**
     * @return god_plan.lottery_id: 彩种Id
     *
     * @mbggenerated
     */
    public Integer getLotteryId() {
        return lotteryId;
    }

    /**
     * 字段: god_plan.lottery_id<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 彩种Id
     *
     * @mbggenerated
     */
    public void setLotteryId(Integer lotteryId) {
        this.lotteryId = lotteryId;
    }

    /**
     * @return god_plan.play_tag_id: 玩法id
     *
     * @mbggenerated
     */
    public Integer getPlayTagId() {
        return playTagId;
    }

    /**
     * 字段: god_plan.play_tag_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 玩法id
     *
     * @mbggenerated
     */
    public void setPlayTagId(Integer playTagId) {
        this.playTagId = playTagId;
    }

    /**
     * @return god_plan.plan_type: 计划类型(1,2,3)
     *
     * @mbggenerated
     */
    public Integer getPlanType() {
        return planType;
    }

    /**
     * 字段: god_plan.plan_type<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 计划类型(1,2,3)
     *
     * @mbggenerated
     */
    public void setPlanType(Integer planType) {
        this.planType = planType;
    }

    /**
     * @return god_plan.status: 状态(0关闭，1开启)
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * 字段: god_plan.status<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 255<br/>
     * 说明: 状态(0关闭，1开启)
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * @return god_plan.reward_amount: 大神打赏总金额
     *
     * @mbggenerated
     */
    public BigDecimal getRewardAmount() {
        return rewardAmount;
    }

    /**
     * 字段: god_plan.reward_amount<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 20<br/>
     * 说明: 大神打赏总金额
     *
     * @mbggenerated
     */
    public void setRewardAmount(BigDecimal rewardAmount) {
        this.rewardAmount = rewardAmount;
    }

    /**
     * @return god_plan.win_count: 中奖数
     *
     * @mbggenerated
     */
    public Integer getWinCount() {
        return winCount;
    }

    /**
     * 字段: god_plan.win_count<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 中奖数
     *
     * @mbggenerated
     */
    public void setWinCount(Integer winCount) {
        this.winCount = winCount;
    }

    /**
     * @return god_plan.probability: 总中奖率
     *
     * @mbggenerated
     */
    public String getProbability() {
        return probability;
    }

    /**
     * 字段: god_plan.probability<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 255<br/>
     * 说明: 总中奖率
     *
     * @mbggenerated
     */
    public void setProbability(String probability) {
        this.probability = probability;
    }

    /**
     * @return god_plan.total_issue_count: 总推单期数
     *
     * @mbggenerated
     */
    public Integer getTotalIssueCount() {
        return totalIssueCount;
    }

    /**
     * 字段: god_plan.total_issue_count<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 总推单期数
     *
     * @mbggenerated
     */
    public void setTotalIssueCount(Integer totalIssueCount) {
        this.totalIssueCount = totalIssueCount;
    }

    /**
     * @return god_plan.order_num: 排序
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * 字段: god_plan.order_num<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 排序
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * @return god_plan.create_time: 创建时间
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 字段: god_plan.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return god_plan.update_time: 更新时间
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 字段: god_plan.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * @return god_plan.play_show_name: 显示名称
     *
     * @mbggenerated
     */
    public String getPlayShowName() {
        return playShowName;
    }

    /**
     * 字段: god_plan.play_show_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 显示名称
     *
     * @mbggenerated
     */
    public void setPlayShowName(String playShowName) {
        this.playShowName = playShowName;
    }

    /**
     * @return god_plan.play_name: 玩法名称
     *
     * @mbggenerated
     */
    public String getPlayName() {
        return playName;
    }

    /**
     * 字段: god_plan.play_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 玩法名称
     *
     * @mbggenerated
     */
    public void setPlayName(String playName) {
        this.playName = playName;
    }

    /**
     * @return god_plan.plan_id: 计划Id
     *
     * @mbggenerated
     */
    public Long getPlanId() {
        return planId;
    }

    /**
     * 字段: god_plan.plan_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 计划Id
     *
     * @mbggenerated
     */
    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table god_plan
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GodPlan other = (GodPlan) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGodId() == null ? other.getGodId() == null : this.getGodId().equals(other.getGodId()))
            && (this.getHead() == null ? other.getHead() == null : this.getHead().equals(other.getHead()))
            && (this.getGodNickName() == null ? other.getGodNickName() == null : this.getGodNickName().equals(other.getGodNickName()))
            && (this.getLotteryId() == null ? other.getLotteryId() == null : this.getLotteryId().equals(other.getLotteryId()))
            && (this.getPlayTagId() == null ? other.getPlayTagId() == null : this.getPlayTagId().equals(other.getPlayTagId()))
            && (this.getPlanType() == null ? other.getPlanType() == null : this.getPlanType().equals(other.getPlanType()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getRewardAmount() == null ? other.getRewardAmount() == null : this.getRewardAmount().equals(other.getRewardAmount()))
            && (this.getWinCount() == null ? other.getWinCount() == null : this.getWinCount().equals(other.getWinCount()))
            && (this.getProbability() == null ? other.getProbability() == null : this.getProbability().equals(other.getProbability()))
            && (this.getTotalIssueCount() == null ? other.getTotalIssueCount() == null : this.getTotalIssueCount().equals(other.getTotalIssueCount()))
            && (this.getOrderNum() == null ? other.getOrderNum() == null : this.getOrderNum().equals(other.getOrderNum()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getPlayShowName() == null ? other.getPlayShowName() == null : this.getPlayShowName().equals(other.getPlayShowName()))
            && (this.getPlayName() == null ? other.getPlayName() == null : this.getPlayName().equals(other.getPlayName()))
            && (this.getPlanId() == null ? other.getPlanId() == null : this.getPlanId().equals(other.getPlanId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table god_plan
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGodId() == null) ? 0 : getGodId().hashCode());
        result = prime * result + ((getHead() == null) ? 0 : getHead().hashCode());
        result = prime * result + ((getGodNickName() == null) ? 0 : getGodNickName().hashCode());
        result = prime * result + ((getLotteryId() == null) ? 0 : getLotteryId().hashCode());
        result = prime * result + ((getPlayTagId() == null) ? 0 : getPlayTagId().hashCode());
        result = prime * result + ((getPlanType() == null) ? 0 : getPlanType().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRewardAmount() == null) ? 0 : getRewardAmount().hashCode());
        result = prime * result + ((getWinCount() == null) ? 0 : getWinCount().hashCode());
        result = prime * result + ((getProbability() == null) ? 0 : getProbability().hashCode());
        result = prime * result + ((getTotalIssueCount() == null) ? 0 : getTotalIssueCount().hashCode());
        result = prime * result + ((getOrderNum() == null) ? 0 : getOrderNum().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getPlayShowName() == null) ? 0 : getPlayShowName().hashCode());
        result = prime * result + ((getPlayName() == null) ? 0 : getPlayName().hashCode());
        result = prime * result + ((getPlanId() == null) ? 0 : getPlanId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table god_plan
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", godId=").append(godId);
        sb.append(", head=").append(head);
        sb.append(", godNickName=").append(godNickName);
        sb.append(", lotteryId=").append(lotteryId);
        sb.append(", playTagId=").append(playTagId);
        sb.append(", planType=").append(planType);
        sb.append(", status=").append(status);
        sb.append(", rewardAmount=").append(rewardAmount);
        sb.append(", winCount=").append(winCount);
        sb.append(", probability=").append(probability);
        sb.append(", totalIssueCount=").append(totalIssueCount);
        sb.append(", orderNum=").append(orderNum);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", playShowName=").append(playShowName);
        sb.append(", playName=").append(playName);
        sb.append(", planId=").append(planId);
        sb.append("]");
        return sb.toString();
    }
}