package com.likes.common.mybatis.entity;

import java.io.Serializable;

public class GodPlanSeriesPlay implements Serializable {
    /**
     * 字段: god_plan_series_play.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 彩种系列Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 字段: god_plan_series_play.name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 系列名称
     *
     * @mbggenerated
     */
    private String name;

    /**
     * 字段: god_plan_series_play.lottery_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 彩种Id
     *
     * @mbggenerated
     */
    private Integer lotteryId;

    /**
     * 字段: god_plan_series_play.show_play_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 显示玩法名称
     *
     * @mbggenerated
     */
    private String showPlayName;

    /**
     * 字段: god_plan_series_play.play_values<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 玩法值集合（逗号分隔）
     *
     * @mbggenerated
     */
    private String playValues;

    /**
     * 字段: god_plan_series_play.value_count<br/>
     * 必填: true<br/>
     * 缺省: 1<br/>
     * 长度: 10<br/>
     * 说明: 值个数
     *
     * @mbggenerated
     */
    private Integer valueCount;

    /**
     * 字段: god_plan_series_play.play_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 玩法名称
     *
     * @mbggenerated
     */
    private String playName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table god_plan_series_play
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return god_plan_series_play.id: 彩种系列Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 字段: god_plan_series_play.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 彩种系列Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return god_plan_series_play.name: 系列名称
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * 字段: god_plan_series_play.name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 系列名称
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return god_plan_series_play.lottery_id: 彩种Id
     *
     * @mbggenerated
     */
    public Integer getLotteryId() {
        return lotteryId;
    }

    /**
     * 字段: god_plan_series_play.lottery_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 彩种Id
     *
     * @mbggenerated
     */
    public void setLotteryId(Integer lotteryId) {
        this.lotteryId = lotteryId;
    }

    /**
     * @return god_plan_series_play.show_play_name: 显示玩法名称
     *
     * @mbggenerated
     */
    public String getShowPlayName() {
        return showPlayName;
    }

    /**
     * 字段: god_plan_series_play.show_play_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 显示玩法名称
     *
     * @mbggenerated
     */
    public void setShowPlayName(String showPlayName) {
        this.showPlayName = showPlayName;
    }

    /**
     * @return god_plan_series_play.play_values: 玩法值集合（逗号分隔）
     *
     * @mbggenerated
     */
    public String getPlayValues() {
        return playValues;
    }

    /**
     * 字段: god_plan_series_play.play_values<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 玩法值集合（逗号分隔）
     *
     * @mbggenerated
     */
    public void setPlayValues(String playValues) {
        this.playValues = playValues;
    }

    /**
     * @return god_plan_series_play.value_count: 值个数
     *
     * @mbggenerated
     */
    public Integer getValueCount() {
        return valueCount;
    }

    /**
     * 字段: god_plan_series_play.value_count<br/>
     * 必填: true<br/>
     * 缺省: 1<br/>
     * 长度: 10<br/>
     * 说明: 值个数
     *
     * @mbggenerated
     */
    public void setValueCount(Integer valueCount) {
        this.valueCount = valueCount;
    }

    /**
     * @return god_plan_series_play.play_name: 玩法名称
     *
     * @mbggenerated
     */
    public String getPlayName() {
        return playName;
    }

    /**
     * 字段: god_plan_series_play.play_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 玩法名称
     *
     * @mbggenerated
     */
    public void setPlayName(String playName) {
        this.playName = playName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table god_plan_series_play
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GodPlanSeriesPlay other = (GodPlanSeriesPlay) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getLotteryId() == null ? other.getLotteryId() == null : this.getLotteryId().equals(other.getLotteryId()))
            && (this.getShowPlayName() == null ? other.getShowPlayName() == null : this.getShowPlayName().equals(other.getShowPlayName()))
            && (this.getPlayValues() == null ? other.getPlayValues() == null : this.getPlayValues().equals(other.getPlayValues()))
            && (this.getValueCount() == null ? other.getValueCount() == null : this.getValueCount().equals(other.getValueCount()))
            && (this.getPlayName() == null ? other.getPlayName() == null : this.getPlayName().equals(other.getPlayName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table god_plan_series_play
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getLotteryId() == null) ? 0 : getLotteryId().hashCode());
        result = prime * result + ((getShowPlayName() == null) ? 0 : getShowPlayName().hashCode());
        result = prime * result + ((getPlayValues() == null) ? 0 : getPlayValues().hashCode());
        result = prime * result + ((getValueCount() == null) ? 0 : getValueCount().hashCode());
        result = prime * result + ((getPlayName() == null) ? 0 : getPlayName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table god_plan_series_play
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", lotteryId=").append(lotteryId);
        sb.append(", showPlayName=").append(showPlayName);
        sb.append(", playValues=").append(playValues);
        sb.append(", valueCount=").append(valueCount);
        sb.append(", playName=").append(playName);
        sb.append("]");
        return sb.toString();
    }
}