package com.likes.common.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class InfPush implements Serializable {
    /**
     * 字段: inf_push.bdpushid<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 推送id
     *
     * @mbggenerated
     */
    private Long bdpushid;

    /**
     * 字段: inf_push.pushtype<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 推送类型
     *
     * @mbggenerated
     */
    private String pushtype;

    /**
     * 字段: inf_push.pushtitle<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 推送标题
     *
     * @mbggenerated
     */
    private String pushtitle;

    /**
     * 字段: inf_push.pushbody<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 推送摘要
     *
     * @mbggenerated
     */
    private String pushbody;

    /**
     * 字段: inf_push.pushdate<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 推送时间
     *
     * @mbggenerated
     */
    private Date pushdate;

    /**
     * 字段: inf_push.sortby<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 排序权重
     *
     * @mbggenerated
     */
    private Integer sortby;

    /**
     * 字段: inf_push.is_delete<br/>
     * 必填: true<br/>
     * 缺省: b'0'<br/>
     * 长度: 1<br/>
     * 说明: 是否删除
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * 字段: inf_push.create_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 创建人
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * 字段: inf_push.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 字段: inf_push.update_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 最后修改人
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * 字段: inf_push.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inf_push
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return inf_push.bdpushid: 推送id
     *
     * @mbggenerated
     */
    public Long getBdpushid() {
        return bdpushid;
    }

    /**
     * 字段: inf_push.bdpushid<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 推送id
     *
     * @mbggenerated
     */
    public void setBdpushid(Long bdpushid) {
        this.bdpushid = bdpushid;
    }

    /**
     * @return inf_push.pushtype: 推送类型
     *
     * @mbggenerated
     */
    public String getPushtype() {
        return pushtype;
    }

    /**
     * 字段: inf_push.pushtype<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 推送类型
     *
     * @mbggenerated
     */
    public void setPushtype(String pushtype) {
        this.pushtype = pushtype;
    }

    /**
     * @return inf_push.pushtitle: 推送标题
     *
     * @mbggenerated
     */
    public String getPushtitle() {
        return pushtitle;
    }

    /**
     * 字段: inf_push.pushtitle<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 推送标题
     *
     * @mbggenerated
     */
    public void setPushtitle(String pushtitle) {
        this.pushtitle = pushtitle;
    }

    /**
     * @return inf_push.pushbody: 推送摘要
     *
     * @mbggenerated
     */
    public String getPushbody() {
        return pushbody;
    }

    /**
     * 字段: inf_push.pushbody<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 推送摘要
     *
     * @mbggenerated
     */
    public void setPushbody(String pushbody) {
        this.pushbody = pushbody;
    }

    /**
     * @return inf_push.pushdate: 推送时间
     *
     * @mbggenerated
     */
    public Date getPushdate() {
        return pushdate;
    }

    /**
     * 字段: inf_push.pushdate<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 推送时间
     *
     * @mbggenerated
     */
    public void setPushdate(Date pushdate) {
        this.pushdate = pushdate;
    }

    /**
     * @return inf_push.sortby: 排序权重
     *
     * @mbggenerated
     */
    public Integer getSortby() {
        return sortby;
    }

    /**
     * 字段: inf_push.sortby<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 排序权重
     *
     * @mbggenerated
     */
    public void setSortby(Integer sortby) {
        this.sortby = sortby;
    }

    /**
     * @return inf_push.is_delete: 是否删除
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * 字段: inf_push.is_delete<br/>
     * 必填: true<br/>
     * 缺省: b'0'<br/>
     * 长度: 1<br/>
     * 说明: 是否删除
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * @return inf_push.create_user: 创建人
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * 字段: inf_push.create_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 创建人
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * @return inf_push.create_time: 创建时间
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 字段: inf_push.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return inf_push.update_user: 最后修改人
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * 字段: inf_push.update_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 最后修改人
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * @return inf_push.update_time: 更新时间
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 字段: inf_push.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_push
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InfPush other = (InfPush) that;
        return (this.getBdpushid() == null ? other.getBdpushid() == null : this.getBdpushid().equals(other.getBdpushid()))
            && (this.getPushtype() == null ? other.getPushtype() == null : this.getPushtype().equals(other.getPushtype()))
            && (this.getPushtitle() == null ? other.getPushtitle() == null : this.getPushtitle().equals(other.getPushtitle()))
            && (this.getPushbody() == null ? other.getPushbody() == null : this.getPushbody().equals(other.getPushbody()))
            && (this.getPushdate() == null ? other.getPushdate() == null : this.getPushdate().equals(other.getPushdate()))
            && (this.getSortby() == null ? other.getSortby() == null : this.getSortby().equals(other.getSortby()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_push
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBdpushid() == null) ? 0 : getBdpushid().hashCode());
        result = prime * result + ((getPushtype() == null) ? 0 : getPushtype().hashCode());
        result = prime * result + ((getPushtitle() == null) ? 0 : getPushtitle().hashCode());
        result = prime * result + ((getPushbody() == null) ? 0 : getPushbody().hashCode());
        result = prime * result + ((getPushdate() == null) ? 0 : getPushdate().hashCode());
        result = prime * result + ((getSortby() == null) ? 0 : getSortby().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_push
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bdpushid=").append(bdpushid);
        sb.append(", pushtype=").append(pushtype);
        sb.append(", pushtitle=").append(pushtitle);
        sb.append(", pushbody=").append(pushbody);
        sb.append(", pushdate=").append(pushdate);
        sb.append(", sortby=").append(sortby);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}