package com.likes.common.mybatis.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InfSysremindinfoExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    protected Integer limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public InfSysremindinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        offset = null;
        limit = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public Integer getLimit() {
        return this.limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public InfSysremindinfoExample bound(Integer offset, Integer limit) {
        this.offset = offset;
        this.limit = limit;
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRmdidIsNull() {
            addCriterion("rmdid is null");
            return (Criteria) this;
        }

        public Criteria andRmdidIsNotNull() {
            addCriterion("rmdid is not null");
            return (Criteria) this;
        }

        public Criteria andRmdidEqualTo(Long value) {
            addCriterion("rmdid =", value, "rmdid");
            return (Criteria) this;
        }

        public Criteria andRmdidNotEqualTo(Long value) {
            addCriterion("rmdid <>", value, "rmdid");
            return (Criteria) this;
        }

        public Criteria andRmdidGreaterThan(Long value) {
            addCriterion("rmdid >", value, "rmdid");
            return (Criteria) this;
        }

        public Criteria andRmdidGreaterThanOrEqualTo(Long value) {
            addCriterion("rmdid >=", value, "rmdid");
            return (Criteria) this;
        }

        public Criteria andRmdidLessThan(Long value) {
            addCriterion("rmdid <", value, "rmdid");
            return (Criteria) this;
        }

        public Criteria andRmdidLessThanOrEqualTo(Long value) {
            addCriterion("rmdid <=", value, "rmdid");
            return (Criteria) this;
        }

        public Criteria andRmdidIn(List<Long> values) {
            addCriterion("rmdid in", values, "rmdid");
            return (Criteria) this;
        }

        public Criteria andRmdidNotIn(List<Long> values) {
            addCriterion("rmdid not in", values, "rmdid");
            return (Criteria) this;
        }

        public Criteria andRmdidBetween(Long value1, Long value2) {
            addCriterion("rmdid between", value1, value2, "rmdid");
            return (Criteria) this;
        }

        public Criteria andRmdidNotBetween(Long value1, Long value2) {
            addCriterion("rmdid not between", value1, value2, "rmdid");
            return (Criteria) this;
        }

        public Criteria andBdpushidIsNull() {
            addCriterion("bdpushid is null");
            return (Criteria) this;
        }

        public Criteria andBdpushidIsNotNull() {
            addCriterion("bdpushid is not null");
            return (Criteria) this;
        }

        public Criteria andBdpushidEqualTo(Long value) {
            addCriterion("bdpushid =", value, "bdpushid");
            return (Criteria) this;
        }

        public Criteria andBdpushidNotEqualTo(Long value) {
            addCriterion("bdpushid <>", value, "bdpushid");
            return (Criteria) this;
        }

        public Criteria andBdpushidGreaterThan(Long value) {
            addCriterion("bdpushid >", value, "bdpushid");
            return (Criteria) this;
        }

        public Criteria andBdpushidGreaterThanOrEqualTo(Long value) {
            addCriterion("bdpushid >=", value, "bdpushid");
            return (Criteria) this;
        }

        public Criteria andBdpushidLessThan(Long value) {
            addCriterion("bdpushid <", value, "bdpushid");
            return (Criteria) this;
        }

        public Criteria andBdpushidLessThanOrEqualTo(Long value) {
            addCriterion("bdpushid <=", value, "bdpushid");
            return (Criteria) this;
        }

        public Criteria andBdpushidIn(List<Long> values) {
            addCriterion("bdpushid in", values, "bdpushid");
            return (Criteria) this;
        }

        public Criteria andBdpushidNotIn(List<Long> values) {
            addCriterion("bdpushid not in", values, "bdpushid");
            return (Criteria) this;
        }

        public Criteria andBdpushidBetween(Long value1, Long value2) {
            addCriterion("bdpushid between", value1, value2, "bdpushid");
            return (Criteria) this;
        }

        public Criteria andBdpushidNotBetween(Long value1, Long value2) {
            addCriterion("bdpushid not between", value1, value2, "bdpushid");
            return (Criteria) this;
        }

        public Criteria andSenderIsNull() {
            addCriterion("sender is null");
            return (Criteria) this;
        }

        public Criteria andSenderIsNotNull() {
            addCriterion("sender is not null");
            return (Criteria) this;
        }

        public Criteria andSenderEqualTo(String value) {
            addCriterion("sender =", value, "sender");
            return (Criteria) this;
        }

        public Criteria andSenderNotEqualTo(String value) {
            addCriterion("sender <>", value, "sender");
            return (Criteria) this;
        }

        public Criteria andSenderGreaterThan(String value) {
            addCriterion("sender >", value, "sender");
            return (Criteria) this;
        }

        public Criteria andSenderGreaterThanOrEqualTo(String value) {
            addCriterion("sender >=", value, "sender");
            return (Criteria) this;
        }

        public Criteria andSenderLessThan(String value) {
            addCriterion("sender <", value, "sender");
            return (Criteria) this;
        }

        public Criteria andSenderLessThanOrEqualTo(String value) {
            addCriterion("sender <=", value, "sender");
            return (Criteria) this;
        }

        public Criteria andSenderLike(String value) {
            addCriterion("sender like", value, "sender");
            return (Criteria) this;
        }

        public Criteria andSenderNotLike(String value) {
            addCriterion("sender not like", value, "sender");
            return (Criteria) this;
        }

        public Criteria andSenderIn(List<String> values) {
            addCriterion("sender in", values, "sender");
            return (Criteria) this;
        }

        public Criteria andSenderNotIn(List<String> values) {
            addCriterion("sender not in", values, "sender");
            return (Criteria) this;
        }

        public Criteria andSenderBetween(String value1, String value2) {
            addCriterion("sender between", value1, value2, "sender");
            return (Criteria) this;
        }

        public Criteria andSenderNotBetween(String value1, String value2) {
            addCriterion("sender not between", value1, value2, "sender");
            return (Criteria) this;
        }

        public Criteria andRmtypeIsNull() {
            addCriterion("rmtype is null");
            return (Criteria) this;
        }

        public Criteria andRmtypeIsNotNull() {
            addCriterion("rmtype is not null");
            return (Criteria) this;
        }

        public Criteria andRmtypeEqualTo(String value) {
            addCriterion("rmtype =", value, "rmtype");
            return (Criteria) this;
        }

        public Criteria andRmtypeNotEqualTo(String value) {
            addCriterion("rmtype <>", value, "rmtype");
            return (Criteria) this;
        }

        public Criteria andRmtypeGreaterThan(String value) {
            addCriterion("rmtype >", value, "rmtype");
            return (Criteria) this;
        }

        public Criteria andRmtypeGreaterThanOrEqualTo(String value) {
            addCriterion("rmtype >=", value, "rmtype");
            return (Criteria) this;
        }

        public Criteria andRmtypeLessThan(String value) {
            addCriterion("rmtype <", value, "rmtype");
            return (Criteria) this;
        }

        public Criteria andRmtypeLessThanOrEqualTo(String value) {
            addCriterion("rmtype <=", value, "rmtype");
            return (Criteria) this;
        }

        public Criteria andRmtypeLike(String value) {
            addCriterion("rmtype like", value, "rmtype");
            return (Criteria) this;
        }

        public Criteria andRmtypeNotLike(String value) {
            addCriterion("rmtype not like", value, "rmtype");
            return (Criteria) this;
        }

        public Criteria andRmtypeIn(List<String> values) {
            addCriterion("rmtype in", values, "rmtype");
            return (Criteria) this;
        }

        public Criteria andRmtypeNotIn(List<String> values) {
            addCriterion("rmtype not in", values, "rmtype");
            return (Criteria) this;
        }

        public Criteria andRmtypeBetween(String value1, String value2) {
            addCriterion("rmtype between", value1, value2, "rmtype");
            return (Criteria) this;
        }

        public Criteria andRmtypeNotBetween(String value1, String value2) {
            addCriterion("rmtype not between", value1, value2, "rmtype");
            return (Criteria) this;
        }

        public Criteria andRecipienterIsNull() {
            addCriterion("recipienter is null");
            return (Criteria) this;
        }

        public Criteria andRecipienterIsNotNull() {
            addCriterion("recipienter is not null");
            return (Criteria) this;
        }

        public Criteria andRecipienterEqualTo(String value) {
            addCriterion("recipienter =", value, "recipienter");
            return (Criteria) this;
        }

        public Criteria andRecipienterNotEqualTo(String value) {
            addCriterion("recipienter <>", value, "recipienter");
            return (Criteria) this;
        }

        public Criteria andRecipienterGreaterThan(String value) {
            addCriterion("recipienter >", value, "recipienter");
            return (Criteria) this;
        }

        public Criteria andRecipienterGreaterThanOrEqualTo(String value) {
            addCriterion("recipienter >=", value, "recipienter");
            return (Criteria) this;
        }

        public Criteria andRecipienterLessThan(String value) {
            addCriterion("recipienter <", value, "recipienter");
            return (Criteria) this;
        }

        public Criteria andRecipienterLessThanOrEqualTo(String value) {
            addCriterion("recipienter <=", value, "recipienter");
            return (Criteria) this;
        }

        public Criteria andRecipienterLike(String value) {
            addCriterion("recipienter like", value, "recipienter");
            return (Criteria) this;
        }

        public Criteria andRecipienterNotLike(String value) {
            addCriterion("recipienter not like", value, "recipienter");
            return (Criteria) this;
        }

        public Criteria andRecipienterIn(List<String> values) {
            addCriterion("recipienter in", values, "recipienter");
            return (Criteria) this;
        }

        public Criteria andRecipienterNotIn(List<String> values) {
            addCriterion("recipienter not in", values, "recipienter");
            return (Criteria) this;
        }

        public Criteria andRecipienterBetween(String value1, String value2) {
            addCriterion("recipienter between", value1, value2, "recipienter");
            return (Criteria) this;
        }

        public Criteria andRecipienterNotBetween(String value1, String value2) {
            addCriterion("recipienter not between", value1, value2, "recipienter");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andRmpicsIsNull() {
            addCriterion("rmpics is null");
            return (Criteria) this;
        }

        public Criteria andRmpicsIsNotNull() {
            addCriterion("rmpics is not null");
            return (Criteria) this;
        }

        public Criteria andRmpicsEqualTo(String value) {
            addCriterion("rmpics =", value, "rmpics");
            return (Criteria) this;
        }

        public Criteria andRmpicsNotEqualTo(String value) {
            addCriterion("rmpics <>", value, "rmpics");
            return (Criteria) this;
        }

        public Criteria andRmpicsGreaterThan(String value) {
            addCriterion("rmpics >", value, "rmpics");
            return (Criteria) this;
        }

        public Criteria andRmpicsGreaterThanOrEqualTo(String value) {
            addCriterion("rmpics >=", value, "rmpics");
            return (Criteria) this;
        }

        public Criteria andRmpicsLessThan(String value) {
            addCriterion("rmpics <", value, "rmpics");
            return (Criteria) this;
        }

        public Criteria andRmpicsLessThanOrEqualTo(String value) {
            addCriterion("rmpics <=", value, "rmpics");
            return (Criteria) this;
        }

        public Criteria andRmpicsLike(String value) {
            addCriterion("rmpics like", value, "rmpics");
            return (Criteria) this;
        }

        public Criteria andRmpicsNotLike(String value) {
            addCriterion("rmpics not like", value, "rmpics");
            return (Criteria) this;
        }

        public Criteria andRmpicsIn(List<String> values) {
            addCriterion("rmpics in", values, "rmpics");
            return (Criteria) this;
        }

        public Criteria andRmpicsNotIn(List<String> values) {
            addCriterion("rmpics not in", values, "rmpics");
            return (Criteria) this;
        }

        public Criteria andRmpicsBetween(String value1, String value2) {
            addCriterion("rmpics between", value1, value2, "rmpics");
            return (Criteria) this;
        }

        public Criteria andRmpicsNotBetween(String value1, String value2) {
            addCriterion("rmpics not between", value1, value2, "rmpics");
            return (Criteria) this;
        }

        public Criteria andRmtitleIsNull() {
            addCriterion("rmtitle is null");
            return (Criteria) this;
        }

        public Criteria andRmtitleIsNotNull() {
            addCriterion("rmtitle is not null");
            return (Criteria) this;
        }

        public Criteria andRmtitleEqualTo(String value) {
            addCriterion("rmtitle =", value, "rmtitle");
            return (Criteria) this;
        }

        public Criteria andRmtitleNotEqualTo(String value) {
            addCriterion("rmtitle <>", value, "rmtitle");
            return (Criteria) this;
        }

        public Criteria andRmtitleGreaterThan(String value) {
            addCriterion("rmtitle >", value, "rmtitle");
            return (Criteria) this;
        }

        public Criteria andRmtitleGreaterThanOrEqualTo(String value) {
            addCriterion("rmtitle >=", value, "rmtitle");
            return (Criteria) this;
        }

        public Criteria andRmtitleLessThan(String value) {
            addCriterion("rmtitle <", value, "rmtitle");
            return (Criteria) this;
        }

        public Criteria andRmtitleLessThanOrEqualTo(String value) {
            addCriterion("rmtitle <=", value, "rmtitle");
            return (Criteria) this;
        }

        public Criteria andRmtitleLike(String value) {
            addCriterion("rmtitle like", value, "rmtitle");
            return (Criteria) this;
        }

        public Criteria andRmtitleNotLike(String value) {
            addCriterion("rmtitle not like", value, "rmtitle");
            return (Criteria) this;
        }

        public Criteria andRmtitleIn(List<String> values) {
            addCriterion("rmtitle in", values, "rmtitle");
            return (Criteria) this;
        }

        public Criteria andRmtitleNotIn(List<String> values) {
            addCriterion("rmtitle not in", values, "rmtitle");
            return (Criteria) this;
        }

        public Criteria andRmtitleBetween(String value1, String value2) {
            addCriterion("rmtitle between", value1, value2, "rmtitle");
            return (Criteria) this;
        }

        public Criteria andRmtitleNotBetween(String value1, String value2) {
            addCriterion("rmtitle not between", value1, value2, "rmtitle");
            return (Criteria) this;
        }

        public Criteria andSenddateIsNull() {
            addCriterion("senddate is null");
            return (Criteria) this;
        }

        public Criteria andSenddateIsNotNull() {
            addCriterion("senddate is not null");
            return (Criteria) this;
        }

        public Criteria andSenddateEqualTo(Date value) {
            addCriterion("senddate =", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateNotEqualTo(Date value) {
            addCriterion("senddate <>", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateGreaterThan(Date value) {
            addCriterion("senddate >", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateGreaterThanOrEqualTo(Date value) {
            addCriterion("senddate >=", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateLessThan(Date value) {
            addCriterion("senddate <", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateLessThanOrEqualTo(Date value) {
            addCriterion("senddate <=", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateIn(List<Date> values) {
            addCriterion("senddate in", values, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateNotIn(List<Date> values) {
            addCriterion("senddate not in", values, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateBetween(Date value1, Date value2) {
            addCriterion("senddate between", value1, value2, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateNotBetween(Date value1, Date value2) {
            addCriterion("senddate not between", value1, value2, "senddate");
            return (Criteria) this;
        }

        public Criteria andRemindtxtIsNull() {
            addCriterion("remindtxt is null");
            return (Criteria) this;
        }

        public Criteria andRemindtxtIsNotNull() {
            addCriterion("remindtxt is not null");
            return (Criteria) this;
        }

        public Criteria andRemindtxtEqualTo(String value) {
            addCriterion("remindtxt =", value, "remindtxt");
            return (Criteria) this;
        }

        public Criteria andRemindtxtNotEqualTo(String value) {
            addCriterion("remindtxt <>", value, "remindtxt");
            return (Criteria) this;
        }

        public Criteria andRemindtxtGreaterThan(String value) {
            addCriterion("remindtxt >", value, "remindtxt");
            return (Criteria) this;
        }

        public Criteria andRemindtxtGreaterThanOrEqualTo(String value) {
            addCriterion("remindtxt >=", value, "remindtxt");
            return (Criteria) this;
        }

        public Criteria andRemindtxtLessThan(String value) {
            addCriterion("remindtxt <", value, "remindtxt");
            return (Criteria) this;
        }

        public Criteria andRemindtxtLessThanOrEqualTo(String value) {
            addCriterion("remindtxt <=", value, "remindtxt");
            return (Criteria) this;
        }

        public Criteria andRemindtxtLike(String value) {
            addCriterion("remindtxt like", value, "remindtxt");
            return (Criteria) this;
        }

        public Criteria andRemindtxtNotLike(String value) {
            addCriterion("remindtxt not like", value, "remindtxt");
            return (Criteria) this;
        }

        public Criteria andRemindtxtIn(List<String> values) {
            addCriterion("remindtxt in", values, "remindtxt");
            return (Criteria) this;
        }

        public Criteria andRemindtxtNotIn(List<String> values) {
            addCriterion("remindtxt not in", values, "remindtxt");
            return (Criteria) this;
        }

        public Criteria andRemindtxtBetween(String value1, String value2) {
            addCriterion("remindtxt between", value1, value2, "remindtxt");
            return (Criteria) this;
        }

        public Criteria andRemindtxtNotBetween(String value1, String value2) {
            addCriterion("remindtxt not between", value1, value2, "remindtxt");
            return (Criteria) this;
        }

        public Criteria andRefparmIsNull() {
            addCriterion("refparm is null");
            return (Criteria) this;
        }

        public Criteria andRefparmIsNotNull() {
            addCriterion("refparm is not null");
            return (Criteria) this;
        }

        public Criteria andRefparmEqualTo(String value) {
            addCriterion("refparm =", value, "refparm");
            return (Criteria) this;
        }

        public Criteria andRefparmNotEqualTo(String value) {
            addCriterion("refparm <>", value, "refparm");
            return (Criteria) this;
        }

        public Criteria andRefparmGreaterThan(String value) {
            addCriterion("refparm >", value, "refparm");
            return (Criteria) this;
        }

        public Criteria andRefparmGreaterThanOrEqualTo(String value) {
            addCriterion("refparm >=", value, "refparm");
            return (Criteria) this;
        }

        public Criteria andRefparmLessThan(String value) {
            addCriterion("refparm <", value, "refparm");
            return (Criteria) this;
        }

        public Criteria andRefparmLessThanOrEqualTo(String value) {
            addCriterion("refparm <=", value, "refparm");
            return (Criteria) this;
        }

        public Criteria andRefparmLike(String value) {
            addCriterion("refparm like", value, "refparm");
            return (Criteria) this;
        }

        public Criteria andRefparmNotLike(String value) {
            addCriterion("refparm not like", value, "refparm");
            return (Criteria) this;
        }

        public Criteria andRefparmIn(List<String> values) {
            addCriterion("refparm in", values, "refparm");
            return (Criteria) this;
        }

        public Criteria andRefparmNotIn(List<String> values) {
            addCriterion("refparm not in", values, "refparm");
            return (Criteria) this;
        }

        public Criteria andRefparmBetween(String value1, String value2) {
            addCriterion("refparm between", value1, value2, "refparm");
            return (Criteria) this;
        }

        public Criteria andRefparmNotBetween(String value1, String value2) {
            addCriterion("refparm not between", value1, value2, "refparm");
            return (Criteria) this;
        }

        public Criteria andRefaddlinkIsNull() {
            addCriterion("refaddlink is null");
            return (Criteria) this;
        }

        public Criteria andRefaddlinkIsNotNull() {
            addCriterion("refaddlink is not null");
            return (Criteria) this;
        }

        public Criteria andRefaddlinkEqualTo(String value) {
            addCriterion("refaddlink =", value, "refaddlink");
            return (Criteria) this;
        }

        public Criteria andRefaddlinkNotEqualTo(String value) {
            addCriterion("refaddlink <>", value, "refaddlink");
            return (Criteria) this;
        }

        public Criteria andRefaddlinkGreaterThan(String value) {
            addCriterion("refaddlink >", value, "refaddlink");
            return (Criteria) this;
        }

        public Criteria andRefaddlinkGreaterThanOrEqualTo(String value) {
            addCriterion("refaddlink >=", value, "refaddlink");
            return (Criteria) this;
        }

        public Criteria andRefaddlinkLessThan(String value) {
            addCriterion("refaddlink <", value, "refaddlink");
            return (Criteria) this;
        }

        public Criteria andRefaddlinkLessThanOrEqualTo(String value) {
            addCriterion("refaddlink <=", value, "refaddlink");
            return (Criteria) this;
        }

        public Criteria andRefaddlinkLike(String value) {
            addCriterion("refaddlink like", value, "refaddlink");
            return (Criteria) this;
        }

        public Criteria andRefaddlinkNotLike(String value) {
            addCriterion("refaddlink not like", value, "refaddlink");
            return (Criteria) this;
        }

        public Criteria andRefaddlinkIn(List<String> values) {
            addCriterion("refaddlink in", values, "refaddlink");
            return (Criteria) this;
        }

        public Criteria andRefaddlinkNotIn(List<String> values) {
            addCriterion("refaddlink not in", values, "refaddlink");
            return (Criteria) this;
        }

        public Criteria andRefaddlinkBetween(String value1, String value2) {
            addCriterion("refaddlink between", value1, value2, "refaddlink");
            return (Criteria) this;
        }

        public Criteria andRefaddlinkNotBetween(String value1, String value2) {
            addCriterion("refaddlink not between", value1, value2, "refaddlink");
            return (Criteria) this;
        }

        public Criteria andRmdateexpIsNull() {
            addCriterion("rmdateexp is null");
            return (Criteria) this;
        }

        public Criteria andRmdateexpIsNotNull() {
            addCriterion("rmdateexp is not null");
            return (Criteria) this;
        }

        public Criteria andRmdateexpEqualTo(Date value) {
            addCriterion("rmdateexp =", value, "rmdateexp");
            return (Criteria) this;
        }

        public Criteria andRmdateexpNotEqualTo(Date value) {
            addCriterion("rmdateexp <>", value, "rmdateexp");
            return (Criteria) this;
        }

        public Criteria andRmdateexpGreaterThan(Date value) {
            addCriterion("rmdateexp >", value, "rmdateexp");
            return (Criteria) this;
        }

        public Criteria andRmdateexpGreaterThanOrEqualTo(Date value) {
            addCriterion("rmdateexp >=", value, "rmdateexp");
            return (Criteria) this;
        }

        public Criteria andRmdateexpLessThan(Date value) {
            addCriterion("rmdateexp <", value, "rmdateexp");
            return (Criteria) this;
        }

        public Criteria andRmdateexpLessThanOrEqualTo(Date value) {
            addCriterion("rmdateexp <=", value, "rmdateexp");
            return (Criteria) this;
        }

        public Criteria andRmdateexpIn(List<Date> values) {
            addCriterion("rmdateexp in", values, "rmdateexp");
            return (Criteria) this;
        }

        public Criteria andRmdateexpNotIn(List<Date> values) {
            addCriterion("rmdateexp not in", values, "rmdateexp");
            return (Criteria) this;
        }

        public Criteria andRmdateexpBetween(Date value1, Date value2) {
            addCriterion("rmdateexp between", value1, value2, "rmdateexp");
            return (Criteria) this;
        }

        public Criteria andRmdateexpNotBetween(Date value1, Date value2) {
            addCriterion("rmdateexp not between", value1, value2, "rmdateexp");
            return (Criteria) this;
        }

        public Criteria andIsseeIsNull() {
            addCriterion("issee is null");
            return (Criteria) this;
        }

        public Criteria andIsseeIsNotNull() {
            addCriterion("issee is not null");
            return (Criteria) this;
        }

        public Criteria andIsseeEqualTo(Integer value) {
            addCriterion("issee =", value, "issee");
            return (Criteria) this;
        }

        public Criteria andIsseeNotEqualTo(Integer value) {
            addCriterion("issee <>", value, "issee");
            return (Criteria) this;
        }

        public Criteria andIsseeGreaterThan(Integer value) {
            addCriterion("issee >", value, "issee");
            return (Criteria) this;
        }

        public Criteria andIsseeGreaterThanOrEqualTo(Integer value) {
            addCriterion("issee >=", value, "issee");
            return (Criteria) this;
        }

        public Criteria andIsseeLessThan(Integer value) {
            addCriterion("issee <", value, "issee");
            return (Criteria) this;
        }

        public Criteria andIsseeLessThanOrEqualTo(Integer value) {
            addCriterion("issee <=", value, "issee");
            return (Criteria) this;
        }

        public Criteria andIsseeIn(List<Integer> values) {
            addCriterion("issee in", values, "issee");
            return (Criteria) this;
        }

        public Criteria andIsseeNotIn(List<Integer> values) {
            addCriterion("issee not in", values, "issee");
            return (Criteria) this;
        }

        public Criteria andIsseeBetween(Integer value1, Integer value2) {
            addCriterion("issee between", value1, value2, "issee");
            return (Criteria) this;
        }

        public Criteria andIsseeNotBetween(Integer value1, Integer value2) {
            addCriterion("issee not between", value1, value2, "issee");
            return (Criteria) this;
        }

        public Criteria andIstodoIsNull() {
            addCriterion("istodo is null");
            return (Criteria) this;
        }

        public Criteria andIstodoIsNotNull() {
            addCriterion("istodo is not null");
            return (Criteria) this;
        }

        public Criteria andIstodoEqualTo(Integer value) {
            addCriterion("istodo =", value, "istodo");
            return (Criteria) this;
        }

        public Criteria andIstodoNotEqualTo(Integer value) {
            addCriterion("istodo <>", value, "istodo");
            return (Criteria) this;
        }

        public Criteria andIstodoGreaterThan(Integer value) {
            addCriterion("istodo >", value, "istodo");
            return (Criteria) this;
        }

        public Criteria andIstodoGreaterThanOrEqualTo(Integer value) {
            addCriterion("istodo >=", value, "istodo");
            return (Criteria) this;
        }

        public Criteria andIstodoLessThan(Integer value) {
            addCriterion("istodo <", value, "istodo");
            return (Criteria) this;
        }

        public Criteria andIstodoLessThanOrEqualTo(Integer value) {
            addCriterion("istodo <=", value, "istodo");
            return (Criteria) this;
        }

        public Criteria andIstodoIn(List<Integer> values) {
            addCriterion("istodo in", values, "istodo");
            return (Criteria) this;
        }

        public Criteria andIstodoNotIn(List<Integer> values) {
            addCriterion("istodo not in", values, "istodo");
            return (Criteria) this;
        }

        public Criteria andIstodoBetween(Integer value1, Integer value2) {
            addCriterion("istodo between", value1, value2, "istodo");
            return (Criteria) this;
        }

        public Criteria andIstodoNotBetween(Integer value1, Integer value2) {
            addCriterion("istodo not between", value1, value2, "istodo");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Boolean value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Boolean value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Boolean value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Boolean value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Boolean> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Boolean> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    public static class Criterion implements Serializable {
        private final String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private final String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
