package com.likes.common.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class InfSysremindinfo implements Serializable {
    /**
     * 字段: inf_sysremindinfo.rmdid<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 消息id
     *
     * @mbggenerated
     */
    private Long rmdid;

    /**
     * 字段: inf_sysremindinfo.bdpushid<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 推送id
     *
     * @mbggenerated
     */
    private Long bdpushid;

    /**
     * 字段: inf_sysremindinfo.sender<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 发送者accno
     *
     * @mbggenerated
     */
    private String sender;

    /**
     * 字段: inf_sysremindinfo.rmtype<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 提醒信息类型：order订单提醒  pay 支付消息，auditvideo视频审核提醒 ,auditimg图文审核提醒 other通用提醒comment评论system系统systemnotice 主播发送微信
     *
     * @mbggenerated
     */
    private String rmtype;

    /**
     * 字段: inf_sysremindinfo.recipienter<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 接收人：accno
     *
     * @mbggenerated
     */
    private String recipienter;

    /**
     * 字段: inf_sysremindinfo.uuid<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 64<br/>
     * 说明: 识别码（群发标识符）
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * 字段: inf_sysremindinfo.rmpics<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 400<br/>
     * 说明: 通知图片 多张以“,”分隔
     *
     * @mbggenerated
     */
    private String rmpics;

    /**
     * 字段: inf_sysremindinfo.rmtitle<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 消息标题
     *
     * @mbggenerated
     */
    private String rmtitle;

    /**
     * 字段: inf_sysremindinfo.senddate<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 发送时间
     *
     * @mbggenerated
     */
    private Date senddate;

    /**
     * 字段: inf_sysremindinfo.remindtxt<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 400<br/>
     * 说明: 提醒消息
     *
     * @mbggenerated
     */
    private String remindtxt;

    /**
     * 字段: inf_sysremindinfo.refparm<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 相关参数id、code
     *
     * @mbggenerated
     */
    private String refparm;

    /**
     * 字段: inf_sysremindinfo.refaddlink<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 200<br/>
     * 说明: 相关链接
     *
     * @mbggenerated
     */
    private String refaddlink;

    /**
     * 字段: inf_sysremindinfo.rmdateexp<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 提醒失效时间 一般提醒7天 重要提醒30天
     *
     * @mbggenerated
     */
    private Date rmdateexp;

    /**
     * 字段: inf_sysremindinfo.issee<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1<br/>
     * 说明: 是否查看0已查看 9未查看
     *
     * @mbggenerated
     */
    private Integer issee;

    /**
     * 字段: inf_sysremindinfo.istodo<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1<br/>
     * 说明: 是否处理0已处理 9未处理
     *
     * @mbggenerated
     */
    private Integer istodo;

    /**
     * 字段: inf_sysremindinfo.is_delete<br/>
     * 必填: true<br/>
     * 缺省: b'0'<br/>
     * 长度: 1<br/>
     * 说明: 是否删除
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * 字段: inf_sysremindinfo.create_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 创建人
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * 字段: inf_sysremindinfo.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 字段: inf_sysremindinfo.update_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 最后修改人
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * 字段: inf_sysremindinfo.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return inf_sysremindinfo.rmdid: 消息id
     *
     * @mbggenerated
     */
    public Long getRmdid() {
        return rmdid;
    }

    /**
     * 字段: inf_sysremindinfo.rmdid<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 消息id
     *
     * @mbggenerated
     */
    public void setRmdid(Long rmdid) {
        this.rmdid = rmdid;
    }

    /**
     * @return inf_sysremindinfo.bdpushid: 推送id
     *
     * @mbggenerated
     */
    public Long getBdpushid() {
        return bdpushid;
    }

    /**
     * 字段: inf_sysremindinfo.bdpushid<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 推送id
     *
     * @mbggenerated
     */
    public void setBdpushid(Long bdpushid) {
        this.bdpushid = bdpushid;
    }

    /**
     * @return inf_sysremindinfo.sender: 发送者accno
     *
     * @mbggenerated
     */
    public String getSender() {
        return sender;
    }

    /**
     * 字段: inf_sysremindinfo.sender<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 发送者accno
     *
     * @mbggenerated
     */
    public void setSender(String sender) {
        this.sender = sender;
    }

    /**
     * @return inf_sysremindinfo.rmtype: 提醒信息类型：order订单提醒  pay 支付消息，auditvideo视频审核提醒 ,auditimg图文审核提醒 other通用提醒comment评论system系统systemnotice 主播发送微信
     *
     * @mbggenerated
     */
    public String getRmtype() {
        return rmtype;
    }

    /**
     * 字段: inf_sysremindinfo.rmtype<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 提醒信息类型：order订单提醒  pay 支付消息，auditvideo视频审核提醒 ,auditimg图文审核提醒 other通用提醒comment评论system系统systemnotice 主播发送微信
     *
     * @mbggenerated
     */
    public void setRmtype(String rmtype) {
        this.rmtype = rmtype;
    }

    /**
     * @return inf_sysremindinfo.recipienter: 接收人：accno
     *
     * @mbggenerated
     */
    public String getRecipienter() {
        return recipienter;
    }

    /**
     * 字段: inf_sysremindinfo.recipienter<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 接收人：accno
     *
     * @mbggenerated
     */
    public void setRecipienter(String recipienter) {
        this.recipienter = recipienter;
    }

    /**
     * @return inf_sysremindinfo.uuid: 识别码（群发标识符）
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * 字段: inf_sysremindinfo.uuid<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 64<br/>
     * 说明: 识别码（群发标识符）
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * @return inf_sysremindinfo.rmpics: 通知图片 多张以“,”分隔
     *
     * @mbggenerated
     */
    public String getRmpics() {
        return rmpics;
    }

    /**
     * 字段: inf_sysremindinfo.rmpics<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 400<br/>
     * 说明: 通知图片 多张以“,”分隔
     *
     * @mbggenerated
     */
    public void setRmpics(String rmpics) {
        this.rmpics = rmpics;
    }

    /**
     * @return inf_sysremindinfo.rmtitle: 消息标题
     *
     * @mbggenerated
     */
    public String getRmtitle() {
        return rmtitle;
    }

    /**
     * 字段: inf_sysremindinfo.rmtitle<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 消息标题
     *
     * @mbggenerated
     */
    public void setRmtitle(String rmtitle) {
        this.rmtitle = rmtitle;
    }

    /**
     * @return inf_sysremindinfo.senddate: 发送时间
     *
     * @mbggenerated
     */
    public Date getSenddate() {
        return senddate;
    }

    /**
     * 字段: inf_sysremindinfo.senddate<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 发送时间
     *
     * @mbggenerated
     */
    public void setSenddate(Date senddate) {
        this.senddate = senddate;
    }

    /**
     * @return inf_sysremindinfo.remindtxt: 提醒消息
     *
     * @mbggenerated
     */
    public String getRemindtxt() {
        return remindtxt;
    }

    /**
     * 字段: inf_sysremindinfo.remindtxt<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 400<br/>
     * 说明: 提醒消息
     *
     * @mbggenerated
     */
    public void setRemindtxt(String remindtxt) {
        this.remindtxt = remindtxt;
    }

    /**
     * @return inf_sysremindinfo.refparm: 相关参数id、code
     *
     * @mbggenerated
     */
    public String getRefparm() {
        return refparm;
    }

    /**
     * 字段: inf_sysremindinfo.refparm<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 相关参数id、code
     *
     * @mbggenerated
     */
    public void setRefparm(String refparm) {
        this.refparm = refparm;
    }

    /**
     * @return inf_sysremindinfo.refaddlink: 相关链接
     *
     * @mbggenerated
     */
    public String getRefaddlink() {
        return refaddlink;
    }

    /**
     * 字段: inf_sysremindinfo.refaddlink<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 200<br/>
     * 说明: 相关链接
     *
     * @mbggenerated
     */
    public void setRefaddlink(String refaddlink) {
        this.refaddlink = refaddlink;
    }

    /**
     * @return inf_sysremindinfo.rmdateexp: 提醒失效时间 一般提醒7天 重要提醒30天
     *
     * @mbggenerated
     */
    public Date getRmdateexp() {
        return rmdateexp;
    }

    /**
     * 字段: inf_sysremindinfo.rmdateexp<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 提醒失效时间 一般提醒7天 重要提醒30天
     *
     * @mbggenerated
     */
    public void setRmdateexp(Date rmdateexp) {
        this.rmdateexp = rmdateexp;
    }

    /**
     * @return inf_sysremindinfo.issee: 是否查看0已查看 9未查看
     *
     * @mbggenerated
     */
    public Integer getIssee() {
        return issee;
    }

    /**
     * 字段: inf_sysremindinfo.issee<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1<br/>
     * 说明: 是否查看0已查看 9未查看
     *
     * @mbggenerated
     */
    public void setIssee(Integer issee) {
        this.issee = issee;
    }

    /**
     * @return inf_sysremindinfo.istodo: 是否处理0已处理 9未处理
     *
     * @mbggenerated
     */
    public Integer getIstodo() {
        return istodo;
    }

    /**
     * 字段: inf_sysremindinfo.istodo<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1<br/>
     * 说明: 是否处理0已处理 9未处理
     *
     * @mbggenerated
     */
    public void setIstodo(Integer istodo) {
        this.istodo = istodo;
    }

    /**
     * @return inf_sysremindinfo.is_delete: 是否删除
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * 字段: inf_sysremindinfo.is_delete<br/>
     * 必填: true<br/>
     * 缺省: b'0'<br/>
     * 长度: 1<br/>
     * 说明: 是否删除
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * @return inf_sysremindinfo.create_user: 创建人
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * 字段: inf_sysremindinfo.create_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 创建人
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * @return inf_sysremindinfo.create_time: 创建时间
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 字段: inf_sysremindinfo.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return inf_sysremindinfo.update_user: 最后修改人
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * 字段: inf_sysremindinfo.update_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 最后修改人
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * @return inf_sysremindinfo.update_time: 更新时间
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 字段: inf_sysremindinfo.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InfSysremindinfo other = (InfSysremindinfo) that;
        return (this.getRmdid() == null ? other.getRmdid() == null : this.getRmdid().equals(other.getRmdid()))
            && (this.getBdpushid() == null ? other.getBdpushid() == null : this.getBdpushid().equals(other.getBdpushid()))
            && (this.getSender() == null ? other.getSender() == null : this.getSender().equals(other.getSender()))
            && (this.getRmtype() == null ? other.getRmtype() == null : this.getRmtype().equals(other.getRmtype()))
            && (this.getRecipienter() == null ? other.getRecipienter() == null : this.getRecipienter().equals(other.getRecipienter()))
            && (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getRmpics() == null ? other.getRmpics() == null : this.getRmpics().equals(other.getRmpics()))
            && (this.getRmtitle() == null ? other.getRmtitle() == null : this.getRmtitle().equals(other.getRmtitle()))
            && (this.getSenddate() == null ? other.getSenddate() == null : this.getSenddate().equals(other.getSenddate()))
            && (this.getRemindtxt() == null ? other.getRemindtxt() == null : this.getRemindtxt().equals(other.getRemindtxt()))
            && (this.getRefparm() == null ? other.getRefparm() == null : this.getRefparm().equals(other.getRefparm()))
            && (this.getRefaddlink() == null ? other.getRefaddlink() == null : this.getRefaddlink().equals(other.getRefaddlink()))
            && (this.getRmdateexp() == null ? other.getRmdateexp() == null : this.getRmdateexp().equals(other.getRmdateexp()))
            && (this.getIssee() == null ? other.getIssee() == null : this.getIssee().equals(other.getIssee()))
            && (this.getIstodo() == null ? other.getIstodo() == null : this.getIstodo().equals(other.getIstodo()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRmdid() == null) ? 0 : getRmdid().hashCode());
        result = prime * result + ((getBdpushid() == null) ? 0 : getBdpushid().hashCode());
        result = prime * result + ((getSender() == null) ? 0 : getSender().hashCode());
        result = prime * result + ((getRmtype() == null) ? 0 : getRmtype().hashCode());
        result = prime * result + ((getRecipienter() == null) ? 0 : getRecipienter().hashCode());
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getRmpics() == null) ? 0 : getRmpics().hashCode());
        result = prime * result + ((getRmtitle() == null) ? 0 : getRmtitle().hashCode());
        result = prime * result + ((getSenddate() == null) ? 0 : getSenddate().hashCode());
        result = prime * result + ((getRemindtxt() == null) ? 0 : getRemindtxt().hashCode());
        result = prime * result + ((getRefparm() == null) ? 0 : getRefparm().hashCode());
        result = prime * result + ((getRefaddlink() == null) ? 0 : getRefaddlink().hashCode());
        result = prime * result + ((getRmdateexp() == null) ? 0 : getRmdateexp().hashCode());
        result = prime * result + ((getIssee() == null) ? 0 : getIssee().hashCode());
        result = prime * result + ((getIstodo() == null) ? 0 : getIstodo().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inf_sysremindinfo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rmdid=").append(rmdid);
        sb.append(", bdpushid=").append(bdpushid);
        sb.append(", sender=").append(sender);
        sb.append(", rmtype=").append(rmtype);
        sb.append(", recipienter=").append(recipienter);
        sb.append(", uuid=").append(uuid);
        sb.append(", rmpics=").append(rmpics);
        sb.append(", rmtitle=").append(rmtitle);
        sb.append(", senddate=").append(senddate);
        sb.append(", remindtxt=").append(remindtxt);
        sb.append(", refparm=").append(refparm);
        sb.append(", refaddlink=").append(refaddlink);
        sb.append(", rmdateexp=").append(rmdateexp);
        sb.append(", issee=").append(issee);
        sb.append(", istodo=").append(istodo);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}