package com.likes.common.mybatis.entity;

import java.io.Serializable;

public class MemHotsearch implements Serializable {
    /**
     * 字段: mem_hotsearch.searchid<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 热词id
     *
     * @mbggenerated
     */
    private Long searchid;

    /**
     * 字段: mem_hotsearch.searchname<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 50<br/>
     * 说明: 热词名称
     *
     * @mbggenerated
     */
    private String searchname;

    /**
     * 字段: mem_hotsearch.searchtype<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1<br/>
     * 说明: 热词类型: 1图文  2短视频 3 直播
     *
     * @mbggenerated
     */
    private Integer searchtype;

    /**
     * 字段: mem_hotsearch.searchnums<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 搜索次数(可作为展示排序)
     *
     * @mbggenerated
     */
    private Long searchnums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return mem_hotsearch.searchid: 热词id
     *
     * @mbggenerated
     */
    public Long getSearchid() {
        return searchid;
    }

    /**
     * 字段: mem_hotsearch.searchid<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 热词id
     *
     * @mbggenerated
     */
    public void setSearchid(Long searchid) {
        this.searchid = searchid;
    }

    /**
     * @return mem_hotsearch.searchname: 热词名称
     *
     * @mbggenerated
     */
    public String getSearchname() {
        return searchname;
    }

    /**
     * 字段: mem_hotsearch.searchname<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 50<br/>
     * 说明: 热词名称
     *
     * @mbggenerated
     */
    public void setSearchname(String searchname) {
        this.searchname = searchname;
    }

    /**
     * @return mem_hotsearch.searchtype: 热词类型: 1图文  2短视频 3 直播
     *
     * @mbggenerated
     */
    public Integer getSearchtype() {
        return searchtype;
    }

    /**
     * 字段: mem_hotsearch.searchtype<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1<br/>
     * 说明: 热词类型: 1图文  2短视频 3 直播
     *
     * @mbggenerated
     */
    public void setSearchtype(Integer searchtype) {
        this.searchtype = searchtype;
    }

    /**
     * @return mem_hotsearch.searchnums: 搜索次数(可作为展示排序)
     *
     * @mbggenerated
     */
    public Long getSearchnums() {
        return searchnums;
    }

    /**
     * 字段: mem_hotsearch.searchnums<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 搜索次数(可作为展示排序)
     *
     * @mbggenerated
     */
    public void setSearchnums(Long searchnums) {
        this.searchnums = searchnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MemHotsearch other = (MemHotsearch) that;
        return (this.getSearchid() == null ? other.getSearchid() == null : this.getSearchid().equals(other.getSearchid()))
            && (this.getSearchname() == null ? other.getSearchname() == null : this.getSearchname().equals(other.getSearchname()))
            && (this.getSearchtype() == null ? other.getSearchtype() == null : this.getSearchtype().equals(other.getSearchtype()))
            && (this.getSearchnums() == null ? other.getSearchnums() == null : this.getSearchnums().equals(other.getSearchnums()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSearchid() == null) ? 0 : getSearchid().hashCode());
        result = prime * result + ((getSearchname() == null) ? 0 : getSearchname().hashCode());
        result = prime * result + ((getSearchtype() == null) ? 0 : getSearchtype().hashCode());
        result = prime * result + ((getSearchnums() == null) ? 0 : getSearchnums().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", searchid=").append(searchid);
        sb.append(", searchname=").append(searchname);
        sb.append(", searchtype=").append(searchtype);
        sb.append(", searchnums=").append(searchnums);
        sb.append("]");
        return sb.toString();
    }
}