package com.likes.common.mybatis.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MgBetOrder implements Serializable {
    /**
     * 字段: mg_bet_order.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * 字段: mg_bet_order.player_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 玩家名称
     *
     * @mbggenerated
     */
    private String playerName;

    /**
     * 字段: mg_bet_order.vendor_code<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 产品代码
     *
     * @mbggenerated
     */
    private String vendorCode;

    /**
     * 字段: mg_bet_order.game_code<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 游戏代码
     *
     * @mbggenerated
     */
    private String gameCode;

    /**
     * 字段: mg_bet_order.parent_bet_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 父注编号
     *
     * @mbggenerated
     */
    private String parentBetId;

    /**
     * 字段: mg_bet_order.bet_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 下注编号
     *
     * @mbggenerated
     */
    private String betId;

    /**
     * 字段: mg_bet_order.trans_type<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 类型
     *
     * @mbggenerated
     */
    private String transType;

    /**
     * 字段: mg_bet_order.currency<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 币种
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * 字段: mg_bet_order.wallet_code<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 钱包代码
     *
     * @mbggenerated
     */
    private String walletCode;

    /**
     * 字段: mg_bet_order.bet_amount<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 下注金额
     *
     * @mbggenerated
     */
    private BigDecimal betAmount;

    /**
     * 字段: mg_bet_order.win_amount<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 派彩或退回金额
     *
     * @mbggenerated
     */
    private BigDecimal winAmount;

    /**
     * 字段: mg_bet_order.traceId<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 交易编号
     *
     * @mbggenerated
     */
    private String traceid;

    /**
     * 字段: mg_bet_order.is_handle<br/>
     * 必填: false<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 是否同步
     *
     * @mbggenerated
     */
    private Integer isHandle;

    /**
     * 字段: mg_bet_order.created_at<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 建立日期
     *
     * @mbggenerated
     */
    @JsonFormat(
            pattern = "yyyy-MM-dd HH:mm:ss",
            timezone = "GMT-6"
    )
    private Date createdAt;

    /**
     * 字段: mg_bet_order.create_time<br/>
     * 必填: false<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    @JsonFormat(
            pattern = "yyyy-MM-dd HH:mm:ss",
            timezone = "GMT-6"
    )
    private Date createTime;

    /**
     * 字段: mg_bet_order.user_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 用户ID
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * 字段: mg_bet_order.game_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 游戏名称
     *
     * @mbggenerated
     */
    private String gameName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return mg_bet_order.id: 
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * 字段: mg_bet_order.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return mg_bet_order.player_name: 玩家名称
     *
     * @mbggenerated
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * 字段: mg_bet_order.player_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 玩家名称
     *
     * @mbggenerated
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    /**
     * @return mg_bet_order.vendor_code: 产品代码
     *
     * @mbggenerated
     */
    public String getVendorCode() {
        return vendorCode;
    }

    /**
     * 字段: mg_bet_order.vendor_code<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 产品代码
     *
     * @mbggenerated
     */
    public void setVendorCode(String vendorCode) {
        this.vendorCode = vendorCode;
    }

    /**
     * @return mg_bet_order.game_code: 游戏代码
     *
     * @mbggenerated
     */
    public String getGameCode() {
        return gameCode;
    }

    /**
     * 字段: mg_bet_order.game_code<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 游戏代码
     *
     * @mbggenerated
     */
    public void setGameCode(String gameCode) {
        this.gameCode = gameCode;
    }

    /**
     * @return mg_bet_order.parent_bet_id: 父注编号
     *
     * @mbggenerated
     */
    public String getParentBetId() {
        return parentBetId;
    }

    /**
     * 字段: mg_bet_order.parent_bet_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 父注编号
     *
     * @mbggenerated
     */
    public void setParentBetId(String parentBetId) {
        this.parentBetId = parentBetId;
    }

    /**
     * @return mg_bet_order.bet_id: 下注编号
     *
     * @mbggenerated
     */
    public String getBetId() {
        return betId;
    }

    /**
     * 字段: mg_bet_order.bet_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 下注编号
     *
     * @mbggenerated
     */
    public void setBetId(String betId) {
        this.betId = betId;
    }

    /**
     * @return mg_bet_order.trans_type: 类型
     *
     * @mbggenerated
     */
    public String getTransType() {
        return transType;
    }

    /**
     * 字段: mg_bet_order.trans_type<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 类型
     *
     * @mbggenerated
     */
    public void setTransType(String transType) {
        this.transType = transType;
    }

    /**
     * @return mg_bet_order.currency: 币种
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * 字段: mg_bet_order.currency<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 币种
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * @return mg_bet_order.wallet_code: 钱包代码
     *
     * @mbggenerated
     */
    public String getWalletCode() {
        return walletCode;
    }

    /**
     * 字段: mg_bet_order.wallet_code<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 钱包代码
     *
     * @mbggenerated
     */
    public void setWalletCode(String walletCode) {
        this.walletCode = walletCode;
    }

    /**
     * @return mg_bet_order.bet_amount: 下注金额
     *
     * @mbggenerated
     */
    public BigDecimal getBetAmount() {
        return betAmount;
    }

    /**
     * 字段: mg_bet_order.bet_amount<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 下注金额
     *
     * @mbggenerated
     */
    public void setBetAmount(BigDecimal betAmount) {
        this.betAmount = betAmount;
    }

    /**
     * @return mg_bet_order.win_amount: 派彩或退回金额
     *
     * @mbggenerated
     */
    public BigDecimal getWinAmount() {
        return winAmount;
    }

    /**
     * 字段: mg_bet_order.win_amount<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 派彩或退回金额
     *
     * @mbggenerated
     */
    public void setWinAmount(BigDecimal winAmount) {
        this.winAmount = winAmount;
    }

    /**
     * @return mg_bet_order.traceId: 交易编号
     *
     * @mbggenerated
     */
    public String getTraceid() {
        return traceid;
    }

    /**
     * 字段: mg_bet_order.traceId<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 交易编号
     *
     * @mbggenerated
     */
    public void setTraceid(String traceid) {
        this.traceid = traceid;
    }

    /**
     * @return mg_bet_order.is_handle: 是否同步
     *
     * @mbggenerated
     */
    public Integer getIsHandle() {
        return isHandle;
    }

    /**
     * 字段: mg_bet_order.is_handle<br/>
     * 必填: false<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 是否同步
     *
     * @mbggenerated
     */
    public void setIsHandle(Integer isHandle) {
        this.isHandle = isHandle;
    }

    /**
     * @return mg_bet_order.created_at: 建立日期
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * 字段: mg_bet_order.created_at<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 建立日期
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * @return mg_bet_order.create_time: 创建时间
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 字段: mg_bet_order.create_time<br/>
     * 必填: false<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return mg_bet_order.user_id: 用户ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * 字段: mg_bet_order.user_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 用户ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * @return mg_bet_order.game_name: 游戏名称
     *
     * @mbggenerated
     */
    public String getGameName() {
        return gameName;
    }

    /**
     * 字段: mg_bet_order.game_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 游戏名称
     *
     * @mbggenerated
     */
    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MgBetOrder other = (MgBetOrder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPlayerName() == null ? other.getPlayerName() == null : this.getPlayerName().equals(other.getPlayerName()))
            && (this.getVendorCode() == null ? other.getVendorCode() == null : this.getVendorCode().equals(other.getVendorCode()))
            && (this.getGameCode() == null ? other.getGameCode() == null : this.getGameCode().equals(other.getGameCode()))
            && (this.getParentBetId() == null ? other.getParentBetId() == null : this.getParentBetId().equals(other.getParentBetId()))
            && (this.getBetId() == null ? other.getBetId() == null : this.getBetId().equals(other.getBetId()))
            && (this.getTransType() == null ? other.getTransType() == null : this.getTransType().equals(other.getTransType()))
            && (this.getCurrency() == null ? other.getCurrency() == null : this.getCurrency().equals(other.getCurrency()))
            && (this.getWalletCode() == null ? other.getWalletCode() == null : this.getWalletCode().equals(other.getWalletCode()))
            && (this.getBetAmount() == null ? other.getBetAmount() == null : this.getBetAmount().equals(other.getBetAmount()))
            && (this.getWinAmount() == null ? other.getWinAmount() == null : this.getWinAmount().equals(other.getWinAmount()))
            && (this.getTraceid() == null ? other.getTraceid() == null : this.getTraceid().equals(other.getTraceid()))
            && (this.getIsHandle() == null ? other.getIsHandle() == null : this.getIsHandle().equals(other.getIsHandle()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getGameName() == null ? other.getGameName() == null : this.getGameName().equals(other.getGameName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPlayerName() == null) ? 0 : getPlayerName().hashCode());
        result = prime * result + ((getVendorCode() == null) ? 0 : getVendorCode().hashCode());
        result = prime * result + ((getGameCode() == null) ? 0 : getGameCode().hashCode());
        result = prime * result + ((getParentBetId() == null) ? 0 : getParentBetId().hashCode());
        result = prime * result + ((getBetId() == null) ? 0 : getBetId().hashCode());
        result = prime * result + ((getTransType() == null) ? 0 : getTransType().hashCode());
        result = prime * result + ((getCurrency() == null) ? 0 : getCurrency().hashCode());
        result = prime * result + ((getWalletCode() == null) ? 0 : getWalletCode().hashCode());
        result = prime * result + ((getBetAmount() == null) ? 0 : getBetAmount().hashCode());
        result = prime * result + ((getWinAmount() == null) ? 0 : getWinAmount().hashCode());
        result = prime * result + ((getTraceid() == null) ? 0 : getTraceid().hashCode());
        result = prime * result + ((getIsHandle() == null) ? 0 : getIsHandle().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getGameName() == null) ? 0 : getGameName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", playerName=").append(playerName);
        sb.append(", vendorCode=").append(vendorCode);
        sb.append(", gameCode=").append(gameCode);
        sb.append(", parentBetId=").append(parentBetId);
        sb.append(", betId=").append(betId);
        sb.append(", transType=").append(transType);
        sb.append(", currency=").append(currency);
        sb.append(", walletCode=").append(walletCode);
        sb.append(", betAmount=").append(betAmount);
        sb.append(", winAmount=").append(winAmount);
        sb.append(", traceid=").append(traceid);
        sb.append(", isHandle=").append(isHandle);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", createTime=").append(createTime);
        sb.append(", userId=").append(userId);
        sb.append(", gameName=").append(gameName);
        sb.append("]");
        return sb.toString();
    }
}
