package com.likes.common.mybatis.entity;

import java.io.Serializable;

public class OrgAdminprivilegeKey implements Serializable {
    /**
     * 字段: org_adminprivilege.ogadid<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 子账号id
     *
     * @mbggenerated
     */
    private Long ogadid;

    /**
     * 字段: org_adminprivilege.sfunid<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 功能id
     *
     * @mbggenerated
     */
    private Long sfunid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table org_adminprivilege
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return org_adminprivilege.ogadid: 子账号id
     *
     * @mbggenerated
     */
    public Long getOgadid() {
        return ogadid;
    }

    /**
     * 字段: org_adminprivilege.ogadid<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 子账号id
     *
     * @mbggenerated
     */
    public void setOgadid(Long ogadid) {
        this.ogadid = ogadid;
    }

    /**
     * @return org_adminprivilege.sfunid: 功能id
     *
     * @mbggenerated
     */
    public Long getSfunid() {
        return sfunid;
    }

    /**
     * 字段: org_adminprivilege.sfunid<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 功能id
     *
     * @mbggenerated
     */
    public void setSfunid(Long sfunid) {
        this.sfunid = sfunid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_adminprivilege
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrgAdminprivilegeKey other = (OrgAdminprivilegeKey) that;
        return (this.getOgadid() == null ? other.getOgadid() == null : this.getOgadid().equals(other.getOgadid()))
            && (this.getSfunid() == null ? other.getSfunid() == null : this.getSfunid().equals(other.getSfunid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_adminprivilege
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOgadid() == null) ? 0 : getOgadid().hashCode());
        result = prime * result + ((getSfunid() == null) ? 0 : getSfunid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_adminprivilege
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ogadid=").append(ogadid);
        sb.append(", sfunid=").append(sfunid);
        sb.append("]");
        return sb.toString();
    }
}