//package com.likes.common.mybatis.entity;
//
//import java.io.Serializable;
//import java.util.Date;
//
//public class PayLevel implements Serializable {
//    /**
//     * 字段: pay_level.id<br/>
//     * 必填: true<br/>
//     * 缺省: <br/>
//     * 长度: 19<br/>
//     * 说明: 手动设置id
//     *
//     * @mbggenerated
//     */
//    private Long id;
//
//    /**
//     * 字段: pay_level.level_name<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 64<br/>
//     * 说明: 层级名称
//     *
//     * @mbggenerated
//     */
//    private String levelName;
//
//    /**
//     * 字段: pay_level.level_desc<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: 层级描述
//     *
//     * @mbggenerated
//     */
//    private String levelDesc;
//
//    /**
//     * 字段: pay_level.min_deposit_count<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 最小存款次数
//     *
//     * @mbggenerated
//     */
//    private Integer minDepositCount;
//
//    /**
//     * 字段: pay_level.min_recharge_amount<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 最小充值金额
//     *
//     * @mbggenerated
//     */
//    private Integer minRechargeAmount;
//
//    /**
//     * 字段: pay_level.max_recharge_amount<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 最大充值金额
//     *
//     * @mbggenerated
//     */
//    private Integer maxRechargeAmount;
//
//    /**
//     * 字段: pay_level.pay_onlines<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: 在线支付方式：支付id，逗号分隔
//     *
//     * @mbggenerated
//     */
//    private String payOnlines;
//
//    /**
//     * 字段: pay_level.pay_bank_accounts<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: 银行账户支付方式：支付id，逗号分隔
//     *
//     * @mbggenerated
//     */
//    private String payBankAccounts;
//
//    /**
//     * 字段: pay_level.api_address<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: api地址
//     *
//     * @mbggenerated
//     */
//    private String apiAddress;
//
//    /**
//     * 字段: pay_level.quick_money<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: 快捷金额：支付额度，逗号分隔
//     *
//     * @mbggenerated
//     */
//    private String quickMoney;
//
//    /**
//     * 字段: pay_level.is_deleted<br/>
//     * 必填: true<br/>
//     * 缺省: 0<br/>
//     * 长度: 10<br/>
//     * 说明: 是否删除（1：删除；0：未删除）
//     *
//     * @mbggenerated
//     */
//    private Integer isDeleted;
//
//    /**
//     * 字段: pay_level.created_at<br/>
//     * 必填: false<br/>
//     * 缺省: CURRENT_TIMESTAMP<br/>
//     * 长度: 19<br/>
//     * 说明: 创建时间
//     *
//     * @mbggenerated
//     */
//    private Date createdAt;
//
//    /**
//     * 字段: pay_level.update_at<br/>
//     * 必填: false<br/>
//     * 缺省: CURRENT_TIMESTAMP<br/>
//     * 长度: 19<br/>
//     * 说明: 修改时间
//     *
//     * @mbggenerated
//     */
//    private Date updateAt;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database table pay_level
//     *
//     * @mbggenerated
//     */
//    private static final long serialVersionUID = 1L;
//
//    /**
//     * @return pay_level.id: 手动设置id
//     *
//     * @mbggenerated
//     */
//    public Long getId() {
//        return id;
//    }
//
//    /**
//     * 字段: pay_level.id<br/>
//     * 必填: true<br/>
//     * 缺省: <br/>
//     * 长度: 19<br/>
//     * 说明: 手动设置id
//     *
//     * @mbggenerated
//     */
//    public void setId(Long id) {
//        this.id = id;
//    }
//
//    /**
//     * @return pay_level.level_name: 层级名称
//     *
//     * @mbggenerated
//     */
//    public String getLevelName() {
//        return levelName;
//    }
//
//    /**
//     * 字段: pay_level.level_name<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 64<br/>
//     * 说明: 层级名称
//     *
//     * @mbggenerated
//     */
//    public void setLevelName(String levelName) {
//        this.levelName = levelName;
//    }
//
//    /**
//     * @return pay_level.level_desc: 层级描述
//     *
//     * @mbggenerated
//     */
//    public String getLevelDesc() {
//        return levelDesc;
//    }
//
//    /**
//     * 字段: pay_level.level_desc<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: 层级描述
//     *
//     * @mbggenerated
//     */
//    public void setLevelDesc(String levelDesc) {
//        this.levelDesc = levelDesc;
//    }
//
//    /**
//     * @return pay_level.min_deposit_count: 最小存款次数
//     *
//     * @mbggenerated
//     */
//    public Integer getMinDepositCount() {
//        return minDepositCount;
//    }
//
//    /**
//     * 字段: pay_level.min_deposit_count<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 最小存款次数
//     *
//     * @mbggenerated
//     */
//    public void setMinDepositCount(Integer minDepositCount) {
//        this.minDepositCount = minDepositCount;
//    }
//
//    /**
//     * @return pay_level.min_recharge_amount: 最小充值金额
//     *
//     * @mbggenerated
//     */
//    public Integer getMinRechargeAmount() {
//        return minRechargeAmount;
//    }
//
//    /**
//     * 字段: pay_level.min_recharge_amount<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 最小充值金额
//     *
//     * @mbggenerated
//     */
//    public void setMinRechargeAmount(Integer minRechargeAmount) {
//        this.minRechargeAmount = minRechargeAmount;
//    }
//
//    /**
//     * @return pay_level.max_recharge_amount: 最大充值金额
//     *
//     * @mbggenerated
//     */
//    public Integer getMaxRechargeAmount() {
//        return maxRechargeAmount;
//    }
//
//    /**
//     * 字段: pay_level.max_recharge_amount<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 最大充值金额
//     *
//     * @mbggenerated
//     */
//    public void setMaxRechargeAmount(Integer maxRechargeAmount) {
//        this.maxRechargeAmount = maxRechargeAmount;
//    }
//
//    /**
//     * @return pay_level.pay_onlines: 在线支付方式：支付id，逗号分隔
//     *
//     * @mbggenerated
//     */
//    public String getPayOnlines() {
//        return payOnlines;
//    }
//
//    /**
//     * 字段: pay_level.pay_onlines<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: 在线支付方式：支付id，逗号分隔
//     *
//     * @mbggenerated
//     */
//    public void setPayOnlines(String payOnlines) {
//        this.payOnlines = payOnlines;
//    }
//
//    /**
//     * @return pay_level.pay_bank_accounts: 银行账户支付方式：支付id，逗号分隔
//     *
//     * @mbggenerated
//     */
//    public String getPayBankAccounts() {
//        return payBankAccounts;
//    }
//
//    /**
//     * 字段: pay_level.pay_bank_accounts<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: 银行账户支付方式：支付id，逗号分隔
//     *
//     * @mbggenerated
//     */
//    public void setPayBankAccounts(String payBankAccounts) {
//        this.payBankAccounts = payBankAccounts;
//    }
//
//    /**
//     * @return pay_level.api_address: api地址
//     *
//     * @mbggenerated
//     */
//    public String getApiAddress() {
//        return apiAddress;
//    }
//
//    /**
//     * 字段: pay_level.api_address<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: api地址
//     *
//     * @mbggenerated
//     */
//    public void setApiAddress(String apiAddress) {
//        this.apiAddress = apiAddress;
//    }
//
//    /**
//     * @return pay_level.quick_money: 快捷金额：支付额度，逗号分隔
//     *
//     * @mbggenerated
//     */
//    public String getQuickMoney() {
//        return quickMoney;
//    }
//
//    /**
//     * 字段: pay_level.quick_money<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: 快捷金额：支付额度，逗号分隔
//     *
//     * @mbggenerated
//     */
//    public void setQuickMoney(String quickMoney) {
//        this.quickMoney = quickMoney;
//    }
//
//    /**
//     * @return pay_level.is_deleted: 是否删除（1：删除；0：未删除）
//     *
//     * @mbggenerated
//     */
//    public Integer getIsDeleted() {
//        return isDeleted;
//    }
//
//    /**
//     * 字段: pay_level.is_deleted<br/>
//     * 必填: true<br/>
//     * 缺省: 0<br/>
//     * 长度: 10<br/>
//     * 说明: 是否删除（1：删除；0：未删除）
//     *
//     * @mbggenerated
//     */
//    public void setIsDeleted(Integer isDeleted) {
//        this.isDeleted = isDeleted;
//    }
//
//    /**
//     * @return pay_level.created_at: 创建时间
//     *
//     * @mbggenerated
//     */
//    public Date getCreatedAt() {
//        return createdAt;
//    }
//
//    /**
//     * 字段: pay_level.created_at<br/>
//     * 必填: false<br/>
//     * 缺省: CURRENT_TIMESTAMP<br/>
//     * 长度: 19<br/>
//     * 说明: 创建时间
//     *
//     * @mbggenerated
//     */
//    public void setCreatedAt(Date createdAt) {
//        this.createdAt = createdAt;
//    }
//
//    /**
//     * @return pay_level.update_at: 修改时间
//     *
//     * @mbggenerated
//     */
//    public Date getUpdateAt() {
//        return updateAt;
//    }
//
//    /**
//     * 字段: pay_level.update_at<br/>
//     * 必填: false<br/>
//     * 缺省: CURRENT_TIMESTAMP<br/>
//     * 长度: 19<br/>
//     * 说明: 修改时间
//     *
//     * @mbggenerated
//     */
//    public void setUpdateAt(Date updateAt) {
//        this.updateAt = updateAt;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table pay_level
//     *
//     * @mbggenerated
//     */
//    @Override
//    public boolean equals(Object that) {
//        if (this == that) {
//            return true;
//        }
//        if (that == null) {
//            return false;
//        }
//        if (getClass() != that.getClass()) {
//            return false;
//        }
//        PayLevel other = (PayLevel) that;
//        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
//            && (this.getLevelName() == null ? other.getLevelName() == null : this.getLevelName().equals(other.getLevelName()))
//            && (this.getLevelDesc() == null ? other.getLevelDesc() == null : this.getLevelDesc().equals(other.getLevelDesc()))
//            && (this.getMinDepositCount() == null ? other.getMinDepositCount() == null : this.getMinDepositCount().equals(other.getMinDepositCount()))
//            && (this.getMinRechargeAmount() == null ? other.getMinRechargeAmount() == null : this.getMinRechargeAmount().equals(other.getMinRechargeAmount()))
//            && (this.getMaxRechargeAmount() == null ? other.getMaxRechargeAmount() == null : this.getMaxRechargeAmount().equals(other.getMaxRechargeAmount()))
//            && (this.getPayOnlines() == null ? other.getPayOnlines() == null : this.getPayOnlines().equals(other.getPayOnlines()))
//            && (this.getPayBankAccounts() == null ? other.getPayBankAccounts() == null : this.getPayBankAccounts().equals(other.getPayBankAccounts()))
//            && (this.getApiAddress() == null ? other.getApiAddress() == null : this.getApiAddress().equals(other.getApiAddress()))
//            && (this.getQuickMoney() == null ? other.getQuickMoney() == null : this.getQuickMoney().equals(other.getQuickMoney()))
//            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()))
//            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
//            && (this.getUpdateAt() == null ? other.getUpdateAt() == null : this.getUpdateAt().equals(other.getUpdateAt()));
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table pay_level
//     *
//     * @mbggenerated
//     */
//    @Override
//    public int hashCode() {
//        final int prime = 31;
//        int result = 1;
//        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
//        result = prime * result + ((getLevelName() == null) ? 0 : getLevelName().hashCode());
//        result = prime * result + ((getLevelDesc() == null) ? 0 : getLevelDesc().hashCode());
//        result = prime * result + ((getMinDepositCount() == null) ? 0 : getMinDepositCount().hashCode());
//        result = prime * result + ((getMinRechargeAmount() == null) ? 0 : getMinRechargeAmount().hashCode());
//        result = prime * result + ((getMaxRechargeAmount() == null) ? 0 : getMaxRechargeAmount().hashCode());
//        result = prime * result + ((getPayOnlines() == null) ? 0 : getPayOnlines().hashCode());
//        result = prime * result + ((getPayBankAccounts() == null) ? 0 : getPayBankAccounts().hashCode());
//        result = prime * result + ((getApiAddress() == null) ? 0 : getApiAddress().hashCode());
//        result = prime * result + ((getQuickMoney() == null) ? 0 : getQuickMoney().hashCode());
//        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
//        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
//        result = prime * result + ((getUpdateAt() == null) ? 0 : getUpdateAt().hashCode());
//        return result;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table pay_level
//     *
//     * @mbggenerated
//     */
//    @Override
//    public String toString() {
//        StringBuilder sb = new StringBuilder();
//        sb.append(getClass().getSimpleName());
//        sb.append(" [");
//        sb.append("Hash = ").append(hashCode());
//        sb.append(", id=").append(id);
//        sb.append(", levelName=").append(levelName);
//        sb.append(", levelDesc=").append(levelDesc);
//        sb.append(", minDepositCount=").append(minDepositCount);
//        sb.append(", minRechargeAmount=").append(minRechargeAmount);
//        sb.append(", maxRechargeAmount=").append(maxRechargeAmount);
//        sb.append(", payOnlines=").append(payOnlines);
//        sb.append(", payBankAccounts=").append(payBankAccounts);
//        sb.append(", apiAddress=").append(apiAddress);
//        sb.append(", quickMoney=").append(quickMoney);
//        sb.append(", isDeleted=").append(isDeleted);
//        sb.append(", createdAt=").append(createdAt);
//        sb.append(", updateAt=").append(updateAt);
//        sb.append("]");
//        return sb.toString();
//    }
//}