//package com.likes.common.mybatis.entity;
//
//import java.io.Serializable;
//
//public class PayQuota implements Serializable {
//    /**
//     * 字段: pay_quota.id<br/>
//     * 主键: 自动增长<br/>
//     * 必填: true<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明:
//     *
//     * @mbggenerated
//     */
//    private Integer id;
//
//    /**
//     * 字段: pay_quota.money<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 金额
//     *
//     * @mbggenerated
//     */
//    private Integer money;
//
//    /**
//     * 字段: pay_quota.is_del<br/>
//     * 必填: true<br/>
//     * 缺省: 0<br/>
//     * 长度: 10<br/>
//     * 说明: 是否删除（0 正常 1 删除）
//     *
//     * @mbggenerated
//     */
//    private Integer isDel;
//
//    /**
//     * 字段: pay_quota.recharge_account_id<br/>
//     * 必填: false<br/>
//     * 缺省: 0<br/>
//     * 长度: 10<br/>
//     * 说明: 充值账户id
//     *
//     * @mbggenerated
//     */
//    private Integer rechargeAccountId;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database table pay_quota
//     *
//     * @mbggenerated
//     */
//    private static final long serialVersionUID = 1L;
//
//    /**
//     * @return pay_quota.id:
//     *
//     * @mbggenerated
//     */
//    public Integer getId() {
//        return id;
//    }
//
//    /**
//     * 字段: pay_quota.id<br/>
//     * 主键: 自动增长<br/>
//     * 必填: true<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明:
//     *
//     * @mbggenerated
//     */
//    public void setId(Integer id) {
//        this.id = id;
//    }
//
//    /**
//     * @return pay_quota.money: 金额
//     *
//     * @mbggenerated
//     */
//    public Integer getMoney() {
//        return money;
//    }
//
//    /**
//     * 字段: pay_quota.money<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 金额
//     *
//     * @mbggenerated
//     */
//    public void setMoney(Integer money) {
//        this.money = money;
//    }
//
//    /**
//     * @return pay_quota.is_del: 是否删除（0 正常 1 删除）
//     *
//     * @mbggenerated
//     */
//    public Integer getIsDel() {
//        return isDel;
//    }
//
//    /**
//     * 字段: pay_quota.is_del<br/>
//     * 必填: true<br/>
//     * 缺省: 0<br/>
//     * 长度: 10<br/>
//     * 说明: 是否删除（0 正常 1 删除）
//     *
//     * @mbggenerated
//     */
//    public void setIsDel(Integer isDel) {
//        this.isDel = isDel;
//    }
//
//    /**
//     * @return pay_quota.recharge_account_id: 充值账户id
//     *
//     * @mbggenerated
//     */
//    public Integer getRechargeAccountId() {
//        return rechargeAccountId;
//    }
//
//    /**
//     * 字段: pay_quota.recharge_account_id<br/>
//     * 必填: false<br/>
//     * 缺省: 0<br/>
//     * 长度: 10<br/>
//     * 说明: 充值账户id
//     *
//     * @mbggenerated
//     */
//    public void setRechargeAccountId(Integer rechargeAccountId) {
//        this.rechargeAccountId = rechargeAccountId;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table pay_quota
//     *
//     * @mbggenerated
//     */
//    @Override
//    public boolean equals(Object that) {
//        if (this == that) {
//            return true;
//        }
//        if (that == null) {
//            return false;
//        }
//        if (getClass() != that.getClass()) {
//            return false;
//        }
//        PayQuota other = (PayQuota) that;
//        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
//            && (this.getMoney() == null ? other.getMoney() == null : this.getMoney().equals(other.getMoney()))
//            && (this.getIsDel() == null ? other.getIsDel() == null : this.getIsDel().equals(other.getIsDel()))
//            && (this.getRechargeAccountId() == null ? other.getRechargeAccountId() == null : this.getRechargeAccountId().equals(other.getRechargeAccountId()));
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table pay_quota
//     *
//     * @mbggenerated
//     */
//    @Override
//    public int hashCode() {
//        final int prime = 31;
//        int result = 1;
//        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
//        result = prime * result + ((getMoney() == null) ? 0 : getMoney().hashCode());
//        result = prime * result + ((getIsDel() == null) ? 0 : getIsDel().hashCode());
//        result = prime * result + ((getRechargeAccountId() == null) ? 0 : getRechargeAccountId().hashCode());
//        return result;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table pay_quota
//     *
//     * @mbggenerated
//     */
//    @Override
//    public String toString() {
//        StringBuilder sb = new StringBuilder();
//        sb.append(getClass().getSimpleName());
//        sb.append(" [");
//        sb.append("Hash = ").append(hashCode());
//        sb.append(", id=").append(id);
//        sb.append(", money=").append(money);
//        sb.append(", isDel=").append(isDel);
//        sb.append(", rechargeAccountId=").append(rechargeAccountId);
//        sb.append("]");
//        return sb.toString();
//    }
//}