//package com.likes.common.mybatis.entity;
//
//import java.io.Serializable;
//import java.util.Date;
//
//public class PaySet implements Serializable {
//    /**
//     * 字段: pay_set.id<br/>
//     * 主键: 自动增长<br/>
//     * 必填: true<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明:
//     *
//     * @mbggenerated
//     */
//    private Integer id;
//
//    /**
//     * 字段: pay_set.platform_id<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 支付商户
//     *
//     * @mbggenerated
//     */
//    private Integer platformId;
//
//    /**
//     * 字段: pay_set.way_id<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 支付方式
//     *
//     * @mbggenerated
//     */
//    private Integer wayId;
//
//    /**
//     * 字段: pay_set.min_money<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 最小额度
//     *
//     * @mbggenerated
//     */
//    private Integer minMoney;
//
//    /**
//     * 字段: pay_set.max_money<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 最大额度
//     *
//     * @mbggenerated
//     */
//    private Integer maxMoney;
//
//    /**
//     * 字段: pay_set.is_start<br/>
//     * 必填: true<br/>
//     * 缺省: 0<br/>
//     * 长度: 10<br/>
//     * 说明: 是否启用（0 启用 1 暂停）
//     *
//     * @mbggenerated
//     */
//    private Integer isStart;
//
//    /**
//     * 字段: pay_set.is_del<br/>
//     * 必填: true<br/>
//     * 缺省: 0<br/>
//     * 长度: 10<br/>
//     * 说明: 是否删除（0 正常 1删除）
//     *
//     * @mbggenerated
//     */
//    private Integer isDel;
//
//    /**
//     * 字段: pay_set.pay_type<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: 渠道码
//     *
//     * @mbggenerated
//     */
//    private String payType;
//
//    /**
//     * 字段: pay_set.create_time<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 19<br/>
//     * 说明: 时间
//     *
//     * @mbggenerated
//     */
//    private Date createTime;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database table pay_set
//     *
//     * @mbggenerated
//     */
//    private static final long serialVersionUID = 1L;
//
//    /**
//     * @return pay_set.id:
//     *
//     * @mbggenerated
//     */
//    public Integer getId() {
//        return id;
//    }
//
//    /**
//     * 字段: pay_set.id<br/>
//     * 主键: 自动增长<br/>
//     * 必填: true<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明:
//     *
//     * @mbggenerated
//     */
//    public void setId(Integer id) {
//        this.id = id;
//    }
//
//    /**
//     * @return pay_set.platform_id: 支付商户
//     *
//     * @mbggenerated
//     */
//    public Integer getPlatformId() {
//        return platformId;
//    }
//
//    /**
//     * 字段: pay_set.platform_id<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 支付商户
//     *
//     * @mbggenerated
//     */
//    public void setPlatformId(Integer platformId) {
//        this.platformId = platformId;
//    }
//
//    /**
//     * @return pay_set.way_id: 支付方式
//     *
//     * @mbggenerated
//     */
//    public Integer getWayId() {
//        return wayId;
//    }
//
//    /**
//     * 字段: pay_set.way_id<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 支付方式
//     *
//     * @mbggenerated
//     */
//    public void setWayId(Integer wayId) {
//        this.wayId = wayId;
//    }
//
//    /**
//     * @return pay_set.min_money: 最小额度
//     *
//     * @mbggenerated
//     */
//    public Integer getMinMoney() {
//        return minMoney;
//    }
//
//    /**
//     * 字段: pay_set.min_money<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 最小额度
//     *
//     * @mbggenerated
//     */
//    public void setMinMoney(Integer minMoney) {
//        this.minMoney = minMoney;
//    }
//
//    /**
//     * @return pay_set.max_money: 最大额度
//     *
//     * @mbggenerated
//     */
//    public Integer getMaxMoney() {
//        return maxMoney;
//    }
//
//    /**
//     * 字段: pay_set.max_money<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明: 最大额度
//     *
//     * @mbggenerated
//     */
//    public void setMaxMoney(Integer maxMoney) {
//        this.maxMoney = maxMoney;
//    }
//
//    /**
//     * @return pay_set.is_start: 是否启用（0 启用 1 暂停）
//     *
//     * @mbggenerated
//     */
//    public Integer getIsStart() {
//        return isStart;
//    }
//
//    /**
//     * 字段: pay_set.is_start<br/>
//     * 必填: true<br/>
//     * 缺省: 0<br/>
//     * 长度: 10<br/>
//     * 说明: 是否启用（0 启用 1 暂停）
//     *
//     * @mbggenerated
//     */
//    public void setIsStart(Integer isStart) {
//        this.isStart = isStart;
//    }
//
//    /**
//     * @return pay_set.is_del: 是否删除（0 正常 1删除）
//     *
//     * @mbggenerated
//     */
//    public Integer getIsDel() {
//        return isDel;
//    }
//
//    /**
//     * 字段: pay_set.is_del<br/>
//     * 必填: true<br/>
//     * 缺省: 0<br/>
//     * 长度: 10<br/>
//     * 说明: 是否删除（0 正常 1删除）
//     *
//     * @mbggenerated
//     */
//    public void setIsDel(Integer isDel) {
//        this.isDel = isDel;
//    }
//
//    /**
//     * @return pay_set.pay_type: 渠道码
//     *
//     * @mbggenerated
//     */
//    public String getPayType() {
//        return payType;
//    }
//
//    /**
//     * 字段: pay_set.pay_type<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: 渠道码
//     *
//     * @mbggenerated
//     */
//    public void setPayType(String payType) {
//        this.payType = payType;
//    }
//
//    /**
//     * @return pay_set.create_time: 时间
//     *
//     * @mbggenerated
//     */
//    public Date getCreateTime() {
//        return createTime;
//    }
//
//    /**
//     * 字段: pay_set.create_time<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 19<br/>
//     * 说明: 时间
//     *
//     * @mbggenerated
//     */
//    public void setCreateTime(Date createTime) {
//        this.createTime = createTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table pay_set
//     *
//     * @mbggenerated
//     */
//    @Override
//    public boolean equals(Object that) {
//        if (this == that) {
//            return true;
//        }
//        if (that == null) {
//            return false;
//        }
//        if (getClass() != that.getClass()) {
//            return false;
//        }
//        PaySet other = (PaySet) that;
//        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
//            && (this.getPlatformId() == null ? other.getPlatformId() == null : this.getPlatformId().equals(other.getPlatformId()))
//            && (this.getWayId() == null ? other.getWayId() == null : this.getWayId().equals(other.getWayId()))
//            && (this.getMinMoney() == null ? other.getMinMoney() == null : this.getMinMoney().equals(other.getMinMoney()))
//            && (this.getMaxMoney() == null ? other.getMaxMoney() == null : this.getMaxMoney().equals(other.getMaxMoney()))
//            && (this.getIsStart() == null ? other.getIsStart() == null : this.getIsStart().equals(other.getIsStart()))
//            && (this.getIsDel() == null ? other.getIsDel() == null : this.getIsDel().equals(other.getIsDel()))
//            && (this.getPayType() == null ? other.getPayType() == null : this.getPayType().equals(other.getPayType()))
//            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table pay_set
//     *
//     * @mbggenerated
//     */
//    @Override
//    public int hashCode() {
//        final int prime = 31;
//        int result = 1;
//        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
//        result = prime * result + ((getPlatformId() == null) ? 0 : getPlatformId().hashCode());
//        result = prime * result + ((getWayId() == null) ? 0 : getWayId().hashCode());
//        result = prime * result + ((getMinMoney() == null) ? 0 : getMinMoney().hashCode());
//        result = prime * result + ((getMaxMoney() == null) ? 0 : getMaxMoney().hashCode());
//        result = prime * result + ((getIsStart() == null) ? 0 : getIsStart().hashCode());
//        result = prime * result + ((getIsDel() == null) ? 0 : getIsDel().hashCode());
//        result = prime * result + ((getPayType() == null) ? 0 : getPayType().hashCode());
//        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
//        return result;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table pay_set
//     *
//     * @mbggenerated
//     */
//    @Override
//    public String toString() {
//        StringBuilder sb = new StringBuilder();
//        sb.append(getClass().getSimpleName());
//        sb.append(" [");
//        sb.append("Hash = ").append(hashCode());
//        sb.append(", id=").append(id);
//        sb.append(", platformId=").append(platformId);
//        sb.append(", wayId=").append(wayId);
//        sb.append(", minMoney=").append(minMoney);
//        sb.append(", maxMoney=").append(maxMoney);
//        sb.append(", isStart=").append(isStart);
//        sb.append(", isDel=").append(isDel);
//        sb.append(", payType=").append(payType);
//        sb.append(", createTime=").append(createTime);
//        sb.append("]");
//        return sb.toString();
//    }
//}