//package com.likes.common.mybatis.entity;
//
//import java.io.Serializable;
//
//public class PayWay implements Serializable {
//    /**
//     * 字段: pay_way.id<br/>
//     * 主键: 自动增长<br/>
//     * 必填: true<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明:
//     *
//     * @mbggenerated
//     */
//    private Integer id;
//
//    /**
//     * 字段: pay_way.way_tag<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明:
//     *
//     * @mbggenerated
//     */
//    private String wayTag;
//
//    /**
//     * 字段: pay_way.picture<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: 图片
//     *
//     * @mbggenerated
//     */
//    private String picture;
//
//    /**
//     * 字段: pay_way.name<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: 名称
//     *
//     * @mbggenerated
//     */
//    private String name;
//
//    /**
//     * 字段: pay_way.is_del<br/>
//     * 必填: true<br/>
//     * 缺省: 0<br/>
//     * 长度: 10<br/>
//     * 说明: 是否删除（0 正常 1 删除）
//     *
//     * @mbggenerated
//     */
//    private Integer isDel;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database table pay_way
//     *
//     * @mbggenerated
//     */
//    private static final long serialVersionUID = 1L;
//
//    /**
//     * @return pay_way.id:
//     *
//     * @mbggenerated
//     */
//    public Integer getId() {
//        return id;
//    }
//
//    /**
//     * 字段: pay_way.id<br/>
//     * 主键: 自动增长<br/>
//     * 必填: true<br/>
//     * 缺省: <br/>
//     * 长度: 10<br/>
//     * 说明:
//     *
//     * @mbggenerated
//     */
//    public void setId(Integer id) {
//        this.id = id;
//    }
//
//    /**
//     * @return pay_way.way_tag:
//     *
//     * @mbggenerated
//     */
//    public String getWayTag() {
//        return wayTag;
//    }
//
//    /**
//     * 字段: pay_way.way_tag<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明:
//     *
//     * @mbggenerated
//     */
//    public void setWayTag(String wayTag) {
//        this.wayTag = wayTag;
//    }
//
//    /**
//     * @return pay_way.picture: 图片
//     *
//     * @mbggenerated
//     */
//    public String getPicture() {
//        return picture;
//    }
//
//    /**
//     * 字段: pay_way.picture<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: 图片
//     *
//     * @mbggenerated
//     */
//    public void setPicture(String picture) {
//        this.picture = picture;
//    }
//
//    /**
//     * @return pay_way.name: 名称
//     *
//     * @mbggenerated
//     */
//    public String getName() {
//        return name;
//    }
//
//    /**
//     * 字段: pay_way.name<br/>
//     * 必填: false<br/>
//     * 缺省: <br/>
//     * 长度: 255<br/>
//     * 说明: 名称
//     *
//     * @mbggenerated
//     */
//    public void setName(String name) {
//        this.name = name;
//    }
//
//    /**
//     * @return pay_way.is_del: 是否删除（0 正常 1 删除）
//     *
//     * @mbggenerated
//     */
//    public Integer getIsDel() {
//        return isDel;
//    }
//
//    /**
//     * 字段: pay_way.is_del<br/>
//     * 必填: true<br/>
//     * 缺省: 0<br/>
//     * 长度: 10<br/>
//     * 说明: 是否删除（0 正常 1 删除）
//     *
//     * @mbggenerated
//     */
//    public void setIsDel(Integer isDel) {
//        this.isDel = isDel;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table pay_way
//     *
//     * @mbggenerated
//     */
//    @Override
//    public boolean equals(Object that) {
//        if (this == that) {
//            return true;
//        }
//        if (that == null) {
//            return false;
//        }
//        if (getClass() != that.getClass()) {
//            return false;
//        }
//        PayWay other = (PayWay) that;
//        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
//            && (this.getWayTag() == null ? other.getWayTag() == null : this.getWayTag().equals(other.getWayTag()))
//            && (this.getPicture() == null ? other.getPicture() == null : this.getPicture().equals(other.getPicture()))
//            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
//            && (this.getIsDel() == null ? other.getIsDel() == null : this.getIsDel().equals(other.getIsDel()));
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table pay_way
//     *
//     * @mbggenerated
//     */
//    @Override
//    public int hashCode() {
//        final int prime = 31;
//        int result = 1;
//        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
//        result = prime * result + ((getWayTag() == null) ? 0 : getWayTag().hashCode());
//        result = prime * result + ((getPicture() == null) ? 0 : getPicture().hashCode());
//        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
//        result = prime * result + ((getIsDel() == null) ? 0 : getIsDel().hashCode());
//        return result;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table pay_way
//     *
//     * @mbggenerated
//     */
//    @Override
//    public String toString() {
//        StringBuilder sb = new StringBuilder();
//        sb.append(getClass().getSimpleName());
//        sb.append(" [");
//        sb.append("Hash = ").append(hashCode());
//        sb.append(", id=").append(id);
//        sb.append(", wayTag=").append(wayTag);
//        sb.append(", picture=").append(picture);
//        sb.append(", name=").append(name);
//        sb.append(", isDel=").append(isDel);
//        sb.append("]");
//        return sb.toString();
//    }
//}