package com.likes.common.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class SysFuncinterface implements Serializable {
    /**
     * 字段: sys_funcinterface.itfcid<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 接口id
     *
     * @mbggenerated
     */
    private Long itfcid;

    /**
     * 字段: sys_funcinterface.ofsystem<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 所属系统 live-manage live-app live
     *
     * @mbggenerated
     */
    private String ofsystem;

    /**
     * 字段: sys_funcinterface.itfcname<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 接口名称
     *
     * @mbggenerated
     */
    private String itfcname;

    /**
     * 字段: sys_funcinterface.itfcurl<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 200<br/>
     * 说明: 接口地址
     *
     * @mbggenerated
     */
    private String itfcurl;

    /**
     * 字段: sys_funcinterface.itfcdesc<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 接口说明
     *
     * @mbggenerated
     */
    private String itfcdesc;

    /**
     * 字段: sys_funcinterface.is_delete<br/>
     * 必填: true<br/>
     * 缺省: b'0'<br/>
     * 长度: 1<br/>
     * 说明: 是否删除
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * 字段: sys_funcinterface.create_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 创建人
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * 字段: sys_funcinterface.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 字段: sys_funcinterface.update_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 最后修改人
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * 字段: sys_funcinterface.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_funcinterface
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return sys_funcinterface.itfcid: 接口id
     *
     * @mbggenerated
     */
    public Long getItfcid() {
        return itfcid;
    }

    /**
     * 字段: sys_funcinterface.itfcid<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 接口id
     *
     * @mbggenerated
     */
    public void setItfcid(Long itfcid) {
        this.itfcid = itfcid;
    }

    /**
     * @return sys_funcinterface.ofsystem: 所属系统 live-manage live-app live
     *
     * @mbggenerated
     */
    public String getOfsystem() {
        return ofsystem;
    }

    /**
     * 字段: sys_funcinterface.ofsystem<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 所属系统 live-manage live-app live
     *
     * @mbggenerated
     */
    public void setOfsystem(String ofsystem) {
        this.ofsystem = ofsystem;
    }

    /**
     * @return sys_funcinterface.itfcname: 接口名称
     *
     * @mbggenerated
     */
    public String getItfcname() {
        return itfcname;
    }

    /**
     * 字段: sys_funcinterface.itfcname<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 接口名称
     *
     * @mbggenerated
     */
    public void setItfcname(String itfcname) {
        this.itfcname = itfcname;
    }

    /**
     * @return sys_funcinterface.itfcurl: 接口地址
     *
     * @mbggenerated
     */
    public String getItfcurl() {
        return itfcurl;
    }

    /**
     * 字段: sys_funcinterface.itfcurl<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 200<br/>
     * 说明: 接口地址
     *
     * @mbggenerated
     */
    public void setItfcurl(String itfcurl) {
        this.itfcurl = itfcurl;
    }

    /**
     * @return sys_funcinterface.itfcdesc: 接口说明
     *
     * @mbggenerated
     */
    public String getItfcdesc() {
        return itfcdesc;
    }

    /**
     * 字段: sys_funcinterface.itfcdesc<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 接口说明
     *
     * @mbggenerated
     */
    public void setItfcdesc(String itfcdesc) {
        this.itfcdesc = itfcdesc;
    }

    /**
     * @return sys_funcinterface.is_delete: 是否删除
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * 字段: sys_funcinterface.is_delete<br/>
     * 必填: true<br/>
     * 缺省: b'0'<br/>
     * 长度: 1<br/>
     * 说明: 是否删除
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * @return sys_funcinterface.create_user: 创建人
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * 字段: sys_funcinterface.create_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 创建人
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * @return sys_funcinterface.create_time: 创建时间
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 字段: sys_funcinterface.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return sys_funcinterface.update_user: 最后修改人
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * 字段: sys_funcinterface.update_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 最后修改人
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * @return sys_funcinterface.update_time: 更新时间
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 字段: sys_funcinterface.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_funcinterface
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysFuncinterface other = (SysFuncinterface) that;
        return (this.getItfcid() == null ? other.getItfcid() == null : this.getItfcid().equals(other.getItfcid()))
            && (this.getOfsystem() == null ? other.getOfsystem() == null : this.getOfsystem().equals(other.getOfsystem()))
            && (this.getItfcname() == null ? other.getItfcname() == null : this.getItfcname().equals(other.getItfcname()))
            && (this.getItfcurl() == null ? other.getItfcurl() == null : this.getItfcurl().equals(other.getItfcurl()))
            && (this.getItfcdesc() == null ? other.getItfcdesc() == null : this.getItfcdesc().equals(other.getItfcdesc()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_funcinterface
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getItfcid() == null) ? 0 : getItfcid().hashCode());
        result = prime * result + ((getOfsystem() == null) ? 0 : getOfsystem().hashCode());
        result = prime * result + ((getItfcname() == null) ? 0 : getItfcname().hashCode());
        result = prime * result + ((getItfcurl() == null) ? 0 : getItfcurl().hashCode());
        result = prime * result + ((getItfcdesc() == null) ? 0 : getItfcdesc().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_funcinterface
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", itfcid=").append(itfcid);
        sb.append(", ofsystem=").append(ofsystem);
        sb.append(", itfcname=").append(itfcname);
        sb.append(", itfcurl=").append(itfcurl);
        sb.append(", itfcdesc=").append(itfcdesc);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}