package com.likes.common.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class SysInfolog implements Serializable {
    /**
     * 字段: sys_infolog.logid<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 日志id
     *
     * @mbggenerated
     */
    private Long logid;

    /**
     * 字段: sys_infolog.accno<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 操作用户
     *
     * @mbggenerated
     */
    private String accno;

    /**
     * 字段: sys_infolog.systemname<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 系统代码：来源系统代码
     *
     * @mbggenerated
     */
    private String systemname;

    /**
     * 字段: sys_infolog.modelname<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 模块名称
     *
     * @mbggenerated
     */
    private String modelname;

    /**
     * 字段: sys_infolog.optcontent<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1000<br/>
     * 说明: 日志内容
     *
     * @mbggenerated
     */
    private String optcontent;

    /**
     * 字段: sys_infolog.optip<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 操作客户端ip
     *
     * @mbggenerated
     */
    private String optip;

    /**
     * 字段: sys_infolog.serverip<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 当前服务器ip
     *
     * @mbggenerated
     */
    private String serverip;

    /**
     * 字段: sys_infolog.longitude<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 经度
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * 字段: sys_infolog.latitude<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 纬度
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * 字段: sys_infolog.orginfo<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 400<br/>
     * 说明: 来源信息
     *
     * @mbggenerated
     */
    private String orginfo;

    /**
     * 字段: sys_infolog.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_infolog
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return sys_infolog.logid: 日志id
     *
     * @mbggenerated
     */
    public Long getLogid() {
        return logid;
    }

    /**
     * 字段: sys_infolog.logid<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 日志id
     *
     * @mbggenerated
     */
    public void setLogid(Long logid) {
        this.logid = logid;
    }

    /**
     * @return sys_infolog.accno: 操作用户
     *
     * @mbggenerated
     */
    public String getAccno() {
        return accno;
    }

    /**
     * 字段: sys_infolog.accno<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 操作用户
     *
     * @mbggenerated
     */
    public void setAccno(String accno) {
        this.accno = accno;
    }

    /**
     * @return sys_infolog.systemname: 系统代码：来源系统代码
     *
     * @mbggenerated
     */
    public String getSystemname() {
        return systemname;
    }

    /**
     * 字段: sys_infolog.systemname<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 系统代码：来源系统代码
     *
     * @mbggenerated
     */
    public void setSystemname(String systemname) {
        this.systemname = systemname;
    }

    /**
     * @return sys_infolog.modelname: 模块名称
     *
     * @mbggenerated
     */
    public String getModelname() {
        return modelname;
    }

    /**
     * 字段: sys_infolog.modelname<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 模块名称
     *
     * @mbggenerated
     */
    public void setModelname(String modelname) {
        this.modelname = modelname;
    }

    /**
     * @return sys_infolog.optcontent: 日志内容
     *
     * @mbggenerated
     */
    public String getOptcontent() {
        return optcontent;
    }

    /**
     * 字段: sys_infolog.optcontent<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1000<br/>
     * 说明: 日志内容
     *
     * @mbggenerated
     */
    public void setOptcontent(String optcontent) {
        this.optcontent = optcontent;
    }

    /**
     * @return sys_infolog.optip: 操作客户端ip
     *
     * @mbggenerated
     */
    public String getOptip() {
        return optip;
    }

    /**
     * 字段: sys_infolog.optip<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 操作客户端ip
     *
     * @mbggenerated
     */
    public void setOptip(String optip) {
        this.optip = optip;
    }

    /**
     * @return sys_infolog.serverip: 当前服务器ip
     *
     * @mbggenerated
     */
    public String getServerip() {
        return serverip;
    }

    /**
     * 字段: sys_infolog.serverip<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 当前服务器ip
     *
     * @mbggenerated
     */
    public void setServerip(String serverip) {
        this.serverip = serverip;
    }

    /**
     * @return sys_infolog.longitude: 经度
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * 字段: sys_infolog.longitude<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 经度
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * @return sys_infolog.latitude: 纬度
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * 字段: sys_infolog.latitude<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 纬度
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * @return sys_infolog.orginfo: 来源信息
     *
     * @mbggenerated
     */
    public String getOrginfo() {
        return orginfo;
    }

    /**
     * 字段: sys_infolog.orginfo<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 400<br/>
     * 说明: 来源信息
     *
     * @mbggenerated
     */
    public void setOrginfo(String orginfo) {
        this.orginfo = orginfo;
    }

    /**
     * @return sys_infolog.create_time: 创建时间
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 字段: sys_infolog.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_infolog
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysInfolog other = (SysInfolog) that;
        return (this.getLogid() == null ? other.getLogid() == null : this.getLogid().equals(other.getLogid()))
            && (this.getAccno() == null ? other.getAccno() == null : this.getAccno().equals(other.getAccno()))
            && (this.getSystemname() == null ? other.getSystemname() == null : this.getSystemname().equals(other.getSystemname()))
            && (this.getModelname() == null ? other.getModelname() == null : this.getModelname().equals(other.getModelname()))
            && (this.getOptcontent() == null ? other.getOptcontent() == null : this.getOptcontent().equals(other.getOptcontent()))
            && (this.getOptip() == null ? other.getOptip() == null : this.getOptip().equals(other.getOptip()))
            && (this.getServerip() == null ? other.getServerip() == null : this.getServerip().equals(other.getServerip()))
            && (this.getLongitude() == null ? other.getLongitude() == null : this.getLongitude().equals(other.getLongitude()))
            && (this.getLatitude() == null ? other.getLatitude() == null : this.getLatitude().equals(other.getLatitude()))
            && (this.getOrginfo() == null ? other.getOrginfo() == null : this.getOrginfo().equals(other.getOrginfo()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_infolog
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLogid() == null) ? 0 : getLogid().hashCode());
        result = prime * result + ((getAccno() == null) ? 0 : getAccno().hashCode());
        result = prime * result + ((getSystemname() == null) ? 0 : getSystemname().hashCode());
        result = prime * result + ((getModelname() == null) ? 0 : getModelname().hashCode());
        result = prime * result + ((getOptcontent() == null) ? 0 : getOptcontent().hashCode());
        result = prime * result + ((getOptip() == null) ? 0 : getOptip().hashCode());
        result = prime * result + ((getServerip() == null) ? 0 : getServerip().hashCode());
        result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
        result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
        result = prime * result + ((getOrginfo() == null) ? 0 : getOrginfo().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_infolog
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logid=").append(logid);
        sb.append(", accno=").append(accno);
        sb.append(", systemname=").append(systemname);
        sb.append(", modelname=").append(modelname);
        sb.append(", optcontent=").append(optcontent);
        sb.append(", optip=").append(optip);
        sb.append(", serverip=").append(serverip);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", orginfo=").append(orginfo);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}