package com.likes.common.mybatis.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysParameterExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    protected Integer limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public SysParameterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        offset = null;
        limit = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public Integer getLimit() {
        return this.limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public SysParameterExample bound(Integer offset, Integer limit) {
        this.offset = offset;
        this.limit = limit;
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysparamidIsNull() {
            addCriterion("sysparamid is null");
            return (Criteria) this;
        }

        public Criteria andSysparamidIsNotNull() {
            addCriterion("sysparamid is not null");
            return (Criteria) this;
        }

        public Criteria andSysparamidEqualTo(Long value) {
            addCriterion("sysparamid =", value, "sysparamid");
            return (Criteria) this;
        }

        public Criteria andSysparamidNotEqualTo(Long value) {
            addCriterion("sysparamid <>", value, "sysparamid");
            return (Criteria) this;
        }

        public Criteria andSysparamidGreaterThan(Long value) {
            addCriterion("sysparamid >", value, "sysparamid");
            return (Criteria) this;
        }

        public Criteria andSysparamidGreaterThanOrEqualTo(Long value) {
            addCriterion("sysparamid >=", value, "sysparamid");
            return (Criteria) this;
        }

        public Criteria andSysparamidLessThan(Long value) {
            addCriterion("sysparamid <", value, "sysparamid");
            return (Criteria) this;
        }

        public Criteria andSysparamidLessThanOrEqualTo(Long value) {
            addCriterion("sysparamid <=", value, "sysparamid");
            return (Criteria) this;
        }

        public Criteria andSysparamidIn(List<Long> values) {
            addCriterion("sysparamid in", values, "sysparamid");
            return (Criteria) this;
        }

        public Criteria andSysparamidNotIn(List<Long> values) {
            addCriterion("sysparamid not in", values, "sysparamid");
            return (Criteria) this;
        }

        public Criteria andSysparamidBetween(Long value1, Long value2) {
            addCriterion("sysparamid between", value1, value2, "sysparamid");
            return (Criteria) this;
        }

        public Criteria andSysparamidNotBetween(Long value1, Long value2) {
            addCriterion("sysparamid not between", value1, value2, "sysparamid");
            return (Criteria) this;
        }

        public Criteria andSysparamcodeIsNull() {
            addCriterion("sysparamcode is null");
            return (Criteria) this;
        }

        public Criteria andSysparamcodeIsNotNull() {
            addCriterion("sysparamcode is not null");
            return (Criteria) this;
        }

        public Criteria andSysparamcodeEqualTo(String value) {
            addCriterion("sysparamcode =", value, "sysparamcode");
            return (Criteria) this;
        }

        public Criteria andSysparamcodeNotEqualTo(String value) {
            addCriterion("sysparamcode <>", value, "sysparamcode");
            return (Criteria) this;
        }

        public Criteria andSysparamcodeGreaterThan(String value) {
            addCriterion("sysparamcode >", value, "sysparamcode");
            return (Criteria) this;
        }

        public Criteria andSysparamcodeGreaterThanOrEqualTo(String value) {
            addCriterion("sysparamcode >=", value, "sysparamcode");
            return (Criteria) this;
        }

        public Criteria andSysparamcodeLessThan(String value) {
            addCriterion("sysparamcode <", value, "sysparamcode");
            return (Criteria) this;
        }

        public Criteria andSysparamcodeLessThanOrEqualTo(String value) {
            addCriterion("sysparamcode <=", value, "sysparamcode");
            return (Criteria) this;
        }

        public Criteria andSysparamcodeLike(String value) {
            addCriterion("sysparamcode like", value, "sysparamcode");
            return (Criteria) this;
        }

        public Criteria andSysparamcodeNotLike(String value) {
            addCriterion("sysparamcode not like", value, "sysparamcode");
            return (Criteria) this;
        }

        public Criteria andSysparamcodeIn(List<String> values) {
            addCriterion("sysparamcode in", values, "sysparamcode");
            return (Criteria) this;
        }

        public Criteria andSysparamcodeNotIn(List<String> values) {
            addCriterion("sysparamcode not in", values, "sysparamcode");
            return (Criteria) this;
        }

        public Criteria andSysparamcodeBetween(String value1, String value2) {
            addCriterion("sysparamcode between", value1, value2, "sysparamcode");
            return (Criteria) this;
        }

        public Criteria andSysparamcodeNotBetween(String value1, String value2) {
            addCriterion("sysparamcode not between", value1, value2, "sysparamcode");
            return (Criteria) this;
        }

        public Criteria andSysparamnameIsNull() {
            addCriterion("sysparamname is null");
            return (Criteria) this;
        }

        public Criteria andSysparamnameIsNotNull() {
            addCriterion("sysparamname is not null");
            return (Criteria) this;
        }

        public Criteria andSysparamnameEqualTo(String value) {
            addCriterion("sysparamname =", value, "sysparamname");
            return (Criteria) this;
        }

        public Criteria andSysparamnameNotEqualTo(String value) {
            addCriterion("sysparamname <>", value, "sysparamname");
            return (Criteria) this;
        }

        public Criteria andSysparamnameGreaterThan(String value) {
            addCriterion("sysparamname >", value, "sysparamname");
            return (Criteria) this;
        }

        public Criteria andSysparamnameGreaterThanOrEqualTo(String value) {
            addCriterion("sysparamname >=", value, "sysparamname");
            return (Criteria) this;
        }

        public Criteria andSysparamnameLessThan(String value) {
            addCriterion("sysparamname <", value, "sysparamname");
            return (Criteria) this;
        }

        public Criteria andSysparamnameLessThanOrEqualTo(String value) {
            addCriterion("sysparamname <=", value, "sysparamname");
            return (Criteria) this;
        }

        public Criteria andSysparamnameLike(String value) {
            addCriterion("sysparamname like", value, "sysparamname");
            return (Criteria) this;
        }

        public Criteria andSysparamnameNotLike(String value) {
            addCriterion("sysparamname not like", value, "sysparamname");
            return (Criteria) this;
        }

        public Criteria andSysparamnameIn(List<String> values) {
            addCriterion("sysparamname in", values, "sysparamname");
            return (Criteria) this;
        }

        public Criteria andSysparamnameNotIn(List<String> values) {
            addCriterion("sysparamname not in", values, "sysparamname");
            return (Criteria) this;
        }

        public Criteria andSysparamnameBetween(String value1, String value2) {
            addCriterion("sysparamname between", value1, value2, "sysparamname");
            return (Criteria) this;
        }

        public Criteria andSysparamnameNotBetween(String value1, String value2) {
            addCriterion("sysparamname not between", value1, value2, "sysparamname");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andSysparamvalueIsNull() {
            addCriterion("sysparamvalue is null");
            return (Criteria) this;
        }

        public Criteria andSysparamvalueIsNotNull() {
            addCriterion("sysparamvalue is not null");
            return (Criteria) this;
        }

        public Criteria andSysparamvalueEqualTo(String value) {
            addCriterion("sysparamvalue =", value, "sysparamvalue");
            return (Criteria) this;
        }

        public Criteria andSysparamvalueNotEqualTo(String value) {
            addCriterion("sysparamvalue <>", value, "sysparamvalue");
            return (Criteria) this;
        }

        public Criteria andSysparamvalueGreaterThan(String value) {
            addCriterion("sysparamvalue >", value, "sysparamvalue");
            return (Criteria) this;
        }

        public Criteria andSysparamvalueGreaterThanOrEqualTo(String value) {
            addCriterion("sysparamvalue >=", value, "sysparamvalue");
            return (Criteria) this;
        }

        public Criteria andSysparamvalueLessThan(String value) {
            addCriterion("sysparamvalue <", value, "sysparamvalue");
            return (Criteria) this;
        }

        public Criteria andSysparamvalueLessThanOrEqualTo(String value) {
            addCriterion("sysparamvalue <=", value, "sysparamvalue");
            return (Criteria) this;
        }

        public Criteria andSysparamvalueLike(String value) {
            addCriterion("sysparamvalue like", value, "sysparamvalue");
            return (Criteria) this;
        }

        public Criteria andSysparamvalueNotLike(String value) {
            addCriterion("sysparamvalue not like", value, "sysparamvalue");
            return (Criteria) this;
        }

        public Criteria andSysparamvalueIn(List<String> values) {
            addCriterion("sysparamvalue in", values, "sysparamvalue");
            return (Criteria) this;
        }

        public Criteria andSysparamvalueNotIn(List<String> values) {
            addCriterion("sysparamvalue not in", values, "sysparamvalue");
            return (Criteria) this;
        }

        public Criteria andSysparamvalueBetween(String value1, String value2) {
            addCriterion("sysparamvalue between", value1, value2, "sysparamvalue");
            return (Criteria) this;
        }

        public Criteria andSysparamvalueNotBetween(String value1, String value2) {
            addCriterion("sysparamvalue not between", value1, value2, "sysparamvalue");
            return (Criteria) this;
        }

        public Criteria andSortbyIsNull() {
            addCriterion("sortby is null");
            return (Criteria) this;
        }

        public Criteria andSortbyIsNotNull() {
            addCriterion("sortby is not null");
            return (Criteria) this;
        }

        public Criteria andSortbyEqualTo(Integer value) {
            addCriterion("sortby =", value, "sortby");
            return (Criteria) this;
        }

        public Criteria andSortbyNotEqualTo(Integer value) {
            addCriterion("sortby <>", value, "sortby");
            return (Criteria) this;
        }

        public Criteria andSortbyGreaterThan(Integer value) {
            addCriterion("sortby >", value, "sortby");
            return (Criteria) this;
        }

        public Criteria andSortbyGreaterThanOrEqualTo(Integer value) {
            addCriterion("sortby >=", value, "sortby");
            return (Criteria) this;
        }

        public Criteria andSortbyLessThan(Integer value) {
            addCriterion("sortby <", value, "sortby");
            return (Criteria) this;
        }

        public Criteria andSortbyLessThanOrEqualTo(Integer value) {
            addCriterion("sortby <=", value, "sortby");
            return (Criteria) this;
        }

        public Criteria andSortbyIn(List<Integer> values) {
            addCriterion("sortby in", values, "sortby");
            return (Criteria) this;
        }

        public Criteria andSortbyNotIn(List<Integer> values) {
            addCriterion("sortby not in", values, "sortby");
            return (Criteria) this;
        }

        public Criteria andSortbyBetween(Integer value1, Integer value2) {
            addCriterion("sortby between", value1, value2, "sortby");
            return (Criteria) this;
        }

        public Criteria andSortbyNotBetween(Integer value1, Integer value2) {
            addCriterion("sortby not between", value1, value2, "sortby");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Boolean value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Boolean value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Boolean value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Boolean value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Boolean> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Boolean> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_parameter
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_parameter
     *
     * @mbggenerated
     */
    public static class Criterion implements Serializable {
        private final String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private final String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
