package com.likes.common.mybatis.entity;

import java.io.Serializable;

public class SysReffuncinitfcKey implements Serializable {
    /**
     * 字段: sys_reffuncinitfc.itfcid<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 接口id
     *
     * @mbggenerated
     */
    private Long itfcid;

    /**
     * 字段: sys_reffuncinitfc.sfunid<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 功能id
     *
     * @mbggenerated
     */
    private Long sfunid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_reffuncinitfc
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return sys_reffuncinitfc.itfcid: 接口id
     *
     * @mbggenerated
     */
    public Long getItfcid() {
        return itfcid;
    }

    /**
     * 字段: sys_reffuncinitfc.itfcid<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 接口id
     *
     * @mbggenerated
     */
    public void setItfcid(Long itfcid) {
        this.itfcid = itfcid;
    }

    /**
     * @return sys_reffuncinitfc.sfunid: 功能id
     *
     * @mbggenerated
     */
    public Long getSfunid() {
        return sfunid;
    }

    /**
     * 字段: sys_reffuncinitfc.sfunid<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 功能id
     *
     * @mbggenerated
     */
    public void setSfunid(Long sfunid) {
        this.sfunid = sfunid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_reffuncinitfc
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysReffuncinitfcKey other = (SysReffuncinitfcKey) that;
        return (this.getItfcid() == null ? other.getItfcid() == null : this.getItfcid().equals(other.getItfcid()))
            && (this.getSfunid() == null ? other.getSfunid() == null : this.getSfunid().equals(other.getSfunid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_reffuncinitfc
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getItfcid() == null) ? 0 : getItfcid().hashCode());
        result = prime * result + ((getSfunid() == null) ? 0 : getSfunid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_reffuncinitfc
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", itfcid=").append(itfcid);
        sb.append(", sfunid=").append(sfunid);
        sb.append("]");
        return sb.toString();
    }
}