package com.likes.common.mybatis.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class SysRoleinfoExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    protected Integer limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public SysRoleinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        offset = null;
        limit = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public Integer getLimit() {
        return this.limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public SysRoleinfoExample bound(Integer offset, Integer limit) {
        this.offset = offset;
        this.limit = limit;
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysroleidIsNull() {
            addCriterion("sysroleid is null");
            return (Criteria) this;
        }

        public Criteria andSysroleidIsNotNull() {
            addCriterion("sysroleid is not null");
            return (Criteria) this;
        }

        public Criteria andSysroleidEqualTo(Long value) {
            addCriterion("sysroleid =", value, "sysroleid");
            return (Criteria) this;
        }

        public Criteria andSysroleidNotEqualTo(Long value) {
            addCriterion("sysroleid <>", value, "sysroleid");
            return (Criteria) this;
        }

        public Criteria andSysroleidGreaterThan(Long value) {
            addCriterion("sysroleid >", value, "sysroleid");
            return (Criteria) this;
        }

        public Criteria andSysroleidGreaterThanOrEqualTo(Long value) {
            addCriterion("sysroleid >=", value, "sysroleid");
            return (Criteria) this;
        }

        public Criteria andSysroleidLessThan(Long value) {
            addCriterion("sysroleid <", value, "sysroleid");
            return (Criteria) this;
        }

        public Criteria andSysroleidLessThanOrEqualTo(Long value) {
            addCriterion("sysroleid <=", value, "sysroleid");
            return (Criteria) this;
        }

        public Criteria andSysroleidIn(List<Long> values) {
            addCriterion("sysroleid in", values, "sysroleid");
            return (Criteria) this;
        }

        public Criteria andSysroleidNotIn(List<Long> values) {
            addCriterion("sysroleid not in", values, "sysroleid");
            return (Criteria) this;
        }

        public Criteria andSysroleidBetween(Long value1, Long value2) {
            addCriterion("sysroleid between", value1, value2, "sysroleid");
            return (Criteria) this;
        }

        public Criteria andSysroleidNotBetween(Long value1, Long value2) {
            addCriterion("sysroleid not between", value1, value2, "sysroleid");
            return (Criteria) this;
        }

        public Criteria andSysrolenameIsNull() {
            addCriterion("sysrolename is null");
            return (Criteria) this;
        }

        public Criteria andSysrolenameIsNotNull() {
            addCriterion("sysrolename is not null");
            return (Criteria) this;
        }

        public Criteria andSysrolenameEqualTo(String value) {
            addCriterion("sysrolename =", value, "sysrolename");
            return (Criteria) this;
        }

        public Criteria andSysrolenameNotEqualTo(String value) {
            addCriterion("sysrolename <>", value, "sysrolename");
            return (Criteria) this;
        }

        public Criteria andSysrolenameGreaterThan(String value) {
            addCriterion("sysrolename >", value, "sysrolename");
            return (Criteria) this;
        }

        public Criteria andSysrolenameGreaterThanOrEqualTo(String value) {
            addCriterion("sysrolename >=", value, "sysrolename");
            return (Criteria) this;
        }

        public Criteria andSysrolenameLessThan(String value) {
            addCriterion("sysrolename <", value, "sysrolename");
            return (Criteria) this;
        }

        public Criteria andSysrolenameLessThanOrEqualTo(String value) {
            addCriterion("sysrolename <=", value, "sysrolename");
            return (Criteria) this;
        }

        public Criteria andSysrolenameLike(String value) {
            addCriterion("sysrolename like", value, "sysrolename");
            return (Criteria) this;
        }

        public Criteria andSysrolenameNotLike(String value) {
            addCriterion("sysrolename not like", value, "sysrolename");
            return (Criteria) this;
        }

        public Criteria andSysrolenameIn(List<String> values) {
            addCriterion("sysrolename in", values, "sysrolename");
            return (Criteria) this;
        }

        public Criteria andSysrolenameNotIn(List<String> values) {
            addCriterion("sysrolename not in", values, "sysrolename");
            return (Criteria) this;
        }

        public Criteria andSysrolenameBetween(String value1, String value2) {
            addCriterion("sysrolename between", value1, value2, "sysrolename");
            return (Criteria) this;
        }

        public Criteria andSysrolenameNotBetween(String value1, String value2) {
            addCriterion("sysrolename not between", value1, value2, "sysrolename");
            return (Criteria) this;
        }

        public Criteria andSysrolestatusIsNull() {
            addCriterion("sysrolestatus is null");
            return (Criteria) this;
        }

        public Criteria andSysrolestatusIsNotNull() {
            addCriterion("sysrolestatus is not null");
            return (Criteria) this;
        }

        public Criteria andSysrolestatusEqualTo(Integer value) {
            addCriterion("sysrolestatus =", value, "sysrolestatus");
            return (Criteria) this;
        }

        public Criteria andSysrolestatusNotEqualTo(Integer value) {
            addCriterion("sysrolestatus <>", value, "sysrolestatus");
            return (Criteria) this;
        }

        public Criteria andSysrolestatusGreaterThan(Integer value) {
            addCriterion("sysrolestatus >", value, "sysrolestatus");
            return (Criteria) this;
        }

        public Criteria andSysrolestatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("sysrolestatus >=", value, "sysrolestatus");
            return (Criteria) this;
        }

        public Criteria andSysrolestatusLessThan(Integer value) {
            addCriterion("sysrolestatus <", value, "sysrolestatus");
            return (Criteria) this;
        }

        public Criteria andSysrolestatusLessThanOrEqualTo(Integer value) {
            addCriterion("sysrolestatus <=", value, "sysrolestatus");
            return (Criteria) this;
        }

        public Criteria andSysrolestatusIn(List<Integer> values) {
            addCriterion("sysrolestatus in", values, "sysrolestatus");
            return (Criteria) this;
        }

        public Criteria andSysrolestatusNotIn(List<Integer> values) {
            addCriterion("sysrolestatus not in", values, "sysrolestatus");
            return (Criteria) this;
        }

        public Criteria andSysrolestatusBetween(Integer value1, Integer value2) {
            addCriterion("sysrolestatus between", value1, value2, "sysrolestatus");
            return (Criteria) this;
        }

        public Criteria andSysrolestatusNotBetween(Integer value1, Integer value2) {
            addCriterion("sysrolestatus not between", value1, value2, "sysrolestatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_roleinfo
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_roleinfo
     *
     * @mbggenerated
     */
    public static class Criterion implements Serializable {
        private final String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private final String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
