package com.likes.common.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class ThirdPrivateChatGroup implements Serializable {
    /**
     * 字段: third_private_chat_group.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 主键id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 字段: third_private_chat_group.admin_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 管理员账号
     *
     * @mbggenerated
     */
    private String adminName;

    /**
     * 字段: third_private_chat_group.chat_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 群名称
     *
     * @mbggenerated
     */
    private String chatName;

    /**
     * 字段: third_private_chat_group.sort<br/>
     * 必填: false<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 排序号
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * 字段: third_private_chat_group.is_work<br/>
     * 必填: false<br/>
     * 缺省: b'1'<br/>
     * 长度: 1<br/>
     * 说明: 是否启用(0:禁用;1:启用)
     *
     * @mbggenerated
     */
    private Boolean isWork;

    /**
     * 字段: third_private_chat_group.head<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 头像
     *
     * @mbggenerated
     */
    private String head;

    /**
     * 字段: third_private_chat_group.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 字段: third_private_chat_group.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table third_private_chat_group
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return third_private_chat_group.id: 主键id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 字段: third_private_chat_group.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 主键id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return third_private_chat_group.admin_name: 管理员账号
     *
     * @mbggenerated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * 字段: third_private_chat_group.admin_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 管理员账号
     *
     * @mbggenerated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    /**
     * @return third_private_chat_group.chat_name: 群名称
     *
     * @mbggenerated
     */
    public String getChatName() {
        return chatName;
    }

    /**
     * 字段: third_private_chat_group.chat_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 群名称
     *
     * @mbggenerated
     */
    public void setChatName(String chatName) {
        this.chatName = chatName;
    }

    /**
     * @return third_private_chat_group.sort: 排序号
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * 字段: third_private_chat_group.sort<br/>
     * 必填: false<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 排序号
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * @return third_private_chat_group.is_work: 是否启用(0:禁用;1:启用)
     *
     * @mbggenerated
     */
    public Boolean getIsWork() {
        return isWork;
    }

    /**
     * 字段: third_private_chat_group.is_work<br/>
     * 必填: false<br/>
     * 缺省: b'1'<br/>
     * 长度: 1<br/>
     * 说明: 是否启用(0:禁用;1:启用)
     *
     * @mbggenerated
     */
    public void setIsWork(Boolean isWork) {
        this.isWork = isWork;
    }

    /**
     * @return third_private_chat_group.head: 头像
     *
     * @mbggenerated
     */
    public String getHead() {
        return head;
    }

    /**
     * 字段: third_private_chat_group.head<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 头像
     *
     * @mbggenerated
     */
    public void setHead(String head) {
        this.head = head;
    }

    /**
     * @return third_private_chat_group.create_time: 创建时间
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 字段: third_private_chat_group.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return third_private_chat_group.update_time: 更新时间
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 字段: third_private_chat_group.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_private_chat_group
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ThirdPrivateChatGroup other = (ThirdPrivateChatGroup) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getAdminName() == null ? other.getAdminName() == null : this.getAdminName().equals(other.getAdminName()))
                && (this.getChatName() == null ? other.getChatName() == null : this.getChatName().equals(other.getChatName()))
                && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
                && (this.getIsWork() == null ? other.getIsWork() == null : this.getIsWork().equals(other.getIsWork()))
                && (this.getHead() == null ? other.getHead() == null : this.getHead().equals(other.getHead()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_private_chat_group
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAdminName() == null) ? 0 : getAdminName().hashCode());
        result = prime * result + ((getChatName() == null) ? 0 : getChatName().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getIsWork() == null) ? 0 : getIsWork().hashCode());
        result = prime * result + ((getHead() == null) ? 0 : getHead().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_private_chat_group
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", adminName=").append(adminName);
        sb.append(", chatName=").append(chatName);
        sb.append(", sort=").append(sort);
        sb.append(", isWork=").append(isWork);
        sb.append(", head=").append(head);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}