package com.likes.common.mybatis.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TraApplycash implements Serializable {
    /**
     * 字段: tra_applycash.apycid<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 提现申请id
     *
     * @mbggenerated
     */
    private Long apycid;

    /**
     * 字段: tra_applycash.bankaccid<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 银行账户id
     *
     * @mbggenerated
     */
    private Long bankaccid;

    /**
     * 字段: tra_applycash.orderid<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 订单id
     *
     * @mbggenerated
     */
    private Long orderid;

    /**
     * 字段: tra_applycash.accno<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 会员标识号
     *
     * @mbggenerated
     */
    private String accno;

    /**
     * 字段: tra_applycash.apycdate<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 申请时间
     *
     * @mbggenerated
     */
    private Date apycdate;

    /**
     * 字段: tra_applycash.apycgold<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 16<br/>
     * 说明: 申请总金额
     *
     * @mbggenerated
     */
    private BigDecimal apycgold;

    /**
     * 字段: tra_applycash.apycamt<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 16<br/>
     * 说明: 打款金额
     *
     * @mbggenerated
     */
    private BigDecimal apycamt;

    /**
     * 字段: tra_applycash.apycstatus<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1<br/>
     * 说明: 申请状态  1提交申请  2提现处理中  4已打款    8已到账  9已取消
     *
     * @mbggenerated
     */
    private Integer apycstatus;

    /**
     * 字段: tra_applycash.paymemname<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 打款人
     *
     * @mbggenerated
     */
    private String paymemname;

    /**
     * 字段: tra_applycash.paydate<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 支付时间
     *
     * @mbggenerated
     */
    private Date paydate;

    /**
     * 字段: tra_applycash.is_delete<br/>
     * 必填: true<br/>
     * 缺省: b'0'<br/>
     * 长度: 1<br/>
     * 说明: 是否删除
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * 字段: tra_applycash.create_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 创建人
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * 字段: tra_applycash.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 字段: tra_applycash.update_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 最后修改人
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * 字段: tra_applycash.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 字段: tra_applycash.damaliang<br/>
     * 必填: false<br/>
     * 缺省: 0.000<br/>
     * 长度: 16<br/>
     * 说明: 打码量
     *
     * @mbggenerated
     */
    private BigDecimal damaliang;

    /**
     * 字段: tra_applycash.xingzhengfei<br/>
     * 必填: false<br/>
     * 缺省: 0.000<br/>
     * 长度: 16<br/>
     * 说明: 行政费
     *
     * @mbggenerated
     */
    private BigDecimal xingzhengfei;

    /**
     * 字段: tra_applycash.bet_amount<br/>
     * 必填: false<br/>
     * 缺省: 0.000<br/>
     * 长度: 16<br/>
     * 说明: 投注金额充值金额
     *
     * @mbggenerated
     */
    private BigDecimal betAmount;

    /**
     * 字段: tra_applycash.no_withdrawal_amount<br/>
     * 必填: false<br/>
     * 缺省: 0.000<br/>
     * 长度: 16<br/>
     * 说明: 当前所需打码量
     *
     * @mbggenerated
     */
    private BigDecimal noWithdrawalAmount;

    /**
     * 字段: tra_applycash.payimg<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 128<br/>
     * 说明: 支付凭证截图 多张以“，”分隔
     *
     * @mbggenerated
     */
    private String payimg;

    /**
     * 字段: tra_applycash.ordertype<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 2<br/>
     * 说明: 提现类型，12投注分成，13礼物分成
     *
     * @mbggenerated
     */
    private Integer ordertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tra_applycash
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return tra_applycash.apycid: 提现申请id
     *
     * @mbggenerated
     */
    public Long getApycid() {
        return apycid;
    }

    /**
     * 字段: tra_applycash.apycid<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 提现申请id
     *
     * @mbggenerated
     */
    public void setApycid(Long apycid) {
        this.apycid = apycid;
    }

    /**
     * @return tra_applycash.bankaccid: 银行账户id
     *
     * @mbggenerated
     */
    public Long getBankaccid() {
        return bankaccid;
    }

    /**
     * 字段: tra_applycash.bankaccid<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 银行账户id
     *
     * @mbggenerated
     */
    public void setBankaccid(Long bankaccid) {
        this.bankaccid = bankaccid;
    }

    /**
     * @return tra_applycash.orderid: 订单id
     *
     * @mbggenerated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * 字段: tra_applycash.orderid<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 订单id
     *
     * @mbggenerated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * @return tra_applycash.accno: 会员标识号
     *
     * @mbggenerated
     */
    public String getAccno() {
        return accno;
    }

    /**
     * 字段: tra_applycash.accno<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 会员标识号
     *
     * @mbggenerated
     */
    public void setAccno(String accno) {
        this.accno = accno;
    }

    /**
     * @return tra_applycash.apycdate: 申请时间
     *
     * @mbggenerated
     */
    public Date getApycdate() {
        return apycdate;
    }

    /**
     * 字段: tra_applycash.apycdate<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 申请时间
     *
     * @mbggenerated
     */
    public void setApycdate(Date apycdate) {
        this.apycdate = apycdate;
    }

    /**
     * @return tra_applycash.apycgold: 申请总金额
     *
     * @mbggenerated
     */
    public BigDecimal getApycgold() {
        return apycgold;
    }

    /**
     * 字段: tra_applycash.apycgold<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 16<br/>
     * 说明: 申请总金额
     *
     * @mbggenerated
     */
    public void setApycgold(BigDecimal apycgold) {
        this.apycgold = apycgold;
    }

    /**
     * @return tra_applycash.apycamt: 打款金额
     *
     * @mbggenerated
     */
    public BigDecimal getApycamt() {
        return apycamt;
    }

    /**
     * 字段: tra_applycash.apycamt<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 16<br/>
     * 说明: 打款金额
     *
     * @mbggenerated
     */
    public void setApycamt(BigDecimal apycamt) {
        this.apycamt = apycamt;
    }

    /**
     * @return tra_applycash.apycstatus: 申请状态  1提交申请  2提现处理中  4已打款    8已到账  9已取消
     *
     * @mbggenerated
     */
    public Integer getApycstatus() {
        return apycstatus;
    }

    /**
     * 字段: tra_applycash.apycstatus<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 1<br/>
     * 说明: 申请状态  1提交申请  2提现处理中  4已打款    8已到账  9已取消
     *
     * @mbggenerated
     */
    public void setApycstatus(Integer apycstatus) {
        this.apycstatus = apycstatus;
    }

    /**
     * @return tra_applycash.paymemname: 打款人
     *
     * @mbggenerated
     */
    public String getPaymemname() {
        return paymemname;
    }

    /**
     * 字段: tra_applycash.paymemname<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 打款人
     *
     * @mbggenerated
     */
    public void setPaymemname(String paymemname) {
        this.paymemname = paymemname;
    }

    /**
     * @return tra_applycash.paydate: 支付时间
     *
     * @mbggenerated
     */
    public Date getPaydate() {
        return paydate;
    }

    /**
     * 字段: tra_applycash.paydate<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 支付时间
     *
     * @mbggenerated
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     * @return tra_applycash.is_delete: 是否删除
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * 字段: tra_applycash.is_delete<br/>
     * 必填: true<br/>
     * 缺省: b'0'<br/>
     * 长度: 1<br/>
     * 说明: 是否删除
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * @return tra_applycash.create_user: 创建人
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * 字段: tra_applycash.create_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 创建人
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * @return tra_applycash.create_time: 创建时间
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 字段: tra_applycash.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return tra_applycash.update_user: 最后修改人
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * 字段: tra_applycash.update_user<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 最后修改人
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * @return tra_applycash.update_time: 更新时间
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 字段: tra_applycash.update_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * @return tra_applycash.damaliang: 打码量
     *
     * @mbggenerated
     */
    public BigDecimal getDamaliang() {
        return damaliang;
    }

    /**
     * 字段: tra_applycash.damaliang<br/>
     * 必填: false<br/>
     * 缺省: 0.000<br/>
     * 长度: 16<br/>
     * 说明: 打码量
     *
     * @mbggenerated
     */
    public void setDamaliang(BigDecimal damaliang) {
        this.damaliang = damaliang;
    }

    /**
     * @return tra_applycash.xingzhengfei: 行政费
     *
     * @mbggenerated
     */
    public BigDecimal getXingzhengfei() {
        return xingzhengfei;
    }

    /**
     * 字段: tra_applycash.xingzhengfei<br/>
     * 必填: false<br/>
     * 缺省: 0.000<br/>
     * 长度: 16<br/>
     * 说明: 行政费
     *
     * @mbggenerated
     */
    public void setXingzhengfei(BigDecimal xingzhengfei) {
        this.xingzhengfei = xingzhengfei;
    }

    /**
     * @return tra_applycash.bet_amount: 投注金额充值金额
     *
     * @mbggenerated
     */
    public BigDecimal getBetAmount() {
        return betAmount;
    }

    /**
     * 字段: tra_applycash.bet_amount<br/>
     * 必填: false<br/>
     * 缺省: 0.000<br/>
     * 长度: 16<br/>
     * 说明: 投注金额充值金额
     *
     * @mbggenerated
     */
    public void setBetAmount(BigDecimal betAmount) {
        this.betAmount = betAmount;
    }

    /**
     * @return tra_applycash.no_withdrawal_amount: 当前所需打码量
     *
     * @mbggenerated
     */
    public BigDecimal getNoWithdrawalAmount() {
        return noWithdrawalAmount;
    }

    /**
     * 字段: tra_applycash.no_withdrawal_amount<br/>
     * 必填: false<br/>
     * 缺省: 0.000<br/>
     * 长度: 16<br/>
     * 说明: 当前所需打码量
     *
     * @mbggenerated
     */
    public void setNoWithdrawalAmount(BigDecimal noWithdrawalAmount) {
        this.noWithdrawalAmount = noWithdrawalAmount;
    }

    /**
     * @return tra_applycash.payimg: 支付凭证截图 多张以“，”分隔
     *
     * @mbggenerated
     */
    public String getPayimg() {
        return payimg;
    }

    /**
     * 字段: tra_applycash.payimg<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 128<br/>
     * 说明: 支付凭证截图 多张以“，”分隔
     *
     * @mbggenerated
     */
    public void setPayimg(String payimg) {
        this.payimg = payimg;
    }

    /**
     * @return tra_applycash.ordertype: 提现类型，12投注分成，13礼物分成
     *
     * @mbggenerated
     */
    public Integer getOrdertype() {
        return ordertype;
    }

    /**
     * 字段: tra_applycash.ordertype<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 2<br/>
     * 说明: 提现类型，12投注分成，13礼物分成
     *
     * @mbggenerated
     */
    public void setOrdertype(Integer ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_applycash
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TraApplycash other = (TraApplycash) that;
        return (this.getApycid() == null ? other.getApycid() == null : this.getApycid().equals(other.getApycid()))
            && (this.getBankaccid() == null ? other.getBankaccid() == null : this.getBankaccid().equals(other.getBankaccid()))
            && (this.getOrderid() == null ? other.getOrderid() == null : this.getOrderid().equals(other.getOrderid()))
            && (this.getAccno() == null ? other.getAccno() == null : this.getAccno().equals(other.getAccno()))
            && (this.getApycdate() == null ? other.getApycdate() == null : this.getApycdate().equals(other.getApycdate()))
            && (this.getApycgold() == null ? other.getApycgold() == null : this.getApycgold().equals(other.getApycgold()))
            && (this.getApycamt() == null ? other.getApycamt() == null : this.getApycamt().equals(other.getApycamt()))
            && (this.getApycstatus() == null ? other.getApycstatus() == null : this.getApycstatus().equals(other.getApycstatus()))
            && (this.getPaymemname() == null ? other.getPaymemname() == null : this.getPaymemname().equals(other.getPaymemname()))
            && (this.getPaydate() == null ? other.getPaydate() == null : this.getPaydate().equals(other.getPaydate()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDamaliang() == null ? other.getDamaliang() == null : this.getDamaliang().equals(other.getDamaliang()))
            && (this.getXingzhengfei() == null ? other.getXingzhengfei() == null : this.getXingzhengfei().equals(other.getXingzhengfei()))
            && (this.getBetAmount() == null ? other.getBetAmount() == null : this.getBetAmount().equals(other.getBetAmount()))
            && (this.getNoWithdrawalAmount() == null ? other.getNoWithdrawalAmount() == null : this.getNoWithdrawalAmount().equals(other.getNoWithdrawalAmount()))
            && (this.getPayimg() == null ? other.getPayimg() == null : this.getPayimg().equals(other.getPayimg()))
            && (this.getOrdertype() == null ? other.getOrdertype() == null : this.getOrdertype().equals(other.getOrdertype()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_applycash
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getApycid() == null) ? 0 : getApycid().hashCode());
        result = prime * result + ((getBankaccid() == null) ? 0 : getBankaccid().hashCode());
        result = prime * result + ((getOrderid() == null) ? 0 : getOrderid().hashCode());
        result = prime * result + ((getAccno() == null) ? 0 : getAccno().hashCode());
        result = prime * result + ((getApycdate() == null) ? 0 : getApycdate().hashCode());
        result = prime * result + ((getApycgold() == null) ? 0 : getApycgold().hashCode());
        result = prime * result + ((getApycamt() == null) ? 0 : getApycamt().hashCode());
        result = prime * result + ((getApycstatus() == null) ? 0 : getApycstatus().hashCode());
        result = prime * result + ((getPaymemname() == null) ? 0 : getPaymemname().hashCode());
        result = prime * result + ((getPaydate() == null) ? 0 : getPaydate().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDamaliang() == null) ? 0 : getDamaliang().hashCode());
        result = prime * result + ((getXingzhengfei() == null) ? 0 : getXingzhengfei().hashCode());
        result = prime * result + ((getBetAmount() == null) ? 0 : getBetAmount().hashCode());
        result = prime * result + ((getNoWithdrawalAmount() == null) ? 0 : getNoWithdrawalAmount().hashCode());
        result = prime * result + ((getPayimg() == null) ? 0 : getPayimg().hashCode());
        result = prime * result + ((getOrdertype() == null) ? 0 : getOrdertype().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_applycash
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", apycid=").append(apycid);
        sb.append(", bankaccid=").append(bankaccid);
        sb.append(", orderid=").append(orderid);
        sb.append(", accno=").append(accno);
        sb.append(", apycdate=").append(apycdate);
        sb.append(", apycgold=").append(apycgold);
        sb.append(", apycamt=").append(apycamt);
        sb.append(", apycstatus=").append(apycstatus);
        sb.append(", paymemname=").append(paymemname);
        sb.append(", paydate=").append(paydate);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", damaliang=").append(damaliang);
        sb.append(", xingzhengfei=").append(xingzhengfei);
        sb.append(", betAmount=").append(betAmount);
        sb.append(", noWithdrawalAmount=").append(noWithdrawalAmount);
        sb.append(", payimg=").append(payimg);
        sb.append(", ordertype=").append(ordertype);
        sb.append("]");
        return sb.toString();
    }
}