package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.AgRound;
import com.likes.common.mybatis.entity.AgRoundExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgRoundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_round
     *
     * @mbggenerated
     */
    int countByExample(AgRoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_round
     *
     * @mbggenerated
     */
    int deleteByExample(AgRoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_round
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_round
     *
     * @mbggenerated
     */
    int insert(AgRound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_round
     *
     * @mbggenerated
     */
    int insertSelective(AgRound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_round
     *
     * @mbggenerated
     */
    AgRound selectOneByExample(AgRoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_round
     *
     * @mbggenerated
     */
    List<AgRound> selectByExample(AgRoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_round
     *
     * @mbggenerated
     */
    AgRound selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_round
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AgRound record, @Param("example") AgRoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_round
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AgRound record, @Param("example") AgRoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_round
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AgRound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_round
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AgRound record);
}