package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.AgTransferLog;
import com.likes.common.mybatis.entity.AgTransferLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgTransferLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_transfer_log
     *
     * @mbggenerated
     */
    int countByExample(AgTransferLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_transfer_log
     *
     * @mbggenerated
     */
    int deleteByExample(AgTransferLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_transfer_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_transfer_log
     *
     * @mbggenerated
     */
    int insert(AgTransferLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_transfer_log
     *
     * @mbggenerated
     */
    int insertSelective(AgTransferLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_transfer_log
     *
     * @mbggenerated
     */
    AgTransferLog selectOneByExample(AgTransferLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_transfer_log
     *
     * @mbggenerated
     */
    List<AgTransferLog> selectByExample(AgTransferLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_transfer_log
     *
     * @mbggenerated
     */
    AgTransferLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_transfer_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AgTransferLog record, @Param("example") AgTransferLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_transfer_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AgTransferLog record, @Param("example") AgTransferLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_transfer_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AgTransferLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_transfer_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AgTransferLog record);
}