package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.AppNotice;
import com.likes.common.mybatis.entity.AppNoticeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AppNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice
     *
     * @mbggenerated
     */
    int countByExample(AppNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice
     *
     * @mbggenerated
     */
    int deleteByExample(AppNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice
     *
     * @mbggenerated
     */
    int insert(AppNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice
     *
     * @mbggenerated
     */
    int insertSelective(AppNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice
     *
     * @mbggenerated
     */
    AppNotice selectOneByExample(AppNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice
     *
     * @mbggenerated
     */
    List<AppNotice> selectByExample(AppNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice
     *
     * @mbggenerated
     */
    AppNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppNotice record, @Param("example") AppNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppNotice record, @Param("example") AppNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppNotice record);
}