package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.AppNoticeCategory;
import com.likes.common.mybatis.entity.AppNoticeCategoryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AppNoticeCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice_category
     *
     * @mbggenerated
     */
    int countByExample(AppNoticeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice_category
     *
     * @mbggenerated
     */
    int deleteByExample(AppNoticeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice_category
     *
     * @mbggenerated
     */
    int insert(AppNoticeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice_category
     *
     * @mbggenerated
     */
    int insertSelective(AppNoticeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice_category
     *
     * @mbggenerated
     */
    AppNoticeCategory selectOneByExample(AppNoticeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice_category
     *
     * @mbggenerated
     */
    List<AppNoticeCategory> selectByExample(AppNoticeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice_category
     *
     * @mbggenerated
     */
    AppNoticeCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppNoticeCategory record, @Param("example") AppNoticeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppNoticeCategory record, @Param("example") AppNoticeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppNoticeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_notice_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppNoticeCategory record);
}