package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.BdBannerseat;
import com.likes.common.mybatis.entity.BdBannerseatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BdBannerseatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bannerseat
     *
     * @mbggenerated
     */
    int countByExample(BdBannerseatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bannerseat
     *
     * @mbggenerated
     */
    int deleteByExample(BdBannerseatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bannerseat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long bseatid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bannerseat
     *
     * @mbggenerated
     */
    int insert(BdBannerseat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bannerseat
     *
     * @mbggenerated
     */
    int insertSelective(BdBannerseat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bannerseat
     *
     * @mbggenerated
     */
    BdBannerseat selectOneByExample(BdBannerseatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bannerseat
     *
     * @mbggenerated
     */
    List<BdBannerseat> selectByExample(BdBannerseatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bannerseat
     *
     * @mbggenerated
     */
    BdBannerseat selectByPrimaryKey(Long bseatid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bannerseat
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BdBannerseat record, @Param("example") BdBannerseatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bannerseat
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BdBannerseat record, @Param("example") BdBannerseatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bannerseat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BdBannerseat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bannerseat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BdBannerseat record);
}