package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.ChessUserset;
import com.likes.common.mybatis.entity.ChessUsersetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChessUsersetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chess_userset
     *
     * @mbggenerated
     */
    int countByExample(ChessUsersetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chess_userset
     *
     * @mbggenerated
     */
    int deleteByExample(ChessUsersetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chess_userset
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long chesssetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chess_userset
     *
     * @mbggenerated
     */
    int insert(ChessUserset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chess_userset
     *
     * @mbggenerated
     */
    int insertSelective(ChessUserset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chess_userset
     *
     * @mbggenerated
     */
    ChessUserset selectOneByExample(ChessUsersetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chess_userset
     *
     * @mbggenerated
     */
    List<ChessUserset> selectByExample(ChessUsersetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chess_userset
     *
     * @mbggenerated
     */
    ChessUserset selectByPrimaryKey(Long chesssetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chess_userset
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ChessUserset record, @Param("example") ChessUsersetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chess_userset
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ChessUserset record, @Param("example") ChessUsersetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chess_userset
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChessUserset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chess_userset
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChessUserset record);
}