package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.MemberYoukeCalc;
import com.likes.common.mybatis.entity.MemberYoukeCalcExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberYoukeCalcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_youke_calc
     *
     * @mbggenerated
     */
    int countByExample(MemberYoukeCalcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_youke_calc
     *
     * @mbggenerated
     */
    int deleteByExample(MemberYoukeCalcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_youke_calc
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_youke_calc
     *
     * @mbggenerated
     */
    int insert(MemberYoukeCalc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_youke_calc
     *
     * @mbggenerated
     */
    int insertSelective(MemberYoukeCalc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_youke_calc
     *
     * @mbggenerated
     */
    MemberYoukeCalc selectOneByExample(MemberYoukeCalcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_youke_calc
     *
     * @mbggenerated
     */
    List<MemberYoukeCalc> selectByExample(MemberYoukeCalcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_youke_calc
     *
     * @mbggenerated
     */
    MemberYoukeCalc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_youke_calc
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MemberYoukeCalc record, @Param("example") MemberYoukeCalcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_youke_calc
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MemberYoukeCalc record, @Param("example") MemberYoukeCalcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_youke_calc
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberYoukeCalc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_youke_calc
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberYoukeCalc record);
}