package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.MemCertification;
import com.likes.common.mybatis.entity.MemCertificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemCertificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_certification
     *
     * @mbggenerated
     */
    int countByExample(MemCertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_certification
     *
     * @mbggenerated
     */
    int deleteByExample(MemCertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_certification
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long certid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_certification
     *
     * @mbggenerated
     */
    int insert(MemCertification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_certification
     *
     * @mbggenerated
     */
    int insertSelective(MemCertification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_certification
     *
     * @mbggenerated
     */
    MemCertification selectOneByExample(MemCertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_certification
     *
     * @mbggenerated
     */
    List<MemCertification> selectByExample(MemCertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_certification
     *
     * @mbggenerated
     */
    MemCertification selectByPrimaryKey(Long certid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_certification
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MemCertification record, @Param("example") MemCertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_certification
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MemCertification record, @Param("example") MemCertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_certification
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemCertification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_certification
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemCertification record);
}