package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.MemHotsearch;
import com.likes.common.mybatis.entity.MemHotsearchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemHotsearchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    int countByExample(MemHotsearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    int deleteByExample(MemHotsearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long searchid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    int insert(MemHotsearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    int insertSelective(MemHotsearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    MemHotsearch selectOneByExample(MemHotsearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    List<MemHotsearch> selectByExample(MemHotsearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    MemHotsearch selectByPrimaryKey(Long searchid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MemHotsearch record, @Param("example") MemHotsearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MemHotsearch record, @Param("example") MemHotsearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemHotsearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_hotsearch
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemHotsearch record);
}