package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.MemLogin;
import com.likes.common.mybatis.entity.MemLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_login
     *
     * @mbggenerated
     */
    int countByExample(MemLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_login
     *
     * @mbggenerated
     */
    int deleteByExample(MemLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_login
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long loginid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_login
     *
     * @mbggenerated
     */
    int insert(MemLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_login
     *
     * @mbggenerated
     */
    int insertSelective(MemLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_login
     *
     * @mbggenerated
     */
    MemLogin selectOneByExample(MemLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_login
     *
     * @mbggenerated
     */
    List<MemLogin> selectByExample(MemLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_login
     *
     * @mbggenerated
     */
    MemLogin selectByPrimaryKey(Long loginid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_login
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MemLogin record, @Param("example") MemLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_login
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MemLogin record, @Param("example") MemLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemLogin record);

    MemLogin selectSelectiveMemLogin(@Param("loginParam") MemLogin loginParam, @Param("logintypes") List<Integer> logintypes);
}