package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.OrderRobotRecord;
import com.likes.common.mybatis.entity.OrderRobotRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderRobotRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_robot_record
     *
     * @mbggenerated
     */
    int countByExample(OrderRobotRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_robot_record
     *
     * @mbggenerated
     */
    int deleteByExample(OrderRobotRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_robot_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_robot_record
     *
     * @mbggenerated
     */
    int insert(OrderRobotRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_robot_record
     *
     * @mbggenerated
     */
    int insertSelective(OrderRobotRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_robot_record
     *
     * @mbggenerated
     */
    OrderRobotRecord selectOneByExample(OrderRobotRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_robot_record
     *
     * @mbggenerated
     */
    List<OrderRobotRecord> selectByExample(OrderRobotRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_robot_record
     *
     * @mbggenerated
     */
    OrderRobotRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_robot_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderRobotRecord record, @Param("example") OrderRobotRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_robot_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderRobotRecord record, @Param("example") OrderRobotRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_robot_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderRobotRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_robot_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderRobotRecord record);
}