package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.OrgAdminprivilegeExample;
import com.likes.common.mybatis.entity.OrgAdminprivilegeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrgAdminprivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_adminprivilege
     *
     * @mbggenerated
     */
    int countByExample(OrgAdminprivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_adminprivilege
     *
     * @mbggenerated
     */
    int deleteByExample(OrgAdminprivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_adminprivilege
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(OrgAdminprivilegeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_adminprivilege
     *
     * @mbggenerated
     */
    int insert(OrgAdminprivilegeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_adminprivilege
     *
     * @mbggenerated
     */
    int insertSelective(OrgAdminprivilegeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_adminprivilege
     *
     * @mbggenerated
     */
    OrgAdminprivilegeKey selectOneByExample(OrgAdminprivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_adminprivilege
     *
     * @mbggenerated
     */
    List<OrgAdminprivilegeKey> selectByExample(OrgAdminprivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_adminprivilege
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrgAdminprivilegeKey record, @Param("example") OrgAdminprivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_adminprivilege
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrgAdminprivilegeKey record, @Param("example") OrgAdminprivilegeExample example);
}