package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.PaymentResultJetpay;
import com.likes.common.mybatis.entity.PaymentResultJetpayExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PaymentResultJetpayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int countByExample(PaymentResultJetpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int deleteByExample(PaymentResultJetpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int insert(PaymentResultJetpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int insertSelective(PaymentResultJetpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    PaymentResultJetpay selectOneByExample(PaymentResultJetpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    List<PaymentResultJetpay> selectByExample(PaymentResultJetpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    PaymentResultJetpay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PaymentResultJetpay record, @Param("example") PaymentResultJetpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PaymentResultJetpay record, @Param("example") PaymentResultJetpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaymentResultJetpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaymentResultJetpay record);
}