package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.PaymentSummary;
import com.likes.common.mybatis.entity.PaymentSummaryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PaymentSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_summary
     *
     * @mbggenerated
     */
    int countByExample(PaymentSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_summary
     *
     * @mbggenerated
     */
    int deleteByExample(PaymentSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_summary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_summary
     *
     * @mbggenerated
     */
    int insert(PaymentSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_summary
     *
     * @mbggenerated
     */
    int insertSelective(PaymentSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_summary
     *
     * @mbggenerated
     */
    PaymentSummary selectOneByExample(PaymentSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_summary
     *
     * @mbggenerated
     */
    List<PaymentSummary> selectByExample(PaymentSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_summary
     *
     * @mbggenerated
     */
    PaymentSummary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_summary
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PaymentSummary record, @Param("example") PaymentSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_summary
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PaymentSummary record, @Param("example") PaymentSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_summary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaymentSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_summary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaymentSummary record);
}