package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.SysErrorlog;
import com.likes.common.mybatis.entity.SysErrorlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysErrorlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    int countByExample(SysErrorlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    int deleteByExample(SysErrorlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long errlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    int insert(SysErrorlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    int insertSelective(SysErrorlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    SysErrorlog selectOneByExampleWithBLOBs(SysErrorlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    List<SysErrorlog> selectByExampleWithBLOBs(SysErrorlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    SysErrorlog selectOneByExample(SysErrorlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    List<SysErrorlog> selectByExample(SysErrorlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    SysErrorlog selectByPrimaryKey(Long errlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysErrorlog record, @Param("example") SysErrorlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") SysErrorlog record, @Param("example") SysErrorlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysErrorlog record, @Param("example") SysErrorlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysErrorlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SysErrorlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_errorlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysErrorlog record);
}