package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.SysFunctionorg;
import com.likes.common.mybatis.entity.SysFunctionorgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysFunctionorgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_functionorg
     *
     * @mbggenerated
     */
    int countByExample(SysFunctionorgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_functionorg
     *
     * @mbggenerated
     */
    int deleteByExample(SysFunctionorgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_functionorg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long sfunid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_functionorg
     *
     * @mbggenerated
     */
    int insert(SysFunctionorg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_functionorg
     *
     * @mbggenerated
     */
    int insertSelective(SysFunctionorg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_functionorg
     *
     * @mbggenerated
     */
    SysFunctionorg selectOneByExample(SysFunctionorgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_functionorg
     *
     * @mbggenerated
     */
    List<SysFunctionorg> selectByExample(SysFunctionorgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_functionorg
     *
     * @mbggenerated
     */
    SysFunctionorg selectByPrimaryKey(Long sfunid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_functionorg
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysFunctionorg record, @Param("example") SysFunctionorgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_functionorg
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysFunctionorg record, @Param("example") SysFunctionorgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_functionorg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysFunctionorg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_functionorg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysFunctionorg record);
}