package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.ThreeStrongWayDs;
import com.likes.common.mybatis.entity.ThreeStrongWayDsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ThreeStrongWayDsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_strong_way_ds
     *
     * @mbggenerated
     */
    int countByExample(ThreeStrongWayDsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_strong_way_ds
     *
     * @mbggenerated
     */
    int deleteByExample(ThreeStrongWayDsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_strong_way_ds
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_strong_way_ds
     *
     * @mbggenerated
     */
    int insert(ThreeStrongWayDs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_strong_way_ds
     *
     * @mbggenerated
     */
    int insertSelective(ThreeStrongWayDs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_strong_way_ds
     *
     * @mbggenerated
     */
    ThreeStrongWayDs selectOneByExample(ThreeStrongWayDsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_strong_way_ds
     *
     * @mbggenerated
     */
    List<ThreeStrongWayDs> selectByExample(ThreeStrongWayDsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_strong_way_ds
     *
     * @mbggenerated
     */
    ThreeStrongWayDs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_strong_way_ds
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ThreeStrongWayDs record, @Param("example") ThreeStrongWayDsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_strong_way_ds
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ThreeStrongWayDs record, @Param("example") ThreeStrongWayDsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_strong_way_ds
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ThreeStrongWayDs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_strong_way_ds
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ThreeStrongWayDs record);
}