package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.ThreeMainWayDx;
import com.likes.common.mybatis.entity.ThreeMainWayDxExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ThreeMainWayDxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_main_way_dx
     *
     * @mbggenerated
     */
    int countByExample(ThreeMainWayDxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_main_way_dx
     *
     * @mbggenerated
     */
    int deleteByExample(ThreeMainWayDxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_main_way_dx
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_main_way_dx
     *
     * @mbggenerated
     */
    int insert(ThreeMainWayDx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_main_way_dx
     *
     * @mbggenerated
     */
    int insertSelective(ThreeMainWayDx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_main_way_dx
     *
     * @mbggenerated
     */
    ThreeMainWayDx selectOneByExample(ThreeMainWayDxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_main_way_dx
     *
     * @mbggenerated
     */
    List<ThreeMainWayDx> selectByExample(ThreeMainWayDxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_main_way_dx
     *
     * @mbggenerated
     */
    ThreeMainWayDx selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_main_way_dx
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ThreeMainWayDx record, @Param("example") ThreeMainWayDxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_main_way_dx
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ThreeMainWayDx record, @Param("example") ThreeMainWayDxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_main_way_dx
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ThreeMainWayDx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_main_way_dx
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ThreeMainWayDx record);
}