package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.ThreeSmallWayDx;
import com.likes.common.mybatis.entity.ThreeSmallWayDxExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ThreeSmallWayDxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_small_way_dx
     *
     * @mbggenerated
     */
    int countByExample(ThreeSmallWayDxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_small_way_dx
     *
     * @mbggenerated
     */
    int deleteByExample(ThreeSmallWayDxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_small_way_dx
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_small_way_dx
     *
     * @mbggenerated
     */
    int insert(ThreeSmallWayDx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_small_way_dx
     *
     * @mbggenerated
     */
    int insertSelective(ThreeSmallWayDx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_small_way_dx
     *
     * @mbggenerated
     */
    ThreeSmallWayDx selectOneByExample(ThreeSmallWayDxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_small_way_dx
     *
     * @mbggenerated
     */
    List<ThreeSmallWayDx> selectByExample(ThreeSmallWayDxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_small_way_dx
     *
     * @mbggenerated
     */
    ThreeSmallWayDx selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_small_way_dx
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ThreeSmallWayDx record, @Param("example") ThreeSmallWayDxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_small_way_dx
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ThreeSmallWayDx record, @Param("example") ThreeSmallWayDxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_small_way_dx
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ThreeSmallWayDx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_small_way_dx
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ThreeSmallWayDx record);
}