package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.ThreeLargeSeedDs;
import com.likes.common.mybatis.entity.ThreeLargeSeedDsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ThreeLargeSeedDsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_large_seed_ds
     *
     * @mbggenerated
     */
    int countByExample(ThreeLargeSeedDsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_large_seed_ds
     *
     * @mbggenerated
     */
    int deleteByExample(ThreeLargeSeedDsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_large_seed_ds
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_large_seed_ds
     *
     * @mbggenerated
     */
    int insert(ThreeLargeSeedDs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_large_seed_ds
     *
     * @mbggenerated
     */
    int insertSelective(ThreeLargeSeedDs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_large_seed_ds
     *
     * @mbggenerated
     */
    ThreeLargeSeedDs selectOneByExample(ThreeLargeSeedDsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_large_seed_ds
     *
     * @mbggenerated
     */
    List<ThreeLargeSeedDs> selectByExample(ThreeLargeSeedDsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_large_seed_ds
     *
     * @mbggenerated
     */
    ThreeLargeSeedDs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_large_seed_ds
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ThreeLargeSeedDs record, @Param("example") ThreeLargeSeedDsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_large_seed_ds
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ThreeLargeSeedDs record, @Param("example") ThreeLargeSeedDsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_large_seed_ds
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ThreeLargeSeedDs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_large_seed_ds
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ThreeLargeSeedDs record);
}