package com.likes.common.mybatis.mapper;

import com.likes.common.mybatis.entity.TraOrdertracking;
import com.likes.common.mybatis.entity.TraOrdertrackingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TraOrdertrackingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_ordertracking
     *
     * @mbggenerated
     */
    int countByExample(TraOrdertrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_ordertracking
     *
     * @mbggenerated
     */
    int deleteByExample(TraOrdertrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_ordertracking
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long trackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_ordertracking
     *
     * @mbggenerated
     */
    int insert(TraOrdertracking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_ordertracking
     *
     * @mbggenerated
     */
    int insertSelective(TraOrdertracking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_ordertracking
     *
     * @mbggenerated
     */
    TraOrdertracking selectOneByExample(TraOrdertrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_ordertracking
     *
     * @mbggenerated
     */
    List<TraOrdertracking> selectByExample(TraOrdertrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_ordertracking
     *
     * @mbggenerated
     */
    TraOrdertracking selectByPrimaryKey(Long trackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_ordertracking
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TraOrdertracking record, @Param("example") TraOrdertrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_ordertracking
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TraOrdertracking record, @Param("example") TraOrdertrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_ordertracking
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TraOrdertracking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_ordertracking
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TraOrdertracking record);
}